import type { Metadata } from 'next';
import Link from 'next/link';
import { FaArrowRight, FaFilm, FaPlay, FaPlus } from 'react-icons/fa6';
import { Container } from '@/components/Container';
import { CorporatePageHero } from '@/components/CorporatePageHero';
import { getPublicClient, getLeagueSnapshot } from '@/lib/public-data';
import { MediaDirectory } from '@/components/PublicDirectory';
import type { Media } from '@/types/database';

export const revalidate = 60;
export const metadata: Metadata = { title:{absolute:'RCL TV | Richmond Basketball Highlights & Live'}, description:'Watch Rich City League live coverage and explore Richmond basketball photos, player-tagged highlights, interviews, Top Plays and RCL media.', alternates:{canonical:'/media'} };

type Highlight={id:string;player_id:string;game_id:string|null;title:string;category:string;clip_url:string|null;thumbnail_url:string|null;featured:boolean;created_at:string;player?:{first_name:string|null;last_name:string|null}|null};

export default async function MediaPage() {
  const client = getPublicClient();
  const db = client as any;
  const { games, teams } = await getLeagueSnapshot();
  const [mediaResult,highlightResult]=client?await Promise.all([
    client.from('media').select('*').eq('status','published').order('created_at',{ascending:false}).limit(60),
    db.from('player_highlights').select('id,player_id,game_id,title,category,clip_url,thumbnail_url,featured,created_at,player:players(first_name,last_name)').eq('status','published').order('featured',{ascending:false}).order('created_at',{ascending:false}).limit(30),
  ]):[{data:[]},{data:[]}];
  const items = ((mediaResult.data ?? []) as Media[]).map((item) => ({ id: item.id, title: item.title, description: item.description, type: item.media_type, url: item.storage_path, createdAt: item.created_at }));
  const highlights=(highlightResult.data??[]) as Highlight[];
  const now = Date.now();
  const nextGame = [...games].filter((game) => !['completed', 'cancelled'].includes(game.status) && new Date(game.scheduled_at).getTime() >= now).sort((a, b) => new Date(a.scheduled_at).getTime() - new Date(b.scheduled_at).getTime())[0];
  const teamName = (id: string) => teams.find((team) => team.id === id)?.name ?? 'RCL Team';
  const liveInputId = process.env.NEXT_PUBLIC_CLOUDFLARE_STREAM_LIVE_INPUT_ID?.trim();
  const customerCode = process.env.NEXT_PUBLIC_CLOUDFLARE_STREAM_CUSTOMER_CODE?.trim();
  const playerUrl = liveInputId && customerCode ? `https://customer-${customerCode}.cloudflarestream.com/${liveInputId}/iframe` : null;

  return <main className="min-h-screen bg-rcl-black pb-24 text-white">
    <CorporatePageHero eyebrow="RCL TV" title="Watch the league" accent="Live. Highlights. Stories." description="The broadcast and video home of Rich City League: live games, Top Plays, player highlights, Between the Lines, interviews, photos and the visual archive of Richmond basketball." assetKey="media.cover" actions={<><Link href="/media/submit" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-rcl-orange px-4 text-xs font-black uppercase tracking-wider text-black"><FaPlus/>Submit highlight</Link><Link href="/games" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/15 px-4 text-xs font-black uppercase tracking-wider">Game Night <FaArrowRight/></Link></>} meta={<div className="min-w-48 rounded-2xl border border-rcl-blue/20 bg-[#071522]/85 px-5 py-4 shadow-xl backdrop-blur"><p className="text-xs font-black uppercase tracking-[.18em] text-white/35">RCL TV library</p><p className="mt-1 font-display text-3xl font-black">{items.length+highlights.length}<span className="ml-2 text-xs text-white/35">items</span></p><p className="mt-2 text-xs text-rcl-orange">Live + player-tagged</p></div>} />
    <Container maxWidth="xl" className="py-10 sm:py-12">
      <section className="overflow-hidden rounded-2xl border border-rcl-blue/15 bg-[#071522]/60 shadow-[0_24px_70px_rgba(0,0,0,.22)]"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 px-5 py-4 sm:px-7"><div><p className="text-xs font-black uppercase tracking-[.22em] text-rcl-orange">RCL Broadcast Network</p><h2 className="mt-1 font-display text-2xl font-black uppercase">Live Court</h2></div><span className="rounded-full border border-rcl-orange/30 bg-rcl-orange/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.16em] text-rcl-orange">Live & Replay</span></div><div className="aspect-video w-full bg-black">{playerUrl ? <iframe src={playerUrl} title="Rich City League Live" className="h-full w-full border-0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /> : <div className="flex h-full flex-col items-center justify-center px-6 text-center"><FaPlay className="text-3xl text-rcl-blue"/><p className="mt-4 text-xs font-black uppercase tracking-[.25em] text-rcl-orange">Broadcast setup in progress</p><h3 className="mt-3 font-display text-2xl font-black uppercase sm:text-4xl">RCL Live is coming online.</h3><p className="mt-3 max-w-xl text-sm leading-6 text-white/40">The live player activates here when the RCL Stream input is connected.</p></div>}</div><div className="grid gap-4 px-5 py-5 sm:px-7 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-xs font-black uppercase tracking-[.18em] text-white/30">{nextGame ? 'Next broadcast' : 'RCL Live'}</p><h3 className="mt-2 font-display text-lg font-black uppercase sm:text-xl">{nextGame ? `${teamName(nextGame.away_team_id)} vs ${teamName(nextGame.home_team_id)}` : 'Broadcast schedule coming soon'}</h3>{nextGame && <p className="mt-1 text-sm text-white/40">{new Date(nextGame.scheduled_at).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/New_York' })}</p>}</div><div className="md:text-right"><p className="text-xs font-black uppercase tracking-[.18em] text-rcl-blue">Watch here</p><p className="mt-1 text-xs text-white/35">No external app required.</p></div></div></section>

      <section className="mt-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.22em] text-rcl-orange"><FaFilm className="mr-1 inline"/>Highlight engine</p><h2 className="mt-1 font-display text-3xl font-black uppercase">Top Plays & player tape</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/40">Tagged clips attach to the player’s Basketball Passport and, when available, the official game.</p></div><Link href="/media/submit" className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-wider text-rcl-blue">Add a clip <FaArrowRight/></Link></div>{highlights.length?<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{highlights.map(h=><a key={h.id} href={h.clip_url??(h.game_id?`/games/${h.game_id}`:`/players/${h.player_id}/passport`)} className="group rounded-2xl border border-white/10 bg-[#071018] p-4 transition hover:border-rcl-blue/35"><div className="relative grid aspect-video place-items-center overflow-hidden rounded-xl bg-[radial-gradient(circle_at_center,rgba(26,155,220,.16),transparent_55%),#020408]">{h.thumbnail_url?<img src={h.thumbnail_url} alt="" className="absolute inset-0 h-full w-full object-cover opacity-80"/>:null}<span className="relative z-10 grid h-11 w-11 place-items-center rounded-full bg-black/60 text-rcl-blue backdrop-blur"><FaPlay/></span>{h.featured&&<span className="absolute left-2 top-2 rounded-full bg-rcl-orange px-2 py-1 text-[8px] font-black uppercase tracking-wider text-black">Featured</span>}</div><p className="mt-3 text-[9px] font-black uppercase tracking-wider text-rcl-orange">{h.category.replace(/_/g,' ')}</p><h3 className="mt-1 line-clamp-2 font-black">{h.title}</h3><p className="mt-2 text-xs text-white/35">{h.player?`${h.player.first_name??''} ${h.player.last_name??''}`.trim():'RCL Player'}</p></a>)}</div>:<div className="mt-6 rounded-2xl border border-dashed border-white/10 p-9 text-center"><FaFilm className="mx-auto text-3xl text-rcl-blue"/><h3 className="mt-3 font-display text-xl font-black uppercase">The player-tagged tape starts here</h3><p className="mt-2 text-sm text-white/35">Submit highlights and connect them to an RCL player and game.</p></div>}</section>

      <section className="mt-12"><div className="mb-6"><p className="text-xs font-black uppercase tracking-[.22em] text-rcl-orange">RCL archive</p><h2 className="mt-1 font-display text-3xl font-black uppercase">Photos, interviews & media</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/40">Browse the published RCL media library without leaving the platform.</p></div><MediaDirectory items={items} /></section>
    </Container>
  </main>;
}
