'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Container } from '@/components/Container';
import { useAuth } from '@/hooks/useAuth';
import { getSupabaseClient } from '@/lib/supabase';
import { NETWORK_CREDIT_LABELS, type NetworkCreditType } from '@/lib/network-partner';
import { FaArrowRight, FaBolt, FaBullhorn, FaCircleCheck } from 'react-icons/fa6';

type Membership={organization_id:string;organization:{id:string;name:string}|null};
type Ledger={credit_type:NetworkCreditType;quantity:number};
const regions=[['statewide','Statewide Virginia'],['central-virginia','Central Virginia'],['tri-cities','Tri-Cities'],['hampton-roads','Hampton Roads'],['northern-virginia','Northern Virginia'],['shenandoah','Shenandoah'],['southwest-virginia','Southwest Virginia']] as const;
const objectives=[['awareness','Awareness'],['event-traffic','Event traffic'],['website-traffic','Website traffic'],['media-views','Media views'],['audience-growth','Audience growth']] as const;
const input='min-h-11 w-full rounded-xl border border-white/10 bg-[#050b12] px-3 text-sm text-white outline-none focus:border-rcl-blue/55';

export default function NetworkBoostBuilderPage(){
 const {user,loading:authLoading}=useAuth(); const supabase=useMemo(()=>getSupabaseClient(),[]); const db=supabase as any;
 const [memberships,setMemberships]=useState<Membership[]>([]); const [organizationId,setOrganizationId]=useState(''); const [ledger,setLedger]=useState<Ledger[]>([]); const [busy,setBusy]=useState(''); const [message,setMessage]=useState('');
 const [form,setForm]=useState({name:'',objective:'awareness',creditType:'event-spotlight' as NetworkCreditType,destinationUrl:'',headline:'',startsAt:'',endsAt:'',region:'statewide'});
 useEffect(()=>{if(!authLoading&&user)void loadOrgs();},[authLoading,user]); useEffect(()=>{if(organizationId)void loadCredits(organizationId);},[organizationId]);
 async function loadOrgs(){const {data}=await db.from('network_organization_members').select('organization_id,organization:network_organizations!organization_id(id,name)').eq('profile_id',user!.id).eq('status','active');const rows=(data??[]).map((r:any)=>({...r,organization:Array.isArray(r.organization)?r.organization[0]:r.organization}));setMemberships(rows);if(rows[0]?.organization_id)setOrganizationId(rows[0].organization_id);}
 async function loadCredits(orgId:string){const {data}=await db.from('network_partner_credit_ledger').select('credit_type,quantity').eq('organization_id',orgId);setLedger(data??[]);}
 const balances=new Map<NetworkCreditType,number>();ledger.forEach(row=>balances.set(row.credit_type,(balances.get(row.credit_type)??0)+Number(row.quantity||0))); const available=Math.max(0,balances.get(form.creditType)??0);
 async function submit(){setMessage('');if(!form.name.trim()||!form.startsAt||!form.endsAt||!form.destinationUrl.trim()){setMessage('Campaign name, dates and destination URL are required.');return;}setBusy('submit');const {data,error}=await db.rpc('submit_network_campaign_with_credit',{p_organization_id:organizationId,p_name:form.name.trim(),p_objective:form.objective,p_credit_type:form.creditType,p_destination_url:form.destinationUrl.trim(),p_headline:form.headline.trim()||null,p_requested_starts_at:new Date(form.startsAt).toISOString(),p_requested_ends_at:new Date(form.endsAt).toISOString(),p_target_regions:[form.region]});setBusy('');if(error){setMessage(error.message);return;}setMessage(`Campaign submitted for RCL review. ${data?'Reference '+String(data).slice(0,8):''}`);setForm({...form,name:'',headline:'',destinationUrl:''});await loadCredits(organizationId);}
 async function buyCredit(){setBusy('buy');setMessage('');const response=await fetch('/api/network/billing/boost',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId,creditType:form.creditType})});const payload=await response.json().catch(()=>({}));setBusy('');if(!response.ok){setMessage(payload.message||payload.error||'Unable to start Boost checkout.');return;}window.location.assign(payload.url);}
 if(authLoading)return null;
 return <main className="min-h-screen bg-[#03070d] pb-24 text-white"><Container maxWidth="xl" className="py-10 sm:py-14"><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-orange">RCL Reach</p><h1 className="mt-2 font-display text-5xl font-black uppercase">Build a <span className="text-rcl-blue">Boost.</span></h1><p className="mt-4 max-w-3xl text-sm leading-6 text-white/45">Use earned or purchased exposure inventory to submit a campaign. RCL still reviews the creative, dates and placement before delivery begins.</p>{message&&<p className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/[.06] p-4 text-sm text-amber-100">{message}</p>}
 <section className="mt-8 grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><aside className="rounded-3xl border border-white/10 bg-white/[.025] p-6"><FaBolt className="text-rcl-orange"/><h2 className="mt-3 font-display text-2xl font-black uppercase">Your inventory</h2><select className={`${input} mt-4`} value={organizationId} onChange={e=>setOrganizationId(e.target.value)}>{memberships.map(m=><option key={m.organization_id} value={m.organization_id}>{m.organization?.name??'Organization'}</option>)}</select><div className="mt-5 space-y-2">{(Object.keys(NETWORK_CREDIT_LABELS) as NetworkCreditType[]).map(type=><button key={type} onClick={()=>setForm({...form,creditType:type})} className={`flex w-full items-center justify-between rounded-xl border p-3 text-left ${form.creditType===type?'border-rcl-blue/45 bg-rcl-blue/[.08]':'border-white/8 bg-black/15'}`}><span className="text-xs font-bold">{NETWORK_CREDIT_LABELS[type]}</span><b className="text-rcl-blue">{Math.max(0,balances.get(type)??0)}</b></button>)}</div><div className="mt-5 rounded-xl border border-white/8 bg-black/20 p-4"><p className="text-[10px] font-black uppercase tracking-[.14em] text-white/30">Selected credit</p><p className="mt-1 text-lg font-black">{NETWORK_CREDIT_LABELS[form.creditType]}</p><p className="mt-1 text-sm text-white/40">{available} available</p>{available<1&&<button onClick={()=>void buyCredit()} disabled={busy==='buy'} className="mt-4 min-h-11 w-full rounded-xl border border-rcl-orange/30 px-4 text-xs font-black uppercase text-rcl-orange">{busy==='buy'?'Opening Checkout…':'Buy one Boost'}</button>}<Link href="/network/dashboard/billing" className="mt-3 inline-flex items-center gap-2 text-[11px] font-black uppercase text-rcl-blue">Partner plans <FaArrowRight/></Link></div></aside>
 <section className="rounded-3xl border border-rcl-blue/15 bg-[#071522]/55 p-6"><div className="flex items-center gap-3"><FaBullhorn className="text-rcl-blue"/><h2 className="font-display text-2xl font-black uppercase">Campaign request</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Campaign name"><input className={input} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} maxLength={180}/></Field><Field label="Goal"><select className={input} value={form.objective} onChange={e=>setForm({...form,objective:e.target.value})}>{objectives.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Starts"><input type="datetime-local" className={input} value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></Field><Field label="Ends"><input type="datetime-local" className={input} value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></Field><Field label="Virginia target"><select className={input} value={form.region} onChange={e=>setForm({...form,region:e.target.value})}>{regions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><div/><div className="sm:col-span-2"><Field label="Sponsored headline"><input className={input} value={form.headline} onChange={e=>setForm({...form,headline:e.target.value})} maxLength={180}/></Field></div><div className="sm:col-span-2"><Field label="Destination URL"><input type="url" className={input} value={form.destinationUrl} onChange={e=>setForm({...form,destinationUrl:e.target.value})} placeholder="https://..."/></Field></div></div><button onClick={()=>void submit()} disabled={busy==='submit'||available<1} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-xl bg-rcl-orange px-5 text-xs font-black uppercase text-black disabled:opacity-40"><FaCircleCheck/>{busy==='submit'?'Submitting…':available<1?'Credit required':'Submit for RCL review'}</button><p className="mt-4 text-[11px] leading-5 text-white/30">Submitting consumes one credit immediately and creates a pending campaign. Rejected campaigns can be restored manually by RCL. Paid visibility never affects REP, ratings, rankings, stats, awards or selection.</p></section></section>
 </Container></main>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-[10px] font-black uppercase tracking-[.13em] text-white/35">{label}<div className="mt-2">{children}</div></label>}
