'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Container } from '@/components/Container';
import { useAuth } from '@/hooks/useAuth';
import { getSupabaseClient } from '@/lib/supabase';
import { FaArrowLeft, FaArrowRight, FaCircleCheck, FaPenToSquare, FaShieldHalved } from 'react-icons/fa6';

type Organization={id:string;slug:string;name:string;short_name:string|null;description:string|null;city:string|null;website_url:string|null;instagram_url:string|null;facebook_url:string|null;x_url:string|null;youtube_url:string|null;logo_url:string|null;cover_url:string|null;network_tier:string;is_verified:boolean};
type Membership={organization_id:string;member_role:string;organization:Organization};
const input='min-h-11 w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none focus:border-rcl-blue/55';

export default function OrganizationProfileManagerPage(){
  const {user,loading:authLoading}=useAuth(); const supabase=useMemo(()=>getSupabaseClient(),[]); const db=supabase as any;
  const [memberships,setMemberships]=useState<Membership[]>([]); const [selected,setSelected]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const load=useCallback(async()=>{if(!user)return;setLoading(true);const {data,error:loadError}=await db.from('network_organization_members').select('organization_id,member_role,organization:network_organizations!organization_id(id,slug,name,short_name,description,city,website_url,instagram_url,facebook_url,x_url,youtube_url,logo_url,cover_url,network_tier,is_verified)').eq('status','active');if(loadError)setError(loadError.message);const rows=(data??[]).map((row:any)=>({...row,organization:Array.isArray(row.organization)?row.organization[0]:row.organization})).filter((row:any)=>row.organization) as Membership[];setMemberships(rows);setSelected(current=>current||rows[0]?.organization_id||'');setLoading(false)},[db,user]);
  useEffect(()=>{if(!authLoading){if(user)void load();else setLoading(false)}},[authLoading,user,load]);
  if(authLoading||loading)return <Shell><p className="text-sm text-white/40">Loading organization access…</p></Shell>;
  if(!user)return <Shell><AccessCard title="Sign in to manage a Network listing." body="Profile management is tied to verified organization access." href="/auth/sign-in?next=/network/dashboard/profile" action="Sign in"/></Shell>;
  if(!memberships.length)return <Shell><AccessCard title="Claim an organization first." body="Once RCH verifies that you represent an organization, free profile management unlocks here." href="/organizations" action="Find your organization"/></Shell>;
  const membership=memberships.find(item=>item.organization_id===selected)??memberships[0];
  return <Shell>
    <Link href="/network/dashboard" className="inline-flex items-center gap-2 text-xs font-black uppercase text-white/40"><FaArrowLeft/> Partner dashboard</Link>
    <div className="mt-7 grid gap-6 lg:grid-cols-[320px_1fr]">
      <aside className="space-y-4"><div className="rounded-3xl border border-rcl-blue/20 bg-[#071522]/65 p-5"><p className="text-[10px] font-black uppercase tracking-[.16em] text-rcl-blue">Free Network benefit</p><h1 className="mt-2 font-display text-4xl font-black uppercase">Own your public presence.</h1><p className="mt-3 text-sm leading-6 text-white/45">Keep your listing accurate, publish events through RCH review, and measure the audience RCH sends your way. Paid promotion is optional.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><label className="text-[9px] font-black uppercase tracking-[.15em] text-white/35">Organization</label><select value={membership.organization_id} onChange={e=>setSelected(e.target.value)} className={`${input} mt-2`}>{memberships.map(item=><option key={item.organization_id} value={item.organization_id}>{item.organization.name}</option>)}</select></div><Completeness organization={membership.organization}/></aside>
      <ProfileForm key={membership.organization_id} organization={membership.organization} db={db} onBusy={setBusy} busy={busy} onSuccess={async()=>{setMessage('Organization profile updated.');setError('');await load()}} onError={setError}/>
    </div>
    {message&&<p className="mt-5 rounded-xl border border-emerald-400/20 bg-emerald-400/[.05] p-4 text-sm text-emerald-200">{message}</p>}{error&&<p className="mt-5 rounded-xl border border-red-400/20 bg-red-500/10 p-4 text-sm text-red-200">{error}</p>}
  </Shell>;
}

function ProfileForm({organization,db,busy,onBusy,onSuccess,onError}:{organization:Organization;db:any;busy:boolean;onBusy:(v:boolean)=>void;onSuccess:()=>void;onError:(v:string)=>void}){
  const [form,setForm]=useState({shortName:organization.short_name??'',description:organization.description??'',city:organization.city??'',website:organization.website_url??'',instagram:organization.instagram_url??'',facebook:organization.facebook_url??'',x:organization.x_url??'',youtube:organization.youtube_url??'',logo:organization.logo_url??'',cover:organization.cover_url??''});
  const submit=async(e:React.FormEvent)=>{e.preventDefault();onBusy(true);onError('');const {error}=await db.rpc('update_network_organization_profile',{p_organization_id:organization.id,p_short_name:form.shortName||null,p_description:form.description||null,p_city:form.city||null,p_website_url:form.website||null,p_instagram_url:form.instagram||null,p_facebook_url:form.facebook||null,p_x_url:form.x||null,p_youtube_url:form.youtube||null,p_logo_url:form.logo||null,p_cover_url:form.cover||null});onBusy(false);if(error)return onError(error.message);await onSuccess()};
  const set=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}));
  return <form onSubmit={submit} className="rounded-3xl border border-rcl-blue/20 bg-[#071522]/65 p-5 sm:p-7"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-rcl-orange">Public profile</p><h2 className="mt-1 font-display text-4xl font-black uppercase">{organization.name}</h2></div>{organization.is_verified&&<FaCircleCheck className="text-xl text-rcl-blue"/>}</div><p className="mt-3 text-xs leading-5 text-white/35">Organization name, verification, tier, status, and featured placement remain RCH-controlled. The fields below are yours to maintain.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Short name"><input className={input} value={form.shortName} onChange={e=>set('shortName',e.target.value)} maxLength={40}/></Field><Field label="City"><input className={input} value={form.city} onChange={e=>set('city',e.target.value)} maxLength={120}/></Field><div className="sm:col-span-2"><Field label="About the organization"><textarea className={`${input} min-h-32 resize-y`} value={form.description} onChange={e=>set('description',e.target.value)} maxLength={4000}/></Field></div><Field label="Website"><input className={input} type="url" value={form.website} onChange={e=>set('website',e.target.value)} placeholder="https://"/></Field><Field label="Instagram"><input className={input} type="url" value={form.instagram} onChange={e=>set('instagram',e.target.value)} placeholder="https://"/></Field><Field label="Facebook"><input className={input} type="url" value={form.facebook} onChange={e=>set('facebook',e.target.value)} placeholder="https://"/></Field><Field label="X / Twitter"><input className={input} type="url" value={form.x} onChange={e=>set('x',e.target.value)} placeholder="https://"/></Field><Field label="YouTube"><input className={input} type="url" value={form.youtube} onChange={e=>set('youtube',e.target.value)} placeholder="https://"/></Field><Field label="Logo image URL"><input className={input} type="url" value={form.logo} onChange={e=>set('logo',e.target.value)} placeholder="https://"/></Field><div className="sm:col-span-2"><Field label="Cover image URL"><input className={input} type="url" value={form.cover} onChange={e=>set('cover',e.target.value)} placeholder="https://"/></Field></div></div><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-5"><Link href={`/organizations/${organization.slug}`} className="inline-flex items-center gap-2 text-xs font-black uppercase text-rcl-blue">View public listing <FaArrowRight/></Link><button disabled={busy} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-rcl-orange px-4 text-xs font-black uppercase text-black disabled:opacity-50"><FaPenToSquare/>{busy?'Saving…':'Save public profile'}</button></div></form>;
}

function Completeness({organization}:{organization:Organization}){const items=[['Description',organization.description],['City',organization.city],['Website',organization.website_url],['Instagram',organization.instagram_url],['Logo',organization.logo_url],['Cover image',organization.cover_url]] as const;const complete=items.filter(([,value])=>Boolean(value)).length;const pct=Math.round((complete/items.length)*100);return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.15em] text-white/35">Profile completeness</p><b className="text-rcl-blue">{pct}%</b></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-rcl-blue" style={{width:`${pct}%`}}/></div><div className="mt-4 space-y-2">{items.map(([label,value])=><div key={label} className="flex items-center gap-2 text-xs"><FaCircleCheck className={value?'text-emerald-300':'text-white/15'}/><span className={value?'text-white/55':'text-white/25'}>{label}</span></div>)}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-[10px] font-black uppercase tracking-[.14em] text-white/45">{label}</span>{children}</label>}
function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen bg-[#03070d] pb-24 text-white"><Container maxWidth="xl" className="py-12 sm:py-16">{children}</Container></main>}
function AccessCard({title,body,href,action}:{title:string;body:string;href:string;action:string}){return <div className="max-w-2xl rounded-3xl border border-rcl-blue/20 bg-[#071522]/70 p-7"><FaShieldHalved className="text-2xl text-rcl-blue"/><h1 className="mt-3 font-display text-4xl font-black uppercase">{title}</h1><p className="mt-3 text-sm leading-6 text-white/50">{body}</p><Link href={href} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-xl bg-rcl-blue px-5 text-xs font-black uppercase text-[#03101a]">{action}<FaArrowRight/></Link></div>}
