'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { FaArrowRight, FaBasketball, FaBookmark, FaCalendarDays, FaChartLine, FaCircleCheck, FaCrown, FaDownload, FaLocationDot, FaLock, FaRegBookmark, FaSliders, FaStar } from 'react-icons/fa6';
import { Container } from '@/components/Container';
import { useAuth } from '@/hooks/useAuth';
import { getSupabaseClient } from '@/lib/supabase';
import { MEMBERSHIP_PLANS, hasMembershipEntitlement, isMembershipPlanCode, type MembershipPlanCode } from '@/lib/membership';

type SavedItem={id:string;item_type:string;item_id:string};
type Preference={regions:string[];event_types:string[];run_skill_levels:string[];digest_frequency:string};
type Org={id:string;name:string;slug:string;region:string;city:string|null;organization_type:string};
type Event={id:string;title:string;slug:string;event_type:string;city:string|null;state:string;starts_at:string;organization_id:string;organization?:Org|null};
type Run={id:string;title:string;court_name:string;location:string;starts_at:string;skill_level:string;max_players:number};
type Game={id:string;scheduled_at:string;status:string;home?:{name?:string|null}|null;away?:{name?:string|null}|null};
type Exposure={metric_date:string;profile_views:number;passport_views:number;profile_shares:number;media_views:number};
type Spotlight={id:string;status:string;requested_month:string;created_at:string;target_type:string};

const REGIONS=[['central-virginia','Central Virginia'],['hampton-roads','Hampton Roads'],['northern-virginia','Northern Virginia'],['shenandoah-valley','Shenandoah Valley'],['southwest-virginia','Southwest Virginia'],['statewide','Statewide']] as const;
const EVENT_TYPES=['league','tournament','showcase','tryout','camp','clinic','run'];
const RUN_SKILLS=['all-levels','recreational','competitive','advanced'];
const fmt=(value:string)=>new Date(value).toLocaleString('en-US',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/New_York'});

export default function MyHoopsPage(){
 const {user,loading:authLoading}=useAuth();const supabase=useMemo(()=>getSupabaseClient(true),[]);const db=supabase as any;
 const [plan,setPlan]=useState<MembershipPlanCode>('free');const [saved,setSaved]=useState<SavedItem[]>([]);const [prefs,setPrefs]=useState<Preference>({regions:['central-virginia'],event_types:[],run_skill_levels:[],digest_frequency:'weekly'});const [orgs,setOrgs]=useState<Org[]>([]);const [events,setEvents]=useState<Event[]>([]);const [runs,setRuns]=useState<Run[]>([]);const [games,setGames]=useState<Game[]>([]);const [exposure,setExposure]=useState<Exposure[]>([]);const [spotlight,setSpotlight]=useState<Spotlight|null>(null);const [playerId,setPlayerId]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');const [error,setError]=useState('');
 const plus=hasMembershipEntitlement(plan,'my_hoops');const allAccess=hasMembershipEntitlement(plan,'monthly_spotlight');

 const load=useCallback(async()=>{if(!db||!user){setLoading(false);return;}setLoading(true);setError('');const now=new Date().toISOString();const [{data:planRaw},{data:savedRaw},{data:prefsRaw},{data:playerRaw}]=await Promise.all([db.rpc('current_membership_plan'),db.from('member_saved_items').select('id,item_type,item_id').eq('user_id',user.id).order('created_at',{ascending:false}),db.from('member_opportunity_preferences').select('regions,event_types,run_skill_levels,digest_frequency').eq('user_id',user.id).maybeSingle(),db.from('players').select('id').eq('profile_id',user.id).eq('is_active',true).maybeSingle()]);
 const resolvedPlan=isMembershipPlanCode(planRaw)?planRaw:'free';const resolvedPrefs:Preference=prefsRaw??{regions:['central-virginia'],event_types:[],run_skill_levels:[],digest_frequency:'weekly'};setPlan(resolvedPlan);setSaved((savedRaw??[]) as SavedItem[]);setPrefs(resolvedPrefs);setPlayerId(playerRaw?.id??null);
 const selectedRegions=resolvedPrefs.regions.length?resolvedPrefs.regions:['central-virginia'];const {data:orgRows}=await db.from('network_organizations').select('id,name,slug,region,city,organization_type').in('region',selectedRegions).eq('status','active').order('is_featured',{ascending:false}).limit(100);const organizationRows=(orgRows??[]) as Org[];setOrgs(organizationRows);const ids=organizationRows.map(o=>o.id);
 if(resolvedPlan!=='free'&&ids.length){let q=db.from('network_events').select('id,title,slug,event_type,city,state,starts_at,organization_id').in('organization_id',ids).eq('status','published').gte('starts_at',now).order('starts_at').limit(24);if(resolvedPrefs.event_types.length)q=q.in('event_type',resolvedPrefs.event_types);const {data}=await q;const map=new Map(organizationRows.map(o=>[o.id,o]));setEvents(((data??[]) as Event[]).map(e=>({...e,organization:map.get(e.organization_id)??null})));}else setEvents([]);
 let runQuery=db.from('runs').select('id,title,court_name,location,starts_at,skill_level,max_players').neq('status','cancelled').gte('starts_at',now).order('starts_at').limit(16);if(resolvedPlan!=='free'&&resolvedPrefs.run_skill_levels.length)runQuery=runQuery.in('skill_level',resolvedPrefs.run_skill_levels);const [{data:runRows},{data:gameRows}]=await Promise.all([runQuery,db.from('games').select('id,scheduled_at,status,home:teams!games_home_team_id_fkey(name),away:teams!games_away_team_id_fkey(name)').in('status',['scheduled','live']).gte('scheduled_at',new Date(Date.now()-3*60*60*1000).toISOString()).order('scheduled_at').limit(10)]);setRuns((runRows??[]) as Run[]);setGames((gameRows??[]) as Game[]);
 if(resolvedPlan!=='free'){const [{data:exposureRows},{data:spotlightRows}]=await Promise.all([db.from('profile_exposure_daily').select('metric_date,profile_views,passport_views,profile_shares,media_views').eq('profile_id',user.id).order('metric_date',{ascending:false}).limit(30),db.from('member_spotlight_requests').select('id,status,requested_month,created_at,target_type').eq('user_id',user.id).order('created_at',{ascending:false}).limit(1)]);setExposure((exposureRows??[]) as Exposure[]);setSpotlight((spotlightRows??[])[0]??null);}else{setExposure([]);setSpotlight(null);}setLoading(false);},[db,user]);
 useEffect(()=>{if(!authLoading)void load();},[authLoading,load]);

 const savedKey=(type:string,id:string)=>saved.some(row=>row.item_type===type&&row.item_id===id);
 async function toggleSave(type:string,id:string){if(!db||!user||busy)return;setBusy(`save-${type}-${id}`);setError('');const existing=saved.find(row=>row.item_type===type&&row.item_id===id);if(existing){const {error:e}=await db.from('member_saved_items').delete().eq('id',existing.id);if(e)setError(e.message);}else{const {error:e}=await db.from('member_saved_items').insert({user_id:user.id,item_type:type,item_id:id});if(e)setError(e.message);}setBusy('');await load();}
 function toggleArray(key:'regions'|'event_types'|'run_skill_levels',value:string){setPrefs(current=>{const has=current[key].includes(value);return {...current,[key]:has?current[key].filter(v=>v!==value):[...current[key],value]};});}
 async function savePreferences(){if(!db||!user||busy)return;setBusy('prefs');setError('');setNotice('');const {error:e}=await db.from('member_opportunity_preferences').upsert({user_id:user.id,...prefs,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(e)setError(e.message);else setNotice('My Hoops preferences updated.');setBusy('');await load();}
 async function requestSpotlight(){if(busy)return;setBusy('spotlight');setError('');setNotice('');const response=await fetch('/api/membership/spotlight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetType:'profile',note:'Feature my RCL profile in discovery this month.'})});const payload=await response.json();if(!response.ok)setError(payload.message||payload.error||'Unable to request Spotlight.');else setNotice('Spotlight request submitted for RCL review.');setBusy('');await load();}
 const totals=exposure.reduce((sum,row)=>({profile_views:sum.profile_views+row.profile_views,passport_views:sum.passport_views+row.passport_views,profile_shares:sum.profile_shares+row.profile_shares,media_views:sum.media_views+row.media_views}),{profile_views:0,passport_views:0,profile_shares:0,media_views:0});

 return <main className="rcl-social-world min-h-screen bg-[#03070d] pb-28 text-white"><section className="border-b border-white/10 bg-[radial-gradient(circle_at_78%_10%,rgba(21,159,255,.16),transparent_34%),radial-gradient(circle_at_12%_25%,rgba(249,115,22,.15),transparent_32%),#050a10] py-12"><Container maxWidth="xl"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.25em] text-rcl-blue">My Hoops · {MEMBERSHIP_PLANS[plan].name}</p><h1 className="mt-3 font-display text-4xl font-black uppercase sm:text-6xl">Your basketball world. <span className="text-rcl-orange">One board.</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-white/50">Personalize what you want to see across RCL, the Virginia Network, Runs and the flagship league. Save it, track it and act before the opportunity passes.</p></div><div className="flex flex-wrap gap-2"><Link href="/account/membership" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/15 px-4 text-xs font-black uppercase">Membership</Link>{plus&&<a href="/api/membership/calendar" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-rcl-orange px-4 text-xs font-black uppercase text-black"><FaDownload/> Export calendar</a>}</div></div></Container></section>
 <Container maxWidth="xl" className="py-8">{notice&&<div className="mb-5 rounded-2xl border border-emerald-400/20 bg-emerald-400/[.05] p-4 text-sm text-emerald-100">{notice}</div>}{error&&<div className="mb-5 rounded-2xl border border-red-400/20 bg-red-400/[.05] p-4 text-sm text-red-100">{error}</div>}{(loading||authLoading)?<div className="h-72 animate-pulse rounded-3xl border border-white/10 bg-white/[.02]"/>:<>
 {!plus&&<section className="rounded-3xl border border-rcl-orange/25 bg-rcl-orange/[.035] p-7 sm:p-9"><div className="grid gap-7 lg:grid-cols-[1fr_.75fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.2em] text-rcl-orange"><FaLock className="mr-2 inline"/>RCL+ command center</p><h2 className="mt-3 font-display text-3xl font-black uppercase sm:text-4xl">Free gives you the network. RCL+ organizes it around you.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/50">Personalized Virginia opportunities, saves, a unified basketball calendar, profile analytics and Passport Studio tools activate with RCL+.</p><Link href="/account/membership" className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-xl bg-rcl-orange px-5 text-xs font-black uppercase text-black">See RCL+ <FaArrowRight/></Link></div><div className="grid grid-cols-2 gap-3">{[['Saved world','Organizations + events'],['Calendar','One basketball timeline'],['Analytics','Know your reach'],['Passport Studio','Build your identity']].map(([a,b])=><div key={a} className="rounded-2xl border border-white/10 bg-black/25 p-4"><b className="text-sm">{a}</b><p className="mt-1 text-xs text-white/35">{b}</p></div>)}</div></div></section>}
 {plus&&<><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[['Profile views',totals.profile_views],['Passport views',totals.passport_views],['Profile shares',totals.profile_shares],['Media views',totals.media_views]].map(([label,value])=><article key={String(label)} className="rounded-2xl border border-white/10 bg-white/[.02] p-5"><p className="text-[10px] font-black uppercase tracking-wider text-white/35">30-day {label}</p><p className="mt-2 font-display text-4xl font-black">{value}</p></article>)}</section>
 <section className="mt-6 rounded-3xl border border-rcl-blue/20 bg-[#071522]/45 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-blue"><FaSliders className="mr-2 inline"/>Opportunity preferences</p><h2 className="mt-2 font-display text-2xl font-black uppercase">Tell My Hoops what matters.</h2></div><button onClick={savePreferences} disabled={Boolean(busy)} className="rounded-xl bg-rcl-blue px-4 py-3 text-xs font-black uppercase text-black disabled:opacity-50">{busy==='prefs'?'Saving…':'Save preferences'}</button></div><div className="mt-5 grid gap-5 lg:grid-cols-3"><PreferenceGroup title="Virginia regions" values={REGIONS.map(([value,label])=>({value,label}))} selected={prefs.regions} onToggle={v=>toggleArray('regions',v)}/><PreferenceGroup title="Event types" values={EVENT_TYPES.map(value=>({value,label:value.replace(/-/g,' ')}))} selected={prefs.event_types} onToggle={v=>toggleArray('event_types',v)}/><PreferenceGroup title="Run level" values={RUN_SKILLS.map(value=>({value,label:value.replace(/-/g,' ')}))} selected={prefs.run_skill_levels} onToggle={v=>toggleArray('run_skill_levels',v)}/></div></section>
 <section className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><article className="rounded-3xl border border-white/10 bg-[#071018] p-6"><SectionTitle icon={<FaLocationDot/>} eyebrow="Virginia Network" title="Opportunities for you"/><div className="mt-5 space-y-3">{events.length?events.slice(0,10).map(event=><OpportunityRow key={event.id} title={event.title} meta={`${event.organization?.name??'Virginia basketball'} · ${event.event_type} · ${fmt(event.starts_at)}`} href={`/network/events/${event.slug}`} saved={savedKey('network_event',event.id)} busy={busy===`save-network_event-${event.id}`} onSave={()=>toggleSave('network_event',event.id)}/>):<Empty text="No matching Network events are published yet. Your preferences are saved for when the Network fills in."/>}</div></article><article className="rounded-3xl border border-white/10 bg-white/[.02] p-6"><SectionTitle icon={<FaBasketball/>} eyebrow="Runs" title="Courts moving next"/><div className="mt-5 space-y-3">{runs.slice(0,6).map(run=><OpportunityRow key={run.id} title={run.title} meta={`${run.court_name||run.location} · ${run.skill_level} · ${fmt(run.starts_at)}`} href="/runs" saved={savedKey('run',run.id)} busy={busy===`save-run-${run.id}`} onSave={()=>toggleSave('run',run.id)}/>)}</div></article></section>
 <section className="mt-6 grid gap-6 lg:grid-cols-2"><article className="rounded-3xl border border-white/10 bg-white/[.02] p-6"><SectionTitle icon={<FaCalendarDays/>} eyebrow="Flagship league" title="Upcoming RCL"/><div className="mt-5 space-y-3">{games.length?games.slice(0,6).map(game=><OpportunityRow key={game.id} title={`${game.away?.name??'Away'} vs ${game.home?.name??'Home'}`} meta={`${game.status} · ${fmt(game.scheduled_at)}`} href={`/games/${game.id}`} saved={savedKey('game',game.id)} busy={busy===`save-game-${game.id}`} onSave={()=>toggleSave('game',game.id)}/>):<Empty text="No upcoming official RCL games are currently scheduled."/>}</div></article><article className="rounded-3xl border border-rcl-orange/20 bg-rcl-orange/[.025] p-6"><SectionTitle icon={<FaChartLine/>} eyebrow="Basketball identity" title="Passport Studio"/><p className="mt-4 text-sm leading-6 text-white/45">Your public Basketball Passport remains part of RCL. RCL+ adds the private utility around it: exposure analytics, career organization and share-ready identity tools.</p>{playerId?<Link href={`/players/${playerId}/passport`} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl border border-rcl-orange/30 px-4 text-xs font-black uppercase text-rcl-orange">Open my Passport <FaArrowRight/></Link>:<p className="mt-5 rounded-xl border border-dashed border-white/10 p-4 text-xs text-white/35">Link a player identity to activate Passport Studio.</p>}</article></section>
 {allAccess&&<section className="mt-6 rounded-3xl border border-amber-300/25 bg-[radial-gradient(circle_at_top_right,rgba(251,191,36,.12),transparent_35%),#0b0b08] p-6 sm:p-8"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.2em] text-amber-300"><FaCrown className="mr-2 inline"/>All Access</p><h2 className="mt-2 font-display text-3xl font-black uppercase">Monthly RCL Spotlight</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/50">Request one monthly profile Spotlight for discovery. RCL reviews placement; Spotlight never changes REP, player ratings, rankings, awards or competitive results.</p>{spotlight&&<p className="mt-4 text-xs font-black uppercase text-amber-200">Latest request: {spotlight.status} · {new Date(spotlight.created_at).toLocaleDateString()}</p>}</div><button onClick={requestSpotlight} disabled={Boolean(busy)||Boolean(spotlight&&spotlight.requested_month===new Date().toISOString().slice(0,7)+'-01')} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-amber-300 px-5 text-xs font-black uppercase text-black disabled:opacity-40"><FaStar/>{busy==='spotlight'?'Submitting…':'Request this month'}</button></div></section>}
 </>}</>}</Container></main>;
}

function PreferenceGroup({title,values,selected,onToggle}:{title:string;values:Array<{value:string;label:string}>;selected:string[];onToggle:(value:string)=>void}){return <div><p className="text-[10px] font-black uppercase tracking-wider text-white/35">{title}</p><div className="mt-3 flex flex-wrap gap-2">{values.map(item=><button type="button" key={item.value} onClick={()=>onToggle(item.value)} className={`rounded-full border px-3 py-2 text-[10px] font-black uppercase ${selected.includes(item.value)?'border-rcl-orange/50 bg-rcl-orange/10 text-rcl-orange':'border-white/10 text-white/40'}`}>{selected.includes(item.value)&&<FaCircleCheck className="mr-1 inline"/>}{item.label}</button>)}</div></div>}
function SectionTitle({icon,eyebrow,title}:{icon:React.ReactNode;eyebrow:string;title:string}){return <div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-orange">{icon}<span className="ml-2">{eyebrow}</span></p><h2 className="mt-2 font-display text-2xl font-black uppercase">{title}</h2></div>}
function OpportunityRow({title,meta,href,saved,busy,onSave}:{title:string;meta:string;href:string;saved:boolean;busy:boolean;onSave:()=>void}){return <div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-black/20 p-4"><Link href={href} className="min-w-0 flex-1"><b className="block truncate text-sm">{title}</b><p className="mt-1 truncate text-xs text-white/35">{meta}</p></Link><button type="button" onClick={onSave} disabled={busy} aria-label={saved?'Remove save':'Save'} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/10 text-rcl-orange disabled:opacity-40">{saved?<FaBookmark/>:<FaRegBookmark/>}</button></div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-white/10 p-5 text-sm leading-6 text-white/35">{text}</div>}
