'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { FaAward, FaBasketball, FaCrown, FaMedal, FaTrophy } from 'react-icons/fa6';
import { Container } from '@/components/Container';
import { ClientPageHero } from '@/components/ClientPageHero';
import { getSupabaseClient } from '@/lib/supabase';

type Hall={id:string;player_id:string|null;profile_id:string|null;team_id:string|null;class_year:number;category:string;title:string;citation:string;image_url:string|null;inducted_at:string};
type Season={id:string;name:string;status:string;start_date:string;end_date:string|null};
type Snapshot={season_id:string;profile_id:string;total_xp:number;level:number;hooper_xp:number;community_xp:number;creator_xp:number;coach_xp:number;reliability_xp:number;final_rank:number|null};
type Profile={id:string;display_name:string|null;username:string|null;avatar_url:string|null};
type Award={id:string;title:string;award_type:string;description:string|null;awarded_at:string|null;player_id:string|null};

export default function LegacyPage(){
 const supabase=useMemo(()=>getSupabaseClient(true),[]);const db=supabase as any;const [hall,setHall]=useState<Hall[]>([]);const [seasons,setSeasons]=useState<Season[]>([]);const [snapshots,setSnapshots]=useState<Snapshot[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);const [awards,setAwards]=useState<Award[]>([]);const [seasonId,setSeasonId]=useState('');const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!db){setLoading(false);return;}void(async()=>{const [hallResult,seasonResult,snapshotResult,awardResult]=await Promise.all([db.from('hall_of_fame_inductions').select('*').order('class_year',{ascending:false}),db.from('seasons').select('id,name,status,start_date,end_date').order('start_date',{ascending:false}),db.from('season_reputation_snapshots').select('*').order('final_rank',{ascending:true}),db.from('awards').select('id,title,award_type,description,awarded_at,player_id').order('awarded_at',{ascending:false}).limit(24)]);const halls=(hallResult.data??[]) as Hall[];const ss=(seasonResult.data??[]) as Season[];const snaps=(snapshotResult.data??[]) as Snapshot[];setHall(halls);setSeasons(ss);setSnapshots(snaps);setAwards((awardResult.data??[]) as Award[]);setSeasonId(current=>current||snaps[0]?.season_id||ss.find(s=>s.status==='completed')?.id||ss[0]?.id||'');const ids=[...new Set([...halls.map(x=>x.profile_id),...snaps.map(x=>x.profile_id)].filter(Boolean))] as string[];if(ids.length){const {data}=await db.from('profiles').select('id,display_name,username,avatar_url').in('id',ids);setProfiles((data??[]) as Profile[]);}setLoading(false);})();},[db]);
 const profileMap=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);const seasonMap=useMemo(()=>new Map(seasons.map(s=>[s.id,s])),[seasons]);const leaderboard=snapshots.filter(x=>x.season_id===seasonId).sort((a,b)=>(a.final_rank??999)-(b.final_rank??999));
 return <main className="min-h-screen bg-[#03070d] pb-28 text-white"><ClientPageHero eyebrow="Est. 2011 · Richmond" title="RCL Legacy" accent="History that stays" description="A permanent home for Rich City League seasons, Hall of Fame classes, awards, archived REP and the people who built the basketball culture." assetKey="about.cover" meta={<div className="min-w-48 rounded-2xl border border-rcl-orange/20 bg-[#071522]/85 p-5"><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-orange">Archive</p><p className="mt-2 font-display text-4xl font-black">2011→</p><p className="mt-1 text-xs text-white/35">Every season adds another chapter</p></div>}/><Container maxWidth="xl" className="py-9 sm:py-12"><section className="grid gap-4 sm:grid-cols-3"><ArchiveStat icon={<FaBasketball/>} value={seasons.length} label="Season records"/><ArchiveStat icon={<FaCrown/>} value={hall.length} label="Hall of Fame entries"/><ArchiveStat icon={<FaAward/>} value={awards.length} label="Recent archived awards"/></section>
 <section className="mt-7 rounded-3xl border border-rcl-orange/20 bg-[radial-gradient(circle_at_top_right,rgba(249,115,22,.10),transparent_35%),#071018] p-6 sm:p-8"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-rcl-orange/10 text-rcl-orange"><FaCrown/></span><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-rcl-orange">Hall of Fame</p><h2 className="font-display text-3xl font-black uppercase">Built to remember the people</h2></div></div>{loading?<div className="mt-6 h-48 animate-pulse rounded-2xl bg-white/[.03]"/>:hall.length?<div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{hall.map(entry=>{const p=entry.profile_id?profileMap.get(entry.profile_id):null;return <article key={entry.id} className="rounded-2xl border border-white/10 bg-black/25 p-5"><div className="flex items-start gap-4">{entry.image_url||p?.avatar_url?<div className="relative h-16 w-16 shrink-0 overflow-hidden rounded-xl bg-black/30"><Image src={entry.image_url??p!.avatar_url!} alt="" fill sizes="64px" className="object-cover"/></div>:<span className="grid h-16 w-16 shrink-0 place-items-center rounded-xl bg-rcl-orange/10 text-2xl text-rcl-orange"><FaTrophy/></span>}<div><p className="text-[9px] font-black uppercase tracking-wider text-rcl-orange">Class of {entry.class_year} · {entry.category}</p><h3 className="mt-1 font-display text-xl font-black uppercase">{entry.title}</h3>{p&&<p className="mt-1 text-xs text-rcl-blue">{p.display_name??p.username}</p>}</div></div><p className="mt-4 text-sm leading-6 text-white/45">{entry.citation}</p></article>})}</div>:<div className="mt-6 rounded-2xl border border-dashed border-white/10 p-8 text-center"><FaTrophy className="mx-auto text-3xl text-rcl-orange"/><h3 className="mt-3 font-display text-xl font-black uppercase">The archive is ready for its first digital class</h3><p className="mx-auto mt-2 max-w-2xl text-sm leading-6 text-white/40">Historical players, coaches, teams and contributors can now be inducted without losing their context as future seasons are added.</p></div>}</section>
 <section className="mt-7 grid gap-6 lg:grid-cols-[1fr_.7fr]"><article className="overflow-hidden rounded-3xl border border-rcl-blue/15 bg-[#071522]/40"><div className="flex flex-wrap items-end justify-between gap-4 border-b border-white/10 p-6"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-blue"><FaMedal className="mr-1 inline"/>Season REP archive</p><h2 className="mt-1 font-display text-2xl font-black uppercase">Archived reputation</h2></div><select value={seasonId} onChange={e=>setSeasonId(e.target.value)} className="h-11 rounded-xl border border-white/10 bg-[#071018] px-3 text-xs font-black text-white outline-none"><option value="">Choose season</option>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>{leaderboard.length?<div className="divide-y divide-white/[.06]">{leaderboard.slice(0,25).map(item=>{const p=profileMap.get(item.profile_id);return <div key={item.profile_id} className="grid grid-cols-[auto_1fr_auto] items-center gap-4 p-4 sm:px-6"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/[.04] font-display font-black text-rcl-orange">#{item.final_rank??'—'}</span><div><p className="text-sm font-black">{p?.display_name??(p?.username?`@${p.username}`:'RCL Member')}</p><p className="mt-1 text-[10px] text-white/30">H {item.hooper_xp} · C {item.community_xp} · CR {item.creator_xp} · CO {item.coach_xp} · R {item.reliability_xp}</p></div><b className="font-display text-xl">{item.total_xp}</b></div>})}</div>:<div className="p-8 text-sm leading-6 text-white/35">Season REP snapshots are frozen automatically when a season is marked completed. {seasonMap.get(seasonId)?.status!=='completed'?'The selected season is still active or has no REP snapshot yet.':''}</div>}</article><article className="rounded-3xl border border-white/10 bg-white/[.02] p-6"><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-orange"><FaAward className="mr-1 inline"/>Awards archive</p><h2 className="mt-1 font-display text-2xl font-black uppercase">Recent honors</h2>{awards.length?<div className="mt-5 space-y-3">{awards.slice(0,10).map(a=><div key={a.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-[9px] font-black uppercase tracking-wider text-rcl-orange">{a.award_type.replace(/_/g,' ')}</p><p className="mt-1 font-black">{a.title}</p>{a.description&&<p className="mt-1 text-xs leading-5 text-white/35">{a.description}</p>}</div>)}</div>:<p className="mt-5 text-sm text-white/35">League awards will populate this permanent archive as they are recorded.</p>}<Link href="/badges" className="mt-5 inline-flex text-xs font-black uppercase tracking-wider text-rcl-blue">View badges & achievements</Link></article></section>
 </Container></main>;
}
function ArchiveStat({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <article className="rounded-2xl border border-white/10 bg-white/[.02] p-5"><span className="text-rcl-orange">{icon}</span><p className="mt-3 font-display text-4xl font-black">{value}</p><p className="mt-1 text-[10px] font-black uppercase tracking-wider text-white/35">{label}</p></article>;}
