'use client';

import Image from 'next/image';
import Link from 'next/link';
import type { ReactNode } from 'react';
import { useEffect, useMemo, useState } from 'react';
import { FaAward, FaBasketball, FaCrown, FaMedal, FaTrophy } from 'react-icons/fa6';
import { Container } from '@/components/Container';
import { ClientPageHero } from '@/components/ClientPageHero';
import { getSupabaseClient } from '@/lib/supabase';

type Hall={id:string;profile_id:string|null;class_year:number;category:string;title:string;citation:string;image_url:string|null};
type Season={id:string;name:string;status:string;start_date:string;end_date:string|null};
type Snapshot={season_id:string;profile_id:string;total_xp:number;level:number;hooper_xp:number;community_xp:number;creator_xp:number;coach_xp:number;reliability_xp:number;final_rank:number|null};
type Profile={id:string;display_name:string|null;username:string|null;avatar_url:string|null};
type Award={id:string;name:string;description:string|null;awarded_at:string|null;player_id:string|null;team_id:string|null;season_id:string|null};

export default function LegacyPage(){
 const supabase=useMemo(()=>getSupabaseClient(true),[]);const db=supabase as any;
 const [hall,setHall]=useState<Hall[]>([]);const [seasons,setSeasons]=useState<Season[]>([]);const [snapshots,setSnapshots]=useState<Snapshot[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);const [awards,setAwards]=useState<Award[]>([]);const [seasonId,setSeasonId]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{if(!db){setLoading(false);return;}void(async()=>{setLoading(true);const [h,s,r,a]=await Promise.all([db.from('hall_of_fame_inductions').select('id,profile_id,class_year,category,title,citation,image_url').order('class_year',{ascending:false}),db.from('seasons').select('id,name,status,start_date,end_date').order('start_date',{ascending:false}),db.from('season_reputation_snapshots').select('*').order('final_rank',{ascending:true}),db.from('awards').select('id,name,description,awarded_at,player_id,team_id,season_id').order('awarded_at',{ascending:false}).limit(30)]);if(h.error||s.error||r.error||a.error)setError(h.error?.message||s.error?.message||r.error?.message||a.error?.message||'Legacy archive could not be loaded.');const halls=(h.data??[]) as Hall[];const ss=(s.data??[]) as Season[];const snaps=(r.data??[]) as Snapshot[];setHall(halls);setSeasons(ss);setSnapshots(snaps);setAwards((a.data??[]) as Award[]);setSeasonId(current=>current||snaps[0]?.season_id||ss.find(x=>x.status==='completed')?.id||ss[0]?.id||'');const ids=[...new Set([...halls.map(x=>x.profile_id),...snaps.map(x=>x.profile_id)].filter(Boolean))] as string[];if(ids.length){const {data}=await db.from('profiles').select('id,display_name,username,avatar_url').in('id',ids);setProfiles((data??[]) as Profile[]);}setLoading(false);})();},[db]);
 const profileMap=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);const leaderboard=snapshots.filter(x=>x.season_id===seasonId).sort((a,b)=>(a.final_rank??999)-(b.final_rank??999));
 return <main className="min-h-screen bg-[#03070d] pb-28 text-white"><ClientPageHero eyebrow="Est. 2011 · Richmond" title="RCL Legacy" accent="History that stays" description="A permanent home for Rich City League seasons, Hall of Fame classes, awards and archived REP." assetKey="about.cover" meta={<div className="min-w-48 rounded-2xl border border-rcl-orange/20 bg-[#071522]/85 p-5"><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-orange">Archive</p><p className="mt-2 font-display text-4xl font-black">2011→</p><p className="mt-1 text-xs text-white/35">Every season adds another chapter</p></div>}/><Container maxWidth="xl" className="py-9 sm:py-12">{error&&<p className="mb-5 rounded-2xl border border-red-400/20 bg-red-400/[.06] p-4 text-sm text-red-100">{error}</p>}<section className="grid gap-4 sm:grid-cols-3"><ArchiveStat icon={<FaBasketball/>} value={seasons.length} label="Season records"/><ArchiveStat icon={<FaCrown/>} value={hall.length} label="Hall of Fame entries"/><ArchiveStat icon={<FaAward/>} value={awards.length} label="Recent awards"/></section>
 <section className="mt-7 rounded-3xl border border-rcl-orange/20 bg-[radial-gradient(circle_at_top_right,rgba(249,115,22,.10),transparent_35%),#071018] p-6 sm:p-8"><Header icon={<FaCrown/>} eyebrow="Hall of Fame" title="Built to remember the people"/>{loading?<div className="mt-6 h-40 animate-pulse rounded-2xl bg-white/[.03]"/>:hall.length?<div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{hall.map(entry=>{const p=entry.profile_id?profileMap.get(entry.profile_id):null;return <article key={entry.id} className="rounded-2xl border border-white/10 bg-black/25 p-5"><div className="flex gap-4">{entry.image_url||p?.avatar_url?<div className="relative h-16 w-16 shrink-0 overflow-hidden rounded-xl"><Image src={entry.image_url??p!.avatar_url!} alt="" fill sizes="64px" className="object-cover"/></div>:<span className="grid h-16 w-16 shrink-0 place-items-center rounded-xl bg-rcl-orange/10 text-rcl-orange"><FaTrophy/></span>}<div><p className="text-[9px] font-black uppercase tracking-wider text-rcl-orange">Class of {entry.class_year} · {entry.category}</p><h3 className="mt-1 font-display text-xl font-black uppercase">{entry.title}</h3>{p&&<p className="mt-1 text-xs text-rcl-blue">{p.display_name??p.username}</p>}</div></div><p className="mt-4 text-sm leading-6 text-white/45">{entry.citation}</p></article>})}</div>:<p className="mt-6 rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-white/40">The digital Hall of Fame is ready for its first class.</p>}</section>
 <section className="mt-7 grid gap-6 lg:grid-cols-[1fr_.72fr]"><article className="overflow-hidden rounded-3xl border border-rcl-blue/15 bg-[#071522]/40"><div className="flex flex-wrap items-end justify-between gap-4 border-b border-white/10 p-6"><Header icon={<FaMedal/>} eyebrow="Season REP archive" title="Archived reputation"/><select value={seasonId} onChange={e=>setSeasonId(e.target.value)} className="h-11 rounded-xl border border-white/10 bg-[#071018] px-3 text-xs font-black text-white"><option value="">Choose season</option>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>{leaderboard.length?<div className="divide-y divide-white/[.06]">{leaderboard.slice(0,25).map(item=>{const p=profileMap.get(item.profile_id);return <div key={item.profile_id} className="grid grid-cols-[auto_1fr_auto] items-center gap-4 p-4 sm:px-6"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/[.04] font-display font-black text-rcl-orange">#{item.final_rank??'—'}</span><div><p className="text-sm font-black">{p?.display_name??(p?.username?`@${p.username}`:'RCL Member')}</p><p className="mt-1 text-[10px] text-white/30">Hooper {item.hooper_xp} · Community {item.community_xp} · Creator {item.creator_xp} · Coach {item.coach_xp} · Reliability {item.reliability_xp}</p></div><b className="font-display text-xl">{item.total_xp}</b></div>})}</div>:<p className="p-8 text-sm leading-6 text-white/35">Season REP standings freeze automatically when an RCL season is marked completed.</p>}</article><article className="rounded-3xl border border-white/10 bg-white/[.02] p-6"><Header icon={<FaAward/>} eyebrow="Awards archive" title="Recent honors"/>{awards.length?<div className="mt-5 space-y-3">{awards.slice(0,12).map(a=><div key={a.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="font-black">{a.name}</p>{a.description&&<p className="mt-1 text-xs leading-5 text-white/35">{a.description}</p>}<p className="mt-2 text-[9px] font-black uppercase text-rcl-orange">{a.awarded_at?new Date(a.awarded_at).toLocaleDateString():'RCL honor'}</p></div>)}</div>:<p className="mt-5 text-sm text-white/35">League awards will populate the permanent archive as they are recorded.</p>}<Link href="/badges" className="mt-5 inline-flex text-xs font-black uppercase tracking-wider text-rcl-blue">View badges & achievements</Link></article></section></Container></main>;
}
function ArchiveStat({icon,value,label}:{icon:ReactNode;value:number;label:string}){return <article className="rounded-2xl border border-white/10 bg-white/[.02] p-5"><span className="text-rcl-orange">{icon}</span><p className="mt-3 font-display text-4xl font-black">{value}</p><p className="mt-1 text-[10px] font-black uppercase tracking-wider text-white/35">{label}</p></article>}
function Header({icon,eyebrow,title}:{icon:ReactNode;eyebrow:string;title:string}){return <div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-rcl-orange/10 text-rcl-orange">{icon}</span><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-orange">{eyebrow}</p><h2 className="font-display text-2xl font-black uppercase">{title}</h2></div></div>}
