'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { FaArrowRight, FaCrown, FaFilm, FaNewspaper, FaShieldHalved } from 'react-icons/fa6';
import { Container } from '@/components/Container';
import { ClientPageHero } from '@/components/ClientPageHero';
import { useAuth } from '@/hooks/useAuth';
import { getSupabaseClient } from '@/lib/supabase';

type Highlight={id:string;player_id:string;game_id:string|null;title:string;category:string;clip_url:string|null;status:string;created_at:string;player?:{first_name:string|null;last_name:string|null}|null};
type Story={id:string;game_id:string;headline:string;summary:string;story_body:string|null;status:string;created_at:string;updated_at:string};
type Player={id:string;profile_id:string|null;first_name:string;last_name:string};

export default function BasketballOSAdminPage(){
 const {user}=useAuth();const supabase=useMemo(()=>getSupabaseClient(true),[]);const db=supabase as any;const [highlights,setHighlights]=useState<Highlight[]>([]);const [stories,setStories]=useState<Story[]>([]);const [players,setPlayers]=useState<Player[]>([]);const [storyDrafts,setStoryDrafts]=useState<Record<string,{headline:string;summary:string;story_body:string}>>({});const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [hof,setHof]=useState({playerId:'',classYear:String(new Date().getFullYear()),category:'player',title:'',citation:''});
 const load=useCallback(async()=>{if(!db||!user)return;setError('');const [highlightResult,storyResult,playerResult]=await Promise.all([db.from('player_highlights').select('id,player_id,game_id,title,category,clip_url,status,created_at,player:players(first_name,last_name)').in('status',['pending','draft']).order('created_at',{ascending:true}),db.from('game_story_drafts').select('*').in('status',['draft','approved']).order('created_at',{ascending:false}).limit(40),db.from('players').select('id,profile_id,first_name,last_name').order('last_name').limit(500)]);if(highlightResult.error||storyResult.error){setError(highlightResult.error?.message||storyResult.error?.message||'Staff access is required.');return;}const s=(storyResult.data??[]) as Story[];setHighlights((highlightResult.data??[]) as Highlight[]);setStories(s);setPlayers((playerResult.data??[]) as Player[]);setStoryDrafts(Object.fromEntries(s.map(x=>[x.id,{headline:x.headline,summary:x.summary,story_body:x.story_body??''}])));},[db,user]);useEffect(()=>{void load();},[load]);
 const moderate=async(id:string,status:'published'|'rejected')=>{if(!db)return;setBusy(`highlight-${id}`);setError('');const {error:e}=await db.from('player_highlights').update({status}).eq('id',id);if(e)setError(e.message);else setNotice(status==='published'?'Highlight published to RCH TV and the player Passport.':'Highlight rejected.');setBusy('');await load();};
 const saveStory=async(story:Story,publish=false)=>{if(!db||!user)return;const draft=storyDrafts[story.id];if(!draft)return;setBusy(`story-${story.id}`);setError('');const now=new Date().toISOString();const payload={headline:draft.headline.trim(),summary:draft.summary.trim(),story_body:draft.story_body.trim()||null,status:publish?'published':'draft',updated_at:now,...(publish?{approved_by:user.id,approved_at:now,published_at:now}: {})};const {error:e}=await db.from('game_story_drafts').update(payload).eq('id',story.id);if(e)setError(e.message);else setNotice(publish?'Postgame story published.':'Story draft saved.');setBusy('');await load();};
 const induct=async(e:React.FormEvent)=>{e.preventDefault();if(!db||!hof.title.trim()||!hof.citation.trim())return;const player=players.find(p=>p.id===hof.playerId);setBusy('hof');setError('');const {error:insertError}=await db.from('hall_of_fame_inductions').insert({player_id:player?.id??null,profile_id:player?.profile_id??null,class_year:Number(hof.classYear),category:hof.category,title:hof.title.trim(),citation:hof.citation.trim(),inducted_at:new Date().toISOString().slice(0,10)});if(insertError)setError(insertError.message);else{setNotice('Hall of Fame entry published to the Legacy archive.');setHof({playerId:'',classYear:String(new Date().getFullYear()),category:'player',title:'',citation:''});}setBusy('');};
 return <main className="min-h-screen bg-[#03070d] pb-28 text-white"><ClientPageHero eyebrow="RCL Staff" title="Basketball OS Control Room" accent="Review. Publish. Preserve." description="One staff workspace for Highlight Engine moderation, automatic postgame story drafts and the RCL Legacy archive." assetKey="admin.cover" actions={<Link href="/admin" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/15 px-4 text-xs font-black uppercase tracking-wider"><FaShieldHalved/>Admin</Link>} meta={<div className="rounded-2xl border border-rcl-orange/20 bg-[#071522]/85 p-5"><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-orange">Review queue</p><p className="mt-2 font-display text-4xl font-black">{highlights.length+stories.length}</p><p className="text-xs text-white/35">items need staff judgment</p></div>}/><Container maxWidth="xl" className="py-9 sm:py-12">{notice&&<p className="mb-5 rounded-2xl border border-emerald-400/20 bg-emerald-400/[.06] p-4 text-sm text-emerald-100">{notice}</p>}{error&&<p className="mb-5 rounded-2xl border border-red-400/20 bg-red-400/[.06] p-4 text-sm text-red-100">{error}</p>}<section className="grid gap-6 xl:grid-cols-2"><article className="rounded-3xl border border-rcl-blue/15 bg-[#071522]/40 p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-rcl-blue/10 text-rcl-blue"><FaFilm/></span><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-blue">Highlight Engine</p><h2 className="font-display text-2xl font-black uppercase">Pending clips</h2></div></div><div className="mt-5 space-y-3">{highlights.length?highlights.map(h=><div key={h.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-wider text-rcl-orange">{h.category.replace(/_/g,' ')}</p><p className="mt-1 font-black">{h.title}</p><p className="mt-1 text-xs text-white/35">{h.player?`${h.player.first_name??''} ${h.player.last_name??''}`.trim():'RCL Player'}</p></div>{h.clip_url&&<a href={h.clip_url} target="_blank" rel="noreferrer" className="text-xs font-black uppercase text-rcl-blue">Open <FaArrowRight className="inline"/></a>}</div><div className="mt-4 flex gap-2"><button type="button" disabled={busy===`highlight-${h.id}`} onClick={()=>void moderate(h.id,'published')} className="rounded-xl bg-rcl-orange px-4 py-2.5 text-[10px] font-black uppercase text-black disabled:opacity-50">Approve</button><button type="button" disabled={busy===`highlight-${h.id}`} onClick={()=>void moderate(h.id,'rejected')} className="rounded-xl border border-white/15 px-4 py-2.5 text-[10px] font-black uppercase text-white/60 disabled:opacity-50">Reject</button></div></div>):<p className="rounded-2xl border border-dashed border-white/10 p-6 text-sm text-white/35">No pending highlight submissions.</p>}</div></article>
 <article className="rounded-3xl border border-rcl-orange/15 bg-rcl-orange/[.025] p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-rcl-orange/10 text-rcl-orange"><FaNewspaper/></span><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-orange">Automatic game stories</p><h2 className="font-display text-2xl font-black uppercase">Postgame drafts</h2></div></div><div className="mt-5 space-y-4">{stories.length?stories.map(s=>{const draft=storyDrafts[s.id]??{headline:s.headline,summary:s.summary,story_body:s.story_body??''};return <div key={s.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><Link href={`/games/${s.game_id}`} className="text-[9px] font-black uppercase tracking-wider text-rcl-blue">Open game <FaArrowRight className="inline"/></Link><input value={draft.headline} onChange={e=>setStoryDrafts(current=>({...current,[s.id]:{...draft,headline:e.target.value}}))} className="mt-3 h-11 w-full rounded-xl border border-white/10 bg-[#071018] px-3 text-sm font-black outline-none focus:border-rcl-blue/40"/><textarea value={draft.summary} onChange={e=>setStoryDrafts(current=>({...current,[s.id]:{...draft,summary:e.target.value}}))} rows={3} className="mt-3 w-full rounded-xl border border-white/10 bg-[#071018] p-3 text-xs leading-5 outline-none focus:border-rcl-blue/40"/><textarea value={draft.story_body} onChange={e=>setStoryDrafts(current=>({...current,[s.id]:{...draft,story_body:e.target.value}}))} rows={5} className="mt-3 w-full rounded-xl border border-white/10 bg-[#071018] p-3 text-xs leading-5 outline-none focus:border-rcl-blue/40"/><div className="mt-3 flex gap-2"><button type="button" disabled={busy===`story-${s.id}`} onClick={()=>void saveStory(s,false)} className="rounded-xl border border-white/15 px-4 py-2.5 text-[10px] font-black uppercase">Save</button><button type="button" disabled={busy===`story-${s.id}`} onClick={()=>void saveStory(s,true)} className="rounded-xl bg-rcl-orange px-4 py-2.5 text-[10px] font-black uppercase text-black">Publish story</button></div></div>}):<p className="rounded-2xl border border-dashed border-white/10 p-6 text-sm text-white/35">No postgame drafts waiting for review.</p>}</div></article></section>
 <section className="mt-6 rounded-3xl border border-white/10 bg-white/[.02] p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-rcl-orange/10 text-rcl-orange"><FaCrown/></span><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-orange">Legacy archive</p><h2 className="font-display text-2xl font-black uppercase">Hall of Fame induction</h2></div></div><form onSubmit={induct} className="mt-5 grid gap-4 lg:grid-cols-2"><label className="text-[10px] font-black uppercase tracking-wider text-white/35">Player (optional)<select value={hof.playerId} onChange={e=>setHof(x=>({...x,playerId:e.target.value}))} className="field"><option value="">Contributor / team / no player</option>{players.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-[10px] font-black uppercase tracking-wider text-white/35">Class year<input inputMode="numeric" value={hof.classYear} onChange={e=>setHof(x=>({...x,classYear:e.target.value}))} className="field"/></label><label className="text-[10px] font-black uppercase tracking-wider text-white/35">Category<select value={hof.category} onChange={e=>setHof(x=>({...x,category:e.target.value}))} className="field"><option value="player">Player</option><option value="coach">Coach</option><option value="team">Team</option><option value="contributor">Contributor</option></select></label></div><label className="text-[10px] font-black uppercase tracking-wider text-white/35 lg:col-span-2">Induction title<input value={hof.title} onChange={e=>setHof(x=>({...x,title:e.target.value}))} className="field" placeholder="Example: Class of 2027 — Player"/></label><label className="text-[10px] font-black uppercase tracking-wider text-white/35 lg:col-span-2">Citation<textarea rows={4} value={hof.citation} onChange={e=>setHof(x=>({...x,citation:e.target.value}))} className="field h-auto py-3" placeholder="Why this person or team belongs in RCL history…"/></label><button type="submit" disabled={busy==='hof'} className="min-h-12 rounded-xl bg-rcl-orange px-5 text-xs font-black uppercase text-black disabled:opacity-50">{busy==='hof'?'Publishing…':'Publish induction'}</button><Link href="/legacy" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/15 px-5 text-xs font-black uppercase">Open Legacy archive</Link></form></section></Container><style jsx>{`.field{margin-top:.5rem;height:3rem;width:100%;border-radius:.75rem;border:1px solid rgba(255,255,255,.1);background:#071018;padding:0 .875rem;color:#fff;outline:none}.field:focus{border-color:rgba(26,155,220,.5)}`}</style></main>;
}
