'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Container } from '@/components/Container';
import { useAuth } from '@/hooks/useAuth';
import { getSupabaseClient } from '@/lib/supabase';
import { FaArrowLeft, FaCircleCheck, FaEye, FaNewspaper, FaXmark } from 'react-icons/fa6';

type Submission={id:string;organization_id:string;submitted_by:string;submission_type:string;title:string;summary:string;source_url:string|null;media_url:string|null;status:string;review_notes:string|null;created_at:string;organization:{name:string;slug:string}|null};
const statuses=['submitted','reviewing','accepted','declined','published'] as const;

export default function NetworkEditorialAdminPage(){
 const {user,profile,loading:authLoading}=useAuth(); const supabase=useMemo(()=>getSupabaseClient(),[]); const db=supabase as any; const authorized=Boolean(user&&profile?.role==='admin');
 const [items,setItems]=useState<Submission[]>([]); const [filter,setFilter]=useState('open'); const [busy,setBusy]=useState(''); const [notes,setNotes]=useState<Record<string,string>>({}); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{if(!authorized)return;setLoading(true);const {data,error}=await db.from('network_editorial_submissions').select('id,organization_id,submitted_by,submission_type,title,summary,source_url,media_url,status,review_notes,created_at,organization:network_organizations!organization_id(name,slug)').order('created_at',{ascending:false}).limit(200);if(error)setMessage(error.message);else setItems((data??[]).map((row:any)=>({...row,organization:Array.isArray(row.organization)?row.organization[0]:row.organization})));setLoading(false);},[authorized,db]);
 useEffect(()=>{if(!authLoading&&authorized)void load();else if(!authLoading)setLoading(false);},[authLoading,authorized,load]);
 async function setStatus(id:string,status:'reviewing'|'accepted'|'declined'|'published'){setBusy(id);setMessage('');const {error}=await db.rpc('set_network_editorial_status',{p_submission_id:id,p_status:status,p_review_notes:notes[id]?.trim()||null});setBusy('');if(error){setMessage(error.message);return;}setMessage(`Submission marked ${status}. Operator notification sent.`);await load();}
 const visible=items.filter(item=>filter==='all'||filter==='open'?filter==='all'||['submitted','reviewing','accepted'].includes(item.status):item.status===filter);
 const counts=Object.fromEntries(statuses.map(status=>[status,items.filter(item=>item.status===status).length]));
 if(authLoading||loading)return <main className="min-h-screen bg-[#03070d] text-white"><Container maxWidth="xl" className="py-16"><p className="text-white/45">Loading editorial queue…</p></Container></main>;
 if(!authorized)return <main className="min-h-screen bg-[#03070d] text-white"><Container maxWidth="lg" className="py-16"><h1 className="font-display text-4xl font-black uppercase">Admin access required.</h1></Container></main>;
 return <main className="min-h-screen bg-[#03070d] pb-24 text-white"><section className="border-b border-rcl-blue/15 bg-[radial-gradient(circle_at_80%_10%,rgba(44,166,255,.14),transparent_28%),linear-gradient(145deg,#071522,#03070d)]"><Container maxWidth="xl" className="py-10 sm:py-14"><Link href="/admin/network" className="inline-flex items-center gap-2 text-xs font-black uppercase text-white/40"><FaArrowLeft/> Network operations</Link><p className="mt-6 text-[10px] font-black uppercase tracking-[.2em] text-rcl-orange">RCL Media Operations</p><h1 className="mt-2 font-display text-5xl font-black uppercase">Editorial <span className="text-rcl-blue">Queue.</span></h1><p className="mt-4 max-w-3xl text-sm leading-6 text-white/45">Review what organizations say matters across Virginia basketball. Editorial decisions stay separate from paid RCL Reach distribution.</p></Container></section><Container maxWidth="xl" className="py-8">{message&&<p className="mb-5 rounded-xl border border-amber-300/20 bg-amber-300/[.06] p-4 text-sm text-amber-100">{message}</p>}
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{statuses.map(status=><button key={status} onClick={()=>setFilter(status)} className={`rounded-2xl border p-4 text-left ${filter===status?'border-rcl-blue/40 bg-rcl-blue/[.08]':'border-white/10 bg-white/[.025]'}`}><p className="text-[10px] font-black uppercase tracking-[.12em] text-white/35">{status}</p><p className="mt-2 text-3xl font-black">{counts[status]??0}</p></button>)}</section><div className="mt-4 flex gap-2"><button onClick={()=>setFilter('open')} className={`rounded-lg border px-3 py-2 text-[10px] font-black uppercase ${filter==='open'?'border-rcl-orange/40 text-rcl-orange':'border-white/10 text-white/40'}`}>Open queue</button><button onClick={()=>setFilter('all')} className={`rounded-lg border px-3 py-2 text-[10px] font-black uppercase ${filter==='all'?'border-rcl-orange/40 text-rcl-orange':'border-white/10 text-white/40'}`}>All</button></div>
 <section className="mt-6 space-y-4">{visible.length?visible.map(item=><article key={item.id} className="rounded-3xl border border-white/10 bg-white/[.025] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-rcl-orange">{item.submission_type.replaceAll('-',' ')} · {item.organization?.name??'Organization'}</p><h2 className="mt-2 font-display text-2xl font-black uppercase">{item.title}</h2><p className="mt-2 text-xs text-white/30">Submitted {new Date(item.created_at).toLocaleString()} · <span className="font-black uppercase">{item.status}</span></p></div><FaNewspaper className="text-rcl-blue"/></div><p className="mt-4 max-w-4xl whitespace-pre-wrap text-sm leading-6 text-white/55">{item.summary}</p><div className="mt-4 flex flex-wrap gap-3 text-xs">{item.source_url&&<a href={item.source_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-rcl-blue"><FaEye/> Source</a>}{item.media_url&&<a href={item.media_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-rcl-blue"><FaEye/> Media</a>}{item.organization&&<Link href={`/organizations/${item.organization.slug}`} className="text-white/45">Organization page</Link>}</div><textarea value={notes[item.id]??item.review_notes??''} onChange={e=>setNotes({...notes,[item.id]:e.target.value})} placeholder="Internal/review note shared with submitter when status changes…" className="mt-5 min-h-24 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-white outline-none focus:border-rcl-blue/45" maxLength={2000}/><div className="mt-4 flex flex-wrap gap-2"><Action disabled={busy===item.id} onClick={()=>void setStatus(item.id,'reviewing')} label="Reviewing"/><Action disabled={busy===item.id} onClick={()=>void setStatus(item.id,'accepted')} label="Accept" icon={<FaCircleCheck/>}/><Action disabled={busy===item.id} onClick={()=>void setStatus(item.id,'published')} label="Published" icon={<FaCircleCheck/>}/><Action disabled={busy===item.id} onClick={()=>void setStatus(item.id,'declined')} label="Decline" icon={<FaXmark/>} danger/></div></article>):<p className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-white/35">No submissions match this view.</p>}</section>
 </Container></main>;
}
function Action({label,onClick,disabled,icon,danger=false}:{label:string;onClick:()=>void;disabled:boolean;icon?:React.ReactNode;danger?:boolean}){return <button disabled={disabled} onClick={onClick} className={`inline-flex min-h-10 items-center gap-2 rounded-lg border px-3 text-[10px] font-black uppercase disabled:opacity-40 ${danger?'border-red-400/20 text-red-200':'border-white/12 text-white/65'}`}>{icon}{label}</button>}
