'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Container } from '@/components/Container';
import { useAuth } from '@/hooks/useAuth';
import { getSupabaseClient } from '@/lib/supabase';
import type { FantasyRoster, FantasySeason, FantasyTeam, PublicPlayer } from '@/types/database';
import { calculateFantasyPoints } from '@/lib/rcl-algorithms';

type RosterRow = FantasyRoster & { player?: PublicPlayer };
const slots: Array<'starter'|'bench'> = ['starter','starter','starter','starter','starter','bench','bench','bench'];

export default function FantasyPage(){
 const {user,profile,loading:authLoading}=useAuth(); const supabase=useMemo(()=>getSupabaseClient(),[]); const [season,setSeason]=useState<FantasySeason|null>(null); const [team,setTeam]=useState<FantasyTeam|null>(null); const [roster,setRoster]=useState<RosterRow[]>([]); const [players,setPlayers]=useState<PublicPlayer[]>([]); const [teamName,setTeamName]=useState(''); const [search,setSearch]=useState(''); const [message,setMessage]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 const load=async()=>{if(!supabase)return;setLoading(true);const [seasonResult,playersResult]=await Promise.all([supabase.from('fantasy_seasons').select('*').eq('status','active').order('created_at',{ascending:false}).limit(1).maybeSingle(),supabase.from('public_players').select('*').eq('is_active',true).order('last_name').order('first_name').limit(200)]);if(seasonResult.error||playersResult.error){setMessage('Official fantasy data is not available yet.');setLoading(false);return;}setSeason(seasonResult.data);setPlayers(playersResult.data??[]);if(user&&seasonResult.data){const teamResult=await supabase.from('fantasy_teams').select('*').eq('fantasy_season_id',seasonResult.data.id).eq('manager_id',user.id).maybeSingle();if(teamResult.data){setTeam(teamResult.data);const rosterResult=await supabase.from('fantasy_rosters').select('*').eq('fantasy_team_id',teamResult.data.id);setRoster((rosterResult.data??[]).map(item=>({...item,player:(playersResult.data??[]).find(player=>player.id===item.player_id)})));}}setLoading(false);};
 useEffect(()=>{if(!authLoading)void load()},[authLoading,user,supabase]);
 const createTeam=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase||!user||!season||profile?.role!=='fan'||teamName.trim().length<2)return;setSaving(true);const result=await supabase.from('fantasy_teams').insert({fantasy_season_id:season.id,manager_id:user.id,name:teamName.trim()} as never).select().single();if(result.error)setMessage('Only fan accounts can create fantasy teams.');else{setTeam(result.data);setTeamName('');setMessage('Fantasy team created. Build your roster below.');}setSaving(false)};
 const addPlayer=async(player:PublicPlayer)=>{if(!supabase||!team||profile?.role!=='fan'||roster.some(item=>item.player_id===player.id)||roster.length>=(season?.roster_size??8))return;const slot=roster.filter(item=>item.roster_slot==='starter').length<5?'starter':'bench';const result=await supabase.from('fantasy_rosters').insert({fantasy_team_id:team.id,player_id:player.id,roster_slot:slot} as never);if(!result.error){setRoster(current=>[...current,{fantasy_team_id:team.id,player_id:player.id,roster_slot:slot,acquired_at:new Date().toISOString(),player}]);setSearch('');}};
 const removePlayer=async(playerId:string)=>{if(!supabase||!team)return;const result=await supabase.from('fantasy_rosters').delete().eq('fantasy_team_id',team.id).eq('player_id',playerId);if(!result.error)setRoster(current=>current.filter(item=>item.player_id!==playerId));};
 const available=players.filter(player=>!roster.some(item=>item.player_id===player.id)&&`${player.first_name} ${player.last_name}`.toLowerCase().includes(search.toLowerCase())).slice(0,12);
 if(authLoading||loading)return <main className="min-h-screen bg-rcl-black text-white"><Container maxWidth="xl" className="py-16"><div className="h-10 w-64 animate-pulse rounded bg-white/10"/></Container></main>;
 return <main className="min-h-screen bg-[#060a10] pb-24 text-white"><section className="border-b border-white/10 bg-gradient-to-br from-rcl-navy via-[#0b1422] to-black"><Container maxWidth="xl" className="py-10 sm:py-14"><p className="text-[10px] font-black tracking-[.28em] text-rcl-gold">RCL FANTASY · THE 804 DRAFT ROOM</p><h1 className="mt-3 font-display text-5xl font-black uppercase sm:text-7xl">Build the <span className="text-rcl-orange">squad.</span></h1><p className="mt-4 max-w-2xl text-sm leading-7 text-white/50">Draft real RCL players. Track official fantasy points. Compete with the basketball community.</p><div className="mt-7 grid max-w-3xl grid-cols-3 gap-3"><Metric label="ROSTER" value={`${season?.roster_size??8} spots`}/><Metric label="STARTERS" value="5"/><Metric label="SCORING" value="Official stats"/></div></Container></section><Container maxWidth="xl" className="py-8">
 {!user&&<Notice>Sign in as a fan to create and manage a fantasy team.</Notice>}{user&&profile?.role!=='fan'&&<Notice>Fantasy management is for fan accounts. You can still explore the official player pool.</Notice>}{message&&<Notice>{message}</Notice>}{!season&&<Notice>No active fantasy season is available yet.</Notice>}
 {season&&user&&profile?.role==='fan'&&!team&&<form onSubmit={createTeam} className="rounded-3xl border border-rcl-orange/25 bg-rcl-orange/5 p-6"><p className="text-[9px] font-black tracking-[.2em] text-rcl-orange">DRAFT ROOM ENTRY</p><h2 className="mt-2 font-display text-3xl font-black uppercase">Name your franchise</h2><div className="mt-5 flex flex-col gap-3 sm:flex-row"><input value={teamName} onChange={e=>setTeamName(e.target.value)} minLength={2} maxLength={60} placeholder="Example: 804 Ballers" className="min-h-12 flex-1 rounded-xl border border-white/10 bg-black/30 px-4 text-sm outline-none focus:border-rcl-orange"/><button disabled={saving} className="rounded-xl bg-rcl-orange px-6 py-3 text-xs font-black uppercase tracking-widest text-black disabled:opacity-50">{saving?'Creating…':'Create team'}</button></div></form>}
 {team&&<div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><section className="rounded-3xl border border-white/10 bg-white/[.03] p-5 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] font-black tracking-[.2em] text-rcl-orange">MY FANTASY FRANCHISE</p><h2 className="mt-2 font-display text-3xl font-black uppercase">{team.name}</h2></div><div className="text-right"><p className="text-[9px] font-black tracking-widest text-white/30">SEASON POINTS</p><p className="font-display text-4xl font-black text-rcl-gold">{team.total_points}</p></div></div><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-5">{['PG','SG','SF','PF','C'].map((position,index)=>{const player=roster.filter(item=>item.roster_slot==='starter')[index]?.player;return <div key={position} className="min-h-28 rounded-2xl border border-white/10 bg-black/25 p-3"><p className="text-[9px] font-black text-white/30">{position} · STARTER</p><p className="mt-5 text-sm font-black">{player?`${player.first_name} ${player.last_name}`:'OPEN SLOT'}</p>{player&&<button onClick={()=>removePlayer(player.id)} className="mt-2 text-[9px] font-black text-red-300">REMOVE</button>}</div>})}</div><div className="mt-7"><div className="flex items-center justify-between"><h3 className="font-display text-xl font-black uppercase">Bench</h3><span className="text-[9px] font-black tracking-widest text-white/30">{roster.filter(item=>item.roster_slot==='bench').length} FILLED</span></div><div className="mt-3 grid gap-2 sm:grid-cols-3">{roster.filter(item=>item.roster_slot==='bench').map(item=><div key={item.player_id} className="flex items-center justify-between rounded-xl border border-white/10 bg-black/20 p-3"><Link href={`/players/${item.player_id}`} className="text-xs font-bold hover:text-rcl-orange">{item.player?`${item.player.first_name} ${item.player.last_name}`:'RCL player'}</Link><button onClick={()=>removePlayer(item.player_id)} className="text-[9px] text-red-300">×</button></div>)}</div></div></section>
 <aside className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><p className="text-[9px] font-black tracking-[.2em] text-rcl-gold">PLAYER POOL</p><h2 className="mt-2 font-display text-2xl font-black uppercase">Draft a player</h2><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by player name…" className="mt-5 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-xs outline-none focus:border-rcl-orange"/><div className="mt-4 space-y-2">{available.map(player=><button type="button" key={player.id} onClick={()=>addPlayer(player)} className="flex w-full items-center justify-between rounded-xl border border-white/10 bg-black/20 p-3 text-left hover:border-rcl-orange/40"><span><strong className="block text-xs">{player.first_name} {player.last_name}</strong><small className="text-[9px] text-white/35">{player.position??'Position'} · {player.jersey_number?`#${player.jersey_number}`:'RCL'}</small></span><span className="text-rcl-orange">+</span></button>)}{!available.length&&<p className="py-5 text-center text-xs text-white/30">No available players match that search.</p>}</div><div className="mt-6 rounded-2xl border border-rcl-blue/20 bg-rcl-blue/5 p-4"><p className="text-[9px] font-black tracking-widest text-rcl-blue">HOW SCORING WORKS</p><p className="mt-2 text-xs leading-5 text-white/45">Fantasy points are calculated from verified RCL points, rebounds, assists, steals, blocks and turnovers.</p><p className="mt-3 font-display text-xl font-black text-rcl-gold">{calculateFantasyPoints({points:20,rebounds:10,assists:5,steals:2,blocks:1,turnovers:3)}<span className="ml-2 text-[9px] text-white/30">EXAMPLE PTS</span></p></div></aside></div>}
 {season&&<section className="mt-8 grid gap-4 sm:grid-cols-3"><Info title="OFFICIAL DATA" body="Fantasy scoring follows verified league statistics."/><Info title="FAN FIRST" body="Fantasy teams are built by RCL fan accounts."/><Info title="BUILD A LEGACY" body="Use the same player pool powering the league experience."/></section>}
 </Container></main>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-black/25 p-3"><p className="text-[8px] font-black tracking-widest text-white/30">{label}</p><p className="mt-1 text-xs font-bold">{value}</p></div>}
function Notice({children}:{children:React.ReactNode}){return <div className="mb-5 rounded-2xl border border-white/10 bg-white/[.03] p-4 text-sm text-white/55">{children}</div>}
function Info({title,body}:{title:string;body:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-[9px] font-black tracking-widest text-rcl-orange">{title}</p><p className="mt-2 text-xs leading-5 text-white/45">{body}</p></div>}
