'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { FaArrowLeft, FaBell, FaEnvelope, FaMobileScreenButton } from 'react-icons/fa6';
import { Container } from '@/components/Container';
import { ClientPageHero } from '@/components/ClientPageHero';
import { PWAAppAlertsCard } from '@/components/PWAAppAlertsCard';
import { useAuth } from '@/hooks/useAuth';
import { getSupabaseClient } from '@/lib/supabase';

type Preferences={messages:boolean;friend_requests:boolean;comments:boolean;reactions:boolean;announcements:boolean;email_enabled:boolean;email_messages:boolean;email_social:boolean;email_league:boolean;games:boolean;rep:boolean;missions:boolean;fantasy:boolean;runs:boolean;media:boolean;lab:boolean;pickem:boolean;push_enabled:boolean};
const defaults:Preferences={messages:true,friend_requests:true,comments:true,reactions:true,announcements:true,email_enabled:true,email_messages:true,email_social:true,email_league:true,games:true,rep:true,missions:true,fantasy:true,runs:true,media:true,lab:true,pickem:true,push_enabled:true};
const groups=[
 {title:'Basketball',icon:FaBell,items:[['games','Games & Game Night','Tip-offs, live-game activity and official results.'],['rep','REP & levels','REP gains, status changes and milestones.'],['missions','Weekly missions','Mission progress, completion and reward reminders.'],['runs','Open Runs','Runs you joined, capacity and court activity.'],['lab','The Lab','Training reminders and completed workout activity.'],['pickem','Pick’em','Pick locks and scored prediction results.'],['fantasy','Fantasy','Fantasy league activity and results.'],['media','RCH TV & highlights','Published clips, tagged highlights and featured media.']]},
 {title:'Social',icon:FaMobileScreenButton,items:[['messages','Messages','New direct messages.'],['friend_requests','Basketball connections','Friend and connection requests.'],['comments','Comments','Replies and comments on your content.'],['reactions','Reactions','Reactions to your posts and activity.'],['announcements','League announcements','Important official RCL updates.']]},
 {title:'Email',icon:FaEnvelope,items:[['email_enabled','Email delivery','Master switch for RCL email notifications.'],['email_messages','Message email alerts','Email for important direct-message activity.'],['email_social','Social email alerts','Email for social and community activity.'],['email_league','League email alerts','Email for league operations, games and announcements.']]},
] as const;

export default function NotificationSettingsPage(){
 const {user,loading:authLoading}=useAuth();const supabase=useMemo(()=>getSupabaseClient(true),[]);const db=supabase as any;const [prefs,setPrefs]=useState<Preferences>(defaults);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState('');const [notice,setNotice]=useState('');const [error,setError]=useState('');
 const load=useCallback(async()=>{if(!db||!user){setLoading(false);return;}setLoading(true);const {data,error:loadError}=await db.from('notification_preferences').select('*').eq('profile_id',user.id).maybeSingle();if(loadError)setError(loadError.message);if(data)setPrefs({...defaults,...data} as Preferences);setLoading(false);},[db,user]);useEffect(()=>{void load();},[load]);
 const toggle=async(key:keyof Preferences)=>{if(!db||!user)return;const value=!prefs[key];setPrefs(current=>({...current,[key]:value}));setSaving(key);setNotice('');setError('');const {error:saveError}=await db.from('notification_preferences').upsert({profile_id:user.id,[key]:value,updated_at:new Date().toISOString()},{onConflict:'profile_id'});if(saveError){setPrefs(current=>({...current,[key]:!value}));setError(saveError.message);}else setNotice('Notification preference saved.');setSaving('');};
 return <main className="rcl-social-secondary min-h-screen bg-[#03070d] pb-28 text-white"><ClientPageHero eyebrow="RCL Alerts" title="Notification Control" accent="Your game. Your signal." description="Choose exactly which basketball, social, push and email events deserve your attention instead of treating every RCL update the same." assetKey="social.cover" actions={<Link href="/notifications" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/15 px-4 text-xs font-black uppercase tracking-wider"><FaArrowLeft/>Notifications</Link>}/><Container maxWidth="lg" className="py-9 sm:py-12"><PWAAppAlertsCard/>{notice&&<p className="mt-5 rounded-2xl border border-emerald-400/20 bg-emerald-400/[.06] p-4 text-sm text-emerald-100">{notice}</p>}{error&&<p className="mt-5 rounded-2xl border border-red-400/20 bg-red-400/[.06] p-4 text-sm text-red-100">{error}</p>}{!user&&!authLoading?<div className="mt-6 rounded-3xl border border-rcl-blue/15 bg-[#071522]/50 p-10 text-center"><FaBell className="mx-auto text-3xl text-rcl-blue"/><h2 className="mt-4 font-display text-2xl font-black uppercase">Sign in to control alerts</h2><Link href="/auth/sign-in?next=/settings/notifications" className="mt-5 inline-flex rounded-xl bg-rcl-orange px-5 py-3 text-xs font-black uppercase text-black">Sign in</Link></div>:<div className="mt-7 space-y-6">{groups.map(({title,icon:Icon,items})=><section key={title} className="overflow-hidden rounded-3xl border border-white/10 bg-white/[.02]"><div className="flex items-center gap-3 border-b border-white/10 px-5 py-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-rcl-blue/10 text-rcl-blue"><Icon/></span><h2 className="font-display text-xl font-black uppercase">{title}</h2></div><div className="divide-y divide-white/[.06]">{items.map(([key,label,detail])=>{const typed=key as keyof Preferences;return <div key={key} className="flex items-center justify-between gap-5 px-5 py-4"><div><p className="text-sm font-black">{label}</p><p className="mt-1 text-xs leading-5 text-white/35">{detail}</p></div><button type="button" disabled={loading||saving===key} onClick={()=>void toggle(typed)} aria-pressed={prefs[typed]} className={`relative h-7 w-12 shrink-0 rounded-full border transition ${prefs[typed]?'border-rcl-orange/50 bg-rcl-orange':'border-white/15 bg-white/10'} disabled:opacity-40`}><span className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow transition ${prefs[typed]?'left-6':'left-1'}`}/></button></div>})}</div></section>)}</div>}</Container></main>;
}
