'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react'; import Link from 'next/link'; import {getSupabaseClient} from '@/lib/supabase'; import {useAuth} from '@/hooks/useAuth';
const cats=['scoring','creation','playmaking','defense','athleticism','iq']; const tests:Record<string,{label:string;unit:string;max:number}>={
scoring:{label:'Makes from 25 standardized shots',unit:'/25',max:25},creation:{label:'Controlled handle circuit score',unit:'/20',max:20},playmaking:{label:'Correct reads from 20 scenarios',unit:'/20',max:20},defense:{label:'Defensive movement circuit score',unit:'/20',max:20},athleticism:{label:'Athletic circuit score',unit:'/20',max:20},iq:{label:'Film decision test',unit:'/20',max:20}};
const programs=[['rim-pressure','14-Day Rim Pressure',8,'Finishing through contact'],['shooter','21-Day Shooter',12,'Three-point consistency'],['lockdown','Lockdown Defender',8,'On-ball and help defense'],['point-iq','Point Guard IQ',8,'Reads and decision making'],['tryout','Tryout Ready',10,'Complete competitive preparation'],['conditioning','Game Conditioning',8,'Repeat-effort conditioning']];
export default function PlayerLabPage(){const {user}=useAuth(),db=useMemo(()=>getSupabaseClient() as any,[]);const [scores,setScores]=useState<Record<string,number>>({}),[program,setProgram]=useState<any>(null),[notes,setNotes]=useState<any[]>([]),[title,setTitle]=useState(''),[body,setBody]=useState(''),[msg,setMsg]=useState('');
async function load(){if(!user||!db)return;const [a,p,n]=await Promise.all([db.from('lab_assessments').select('*').eq('profile_id',user.id).order('assessed_at',{ascending:false}),db.from('lab_program_enrollments').select('*').eq('profile_id',user.id).eq('status','active').limit(1).maybeSingle(),db.from('lab_notebook_entries').select('*').eq('profile_id',user.id).order('created_at',{ascending:false}).limit(20)]);const x:Record<string,number>={};for(const r of a.data||[])if(x[r.category]===undefined)x[r.category]=r.score;setScores(x);setProgram(p.data);setNotes(n.data||[])}
useEffect(()=>{void load()},[user]);
async function assess(cat:string,value:number){if(!user)return;const t=tests[cat],score=Math.round(Math.min(100,value/t.max*100));const {error}=await db.from('lab_assessments').insert({profile_id:user.id,category:cat,score,verification_status:'self',notes:t.label});setMsg(error?.message||cat.toUpperCase()+' baseline saved');if(!error)load()}
async function enroll(p:any){if(!user)return;await db.from('lab_program_enrollments').update({status:'paused'}).eq('profile_id',user.id).eq('status','active');const {error}=await db.from('lab_program_enrollments').upsert({profile_id:user.id,program_key:p[0],program_name:p[1],total_sessions:p[2],completed_sessions:0,focus:p[3],status:'active'},{onConflict:'profile_id,program_key'});setMsg(error?.message||p[1]+' started');if(!error)load()}
async function note(e:FormEvent){e.preventDefault();if(!user||!title.trim())return;const {error}=await db.from('lab_notebook_entries').insert({profile_id:user.id,title:title.trim(),body:body.trim(),visibility:'private'});if(!error){setTitle('');setBody('');load()}setMsg(error?.message||'Notebook updated')}
return <main className="min-h-screen bg-[#03080d] px-4 py-24 text-white"><div className="mx-auto max-w-6xl"><Link href="/lab" className="text-xs text-rcl-orange">← THE LAB</Link><h1 className="mt-4 font-display text-5xl font-black">PLAYER LAB</h1><p className="mt-2 max-w-2xl text-sm text-white/45">Assess → Train → Prove. Self-tested results establish a development baseline; they never change official RCL ratings.</p>{msg&&<p className="mt-4 rounded-lg border border-rcl-orange/30 bg-rcl-orange/10 p-3 text-xs">{msg}</p>}
<section className="mt-10"><h2 className="font-display text-2xl">1 // BASELINE ASSESSMENTS</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{cats.map(cat=><Assessment key={cat} cat={cat} score={scores[cat]} save={assess}/>)}</div></section>
<section className="mt-12"><h2 className="font-display text-2xl">2 // DEVELOPMENT PROGRAMS</h2>{program&&<p className="mt-2 text-xs text-rcl-orange">ACTIVE · {program.program_name} · {program.completed_sessions}/{program.total_sessions}</p>}<div className="mt-4 grid gap-3 md:grid-cols-3">{programs.map(p=><button key={p[0] as string} onClick={()=>enroll(p)} className="rounded-xl border border-white/10 bg-white/[.03] p-5 text-left hover:border-rcl-orange/50"><b>{p[1]}</b><small className="mt-2 block text-white/40">{p[3]} · {p[2]} sessions</small></button>)}</div></section>
<section className="mt-12 grid gap-4 md:grid-cols-2"><form onSubmit={note} className="rounded-xl border border-white/10 p-5"><h2 className="font-display text-xl">MY NOTEBOOK</h2><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} placeholder="Session note title" className="mt-4 w-full rounded-lg bg-white/5 p-3"/><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={4000} placeholder="What changed? What needs work?" className="mt-3 min-h-32 w-full rounded-lg bg-white/5 p-3"/><button className="mt-3 rounded-lg bg-rcl-orange px-5 py-3 text-xs font-black">SAVE PRIVATE NOTE</button></form><div className="rounded-xl border border-white/10 p-5"><h2 className="font-display text-xl">RECENT NOTES</h2>{notes.length?notes.map(n=><article key={n.id} className="border-b border-white/10 py-3"><b className="text-sm">{n.title}</b><p className="mt-1 text-xs text-white/45">{n.body}</p></article>):<p className="mt-4 text-xs text-white/35">Your development journal starts here.</p>}</div></section>
<section className="mt-12 grid gap-3 md:grid-cols-3"><Link className="rounded-xl border border-white/10 p-5" href="/lab/film-room"><b>FILM ROOM →</b><p className="mt-2 text-xs text-white/40">Study possessions and save lessons.</p></Link><Link className="rounded-xl border border-white/10 p-5" href="/lab/challenges"><b>CHALLENGES →</b><p className="mt-2 text-xs text-white/40">Compete against measurable targets.</p></Link><Link className="rounded-xl border border-white/10 p-5" href="/game-iq"><b>PROVE IT →</b><p className="mt-2 text-xs text-white/40">Compare development with official game performance.</p></Link></section></div></main>}
function Assessment({cat,score,save}:{cat:string;score?:number;save:(c:string,v:number)=>void}){const [v,setV]=useState('');const t=tests[cat];return <article className="rounded-xl border border-white/10 bg-white/[.03] p-5"><small className="font-black uppercase text-rcl-orange">{cat}</small><b className="mt-2 block text-3xl">{score??'—'}</b><p className="mt-2 min-h-10 text-xs text-white/40">{t.label}</p><div className="mt-4 flex gap-2"><input type="number" min="0" max={t.max} value={v} onChange={e=>setV(e.target.value)} className="w-full rounded-lg bg-white/5 p-2"/><button onClick={()=>save(cat,Number(v))} disabled={v===''||Number(v)<0||Number(v)>t.max} className="rounded-lg bg-white/10 px-3 text-xs">SAVE</button></div><small className="mt-2 block text-white/25">SELF TESTED · {t.unit}</small></article>}
