'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { FaArrowRightArrowLeft, FaBasketball, FaChartLine, FaMedal } from 'react-icons/fa6';
import { Container } from '@/components/Container';
import { ClientPageHero } from '@/components/ClientPageHero';
import { getSupabaseClient } from '@/lib/supabase';

type Player={player_id:string;first_name:string;last_name:string;position:string|null;jersey_number:number|null;photo_url:string|null;overall_rating:number;archetype:string;ppg:number|null;rpg:number|null;apg:number|null;spg:number|null;bpg:number|null;badge_count:number;award_count:number;seasons_played:number};
type Advanced={player_id:string;games_played:number;ppg:number|null;rpg:number|null;apg:number|null;spg:number|null;bpg:number|null;avg_plus_minus:number|null;assist_turnover_ratio:number|null;true_shooting_pct:number|null;effective_fg_pct:number|null;three_pct:number|null;free_throw_pct:number|null};
function f(value:number|null|undefined,suffix=''){return value===null||value===undefined?'—':`${Number(value).toFixed(1)}${suffix}`;}

export default function PlayerComparePage(){
 const search=useSearchParams();const supabase=useMemo(()=>getSupabaseClient(true),[]);const db=supabase as any;const [players,setPlayers]=useState<Player[]>([]);const [advanced,setAdvanced]=useState<Advanced[]>([]);const [left,setLeft]=useState(search.get('left')??'');const [right,setRight]=useState(search.get('right')??'');const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!db){setLoading(false);return;}void(async()=>{const [cards,analytics]=await Promise.all([db.from('player_card_live').select('*').order('overall_rating',{ascending:false}).limit(250),db.from('player_advanced_analytics').select('*').limit(250)]);setPlayers((cards.data??[]) as Player[]);setAdvanced((analytics.data??[]) as Advanced[]);setLoading(false);})();},[db]);
 useEffect(()=>{if(!left&&players[0])setLeft(players[0].player_id);if(!right&&players[1])setRight(players[1].player_id);},[left,right,players]);
 const a=players.find(p=>p.player_id===left);const b=players.find(p=>p.player_id===right);const aa=advanced.find(p=>p.player_id===left);const bb=advanced.find(p=>p.player_id===right);
 const rows=[['Overall',a?.overall_rating,b?.overall_rating],['PPG',f(aa?.ppg),f(bb?.ppg)],['RPG',f(aa?.rpg),f(bb?.rpg)],['APG',f(aa?.apg),f(bb?.apg)],['SPG',f(aa?.spg),f(bb?.spg)],['BPG',f(aa?.bpg),f(bb?.bpg)],['True shooting',f(aa?.true_shooting_pct,'%'),f(bb?.true_shooting_pct,'%')],['eFG%',f(aa?.effective_fg_pct,'%'),f(bb?.effective_fg_pct,'%')],['AST/TO',f(aa?.assist_turnover_ratio),f(bb?.assist_turnover_ratio)],['+/-',f(aa?.avg_plus_minus),f(bb?.avg_plus_minus)],['Badges',a?.badge_count??'—',b?.badge_count??'—'],['Awards',a?.award_count??'—',b?.award_count??'—'],['RCL seasons',a?.seasons_played??'—',b?.seasons_played??'—']];
 return <main className="min-h-screen bg-[#03070d] pb-28 text-white"><ClientPageHero eyebrow="RCL Analytics Lab" title="Player Compare" accent="Side by side" description="Compare verified RCL player cards, traditional production and advanced efficiency without turning the platform into an opinion ranking." assetKey="players.cover" meta={<div className="rounded-2xl border border-rcl-blue/20 bg-[#071522]/85 p-5"><FaArrowRightArrowLeft className="text-2xl text-rcl-blue"/><p className="mt-3 text-xs font-black uppercase tracking-wider text-white/35">Live RCL data</p></div>}/><Container maxWidth="lg" className="py-9 sm:py-12">{loading?<div className="h-[60vh] animate-pulse rounded-3xl border border-white/10 bg-white/[.02]"/>:<><div className="grid gap-4 md:grid-cols-2"><SelectPlayer label="Player one" value={left} setValue={setLeft} players={players}/><SelectPlayer label="Player two" value={right} setValue={setRight} players={players}/></div>{a&&b?<><section className="mt-6 grid grid-cols-[1fr_auto_1fr] items-stretch gap-3"><PlayerCard player={a}/><div className="grid place-items-center"><span className="grid h-12 w-12 place-items-center rounded-full border border-rcl-orange/30 bg-rcl-orange/10 font-display text-sm font-black text-rcl-orange">VS</span></div><PlayerCard player={b} right/></section><section className="mt-6 overflow-hidden rounded-3xl border border-white/10 bg-white/[.02]"><div className="grid grid-cols-[1fr_1.2fr_1fr] border-b border-white/10 bg-rcl-blue/[.04] px-4 py-3 text-[10px] font-black uppercase tracking-wider text-white/35"><span>{a.last_name}</span><span className="text-center">Metric</span><span className="text-right">{b.last_name}</span></div>{rows.map(([label,av,bv])=><div key={String(label)} className="grid grid-cols-[1fr_1.2fr_1fr] items-center border-b border-white/[.06] px-4 py-4 last:border-0"><b className="font-display text-lg">{av}</b><span className="text-center text-[10px] font-black uppercase tracking-wider text-white/35">{label}</span><b className="text-right font-display text-lg">{bv}</b></div>)}</section><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link href={`/players/${a.player_id}/passport`} className="rounded-2xl border border-rcl-blue/20 bg-rcl-blue/[.04] p-4 text-center text-xs font-black uppercase tracking-wider text-rcl-blue">Open {a.first_name}&apos;s Passport</Link><Link href={`/players/${b.player_id}/passport`} className="rounded-2xl border border-rcl-orange/20 bg-rcl-orange/[.04] p-4 text-center text-xs font-black uppercase tracking-wider text-rcl-orange">Open {b.first_name}&apos;s Passport</Link></div></>:<div className="mt-6 rounded-3xl border border-dashed border-white/10 p-10 text-center text-sm text-white/35">Select two players to compare.</div>}</>}</Container></main>;
}

function SelectPlayer({label,value,setValue,players}:{label:string;value:string;setValue:(value:string)=>void;players:Player[]}){return <label className="rounded-2xl border border-white/10 bg-white/[.02] p-4 text-[10px] font-black uppercase tracking-wider text-white/35">{label}<select value={value} onChange={e=>setValue(e.target.value)} className="mt-2 h-12 w-full rounded-xl border border-white/10 bg-[#071018] px-3 text-sm font-bold normal-case tracking-normal text-white outline-none focus:border-rcl-blue/40">{players.map(p=><option key={p.player_id} value={p.player_id}>{p.first_name} {p.last_name} · {p.position??'RCL'} · {p.overall_rating}</option>)}</select></label>;}
function PlayerCard({player,right=false}:{player:Player;right?:boolean}){return <article className={`rounded-3xl border p-4 sm:p-6 ${right?'border-rcl-orange/20 bg-rcl-orange/[.035]':'border-rcl-blue/20 bg-rcl-blue/[.035]'}`}><div className={`flex flex-col gap-4 ${right?'items-end text-right':'items-start'}`}><div className="relative h-20 w-20 overflow-hidden rounded-2xl border border-white/10 bg-black/30">{player.photo_url?<Image src={player.photo_url} alt={`${player.first_name} ${player.last_name}`} fill sizes="80px" className="object-cover"/>:<div className="grid h-full place-items-center"><FaBasketball className="text-2xl text-white/25"/></div>}</div><div><p className="text-[9px] font-black uppercase tracking-wider text-white/30">{player.position??'RCL Player'} · #{player.jersey_number??'—'}</p><h2 className="mt-1 font-display text-xl font-black uppercase sm:text-3xl">{player.first_name} {player.last_name}</h2><p className={`mt-2 text-[10px] font-black uppercase tracking-wider ${right?'text-rcl-orange':'text-rcl-blue'}`}>{player.archetype}</p></div><div className="flex items-end gap-2"><FaMedal className="mb-1 text-rcl-orange"/><b className="font-display text-5xl">{player.overall_rating}</b><span className="mb-1 text-[9px] font-black uppercase text-white/30">OVR</span></div></div></article>;}
