'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { FaBasketball, FaBolt, FaComments, FaFire, FaHeart, FaMedal, FaPaperPlane } from 'react-icons/fa6';
import { getSupabaseClient } from '@/lib/supabase';
import { useAuth } from '@/hooks/useAuth';

type EventRow={id:string;sequence_no:number;period_number:number;clock_seconds:number|null;event_type:string;team_id:string|null;player_id:string|null;points:number;shot_result:string|null;shot_value:number|null;shot_x:number|null;shot_y:number|null;shot_zone:string|null;created_at:string};
type Player={id:string;first_name:string;last_name:string};
type Stat={player_id:string;team_id:string;points:number;rebounds:number;assists:number;steals:number;blocks:number;plus_minus:number|null};
type Reaction={reaction_key:string};
type Vote={player_id:string;votes:number};
type Chat={id:string;profile_id:string;body:string;created_at:string;author?:{display_name:string|null;username:string|null}|null};
type LiveState={status:string;home_score:number;away_score:number;period_number:number|null;clock_seconds:number|null;last_sequence:number|null;last_event_type:string|null};

const reactions=[['fire','🔥'],['wow','😮'],['clutch','⏱️'],['defense','🛡️'],['bucket','🪣'],['crowd','📣']] as const;
function clock(seconds:number|null){if(seconds===null)return '—';const safe=Math.max(0,seconds);return `${Math.floor(safe/60)}:${String(safe%60).padStart(2,'0')}`;}
function eventLabel(type:string){return type.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}

export function GameNightExperience({gameId,homeName,awayName}:{gameId:string;homeName:string;awayName:string}){
 const {user}=useAuth(); const supabase=useMemo(()=>getSupabaseClient(true),[]); const db=supabase as any;
 const [live,setLive]=useState<LiveState|null>(null); const [events,setEvents]=useState<EventRow[]>([]); const [players,setPlayers]=useState<Player[]>([]); const [stats,setStats]=useState<Stat[]>([]); const [reactionRows,setReactionRows]=useState<Reaction[]>([]); const [votes,setVotes]=useState<Vote[]>([]); const [myVote,setMyVote]=useState<string|null>(null); const [chat,setChat]=useState<Chat[]>([]); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(''); const [error,setError]=useState('');
 const load=useCallback(async()=>{if(!db)return;const [liveResult,eventResult,statResult,reactionResult,voteResult,chatResult]=await Promise.all([
  db.from('game_live_state').select('*').eq('game_id',gameId).maybeSingle(),
  db.from('game_events').select('id,sequence_no,period_number,clock_seconds,event_type,team_id,player_id,points,shot_result,shot_value,shot_x,shot_y,shot_zone,created_at').eq('game_id',gameId).is('voided_at',null).order('sequence_no',{ascending:false}).limit(80),
  db.from('player_game_stats').select('player_id,team_id,points,rebounds,assists,steals,blocks,plus_minus').eq('game_id',gameId),
  db.from('game_reactions').select('reaction_key').eq('game_id',gameId),
  db.from('game_mvp_tallies').select('player_id,votes').eq('game_id',gameId),
  user?db.from('game_chat_messages').select('id,profile_id,body,created_at,author:profiles!game_chat_messages_profile_id_fkey(display_name,username)').eq('game_id',gameId).is('deleted_at',null).order('created_at',{ascending:false}).limit(30):Promise.resolve({data:[],error:null}),
 ]);setLive((liveResult.data??null) as LiveState|null);const eventRows=(eventResult.data??[]) as EventRow[];const statRows=(statResult.data??[]) as Stat[];setEvents(eventRows);setStats(statRows);setReactionRows((reactionResult.data??[]) as Reaction[]);setVotes((voteResult.data??[]) as Vote[]);setChat((chatResult.data??[]) as Chat[]);const ids=[...new Set([...eventRows.map(e=>e.player_id),...statRows.map(s=>s.player_id)].filter(Boolean))] as string[];if(ids.length){const {data}=await db.from('public_players').select('id,first_name,last_name').in('id',ids);setPlayers((data??[]) as Player[]);}if(user){const {data}=await db.from('game_mvp_votes').select('player_id').eq('game_id',gameId).eq('voter_profile_id',user.id).maybeSingle();setMyVote(data?.player_id??null);}else setMyVote(null);},[db,gameId,user]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(!supabase)return;const channel=supabase.channel(`game-night-${gameId}`).on('postgres_changes',{event:'*',schema:'public',table:'games',filter:`id=eq.${gameId}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'game_events',filter:`game_id=eq.${gameId}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'game_reactions',filter:`game_id=eq.${gameId}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'game_mvp_votes',filter:`game_id=eq.${gameId}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'game_chat_messages',filter:`game_id=eq.${gameId}`},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel);};},[gameId,load,supabase]);
 const playerMap=useMemo(()=>new Map(players.map(p=>[p.id,p])),[players]); const name=(id:string|null)=>{if(!id)return 'Team play';const p=playerMap.get(id);return p?`${p.first_name} ${p.last_name}`:'RCL Player';};
 const reactionCounts=useMemo(()=>reactionRows.reduce<Record<string,number>>((map,row)=>{map[row.reaction_key]=(map[row.reaction_key]??0)+1;return map;},{}),[reactionRows]);
 const shots=events.filter(e=>e.shot_x!==null&&e.shot_y!==null&&['shot_made','shot_missed'].includes(e.event_type)); const hot=[...stats].sort((a,b)=>b.points-a.points)[0];
 const react=async(key:string)=>{if(!db||!user)return;setBusy(`reaction-${key}`);setError('');const {error:insertError}=await db.from('game_reactions').upsert({game_id:gameId,profile_id:user.id,reaction_key:key},{onConflict:'game_id,profile_id,reaction_key'});if(insertError)setError(insertError.message);setBusy('');};
 const vote=async(playerId:string)=>{if(!db||!user)return;setBusy(`vote-${playerId}`);setError('');const {error:voteError}=await db.from('game_mvp_votes').upsert({game_id:gameId,voter_profile_id:user.id,player_id:playerId},{onConflict:'game_id,voter_profile_id'});if(voteError)setError(voteError.message);else setMyVote(playerId);setBusy('');};
 const send=async()=>{const body=message.trim();if(!db||!user||!body)return;setBusy('chat');setError('');const {error:sendError}=await db.from('game_chat_messages').insert({game_id:gameId,profile_id:user.id,body});if(sendError)setError(sendError.message);else setMessage('');setBusy('');};
 return <section className="mt-6 overflow-hidden rounded-3xl border border-rcl-orange/20 bg-[radial-gradient(circle_at_top_left,rgba(59,130,246,.10),transparent_36%),#050a10]">
  <div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-5 py-4 sm:px-7"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-rcl-orange"><FaFire className="mr-2 inline"/>RCL Game Night</p><h2 className="mt-1 font-display text-2xl font-black uppercase">Live basketball layer</h2></div><div className="flex items-center gap-2">{live?.status==='live'&&<span className="rounded-full border border-red-400/30 bg-red-400/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-wider text-red-300">Live</span>}<span className="rounded-full border border-white/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-wider text-white/35">Q{live?.period_number??'—'} · {clock(live?.clock_seconds??null)}</span></div></div>
  {error&&<p className="mx-5 mt-5 rounded-xl border border-red-400/20 bg-red-400/[.06] p-3 text-xs text-red-100 sm:mx-7">{error}</p>}
  <div className="grid gap-0 xl:grid-cols-[1.1fr_.9fr]">
   <div className="p-5 sm:p-7"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-4 rounded-2xl border border-white/10 bg-black/25 p-5"><div><p className="text-[10px] font-black uppercase tracking-wider text-white/30">Away</p><p className="mt-1 font-display text-lg font-black uppercase sm:text-2xl">{awayName}</p></div><div className="font-display text-4xl font-black sm:text-5xl">{live?.away_score??0}<span className="mx-3 text-white/20">–</span>{live?.home_score??0}</div><div className="text-right"><p className="text-[10px] font-black uppercase tracking-wider text-white/30">Home</p><p className="mt-1 font-display text-lg font-black uppercase sm:text-2xl">{homeName}</p></div></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-white/10 bg-[#0a1119] p-4"><div className="mb-3 flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-rcl-blue"><FaBasketball className="mr-1 inline"/>Live shot chart</p><p className="mt-1 text-xs text-white/35">Official scorebook locations</p></div><span className="text-[10px] font-black text-white/30">{shots.length} shots</span></div><div className="relative aspect-[50/47] overflow-hidden rounded-xl border border-white/10 bg-[#9f6737]"><svg viewBox="0 0 50 47" preserveAspectRatio="none" className="absolute inset-0 h-full w-full" aria-hidden="true"><rect x=".4" y=".4" width="49.2" height="46.2" fill="none" stroke="#fffaf0" strokeWidth=".28"/><rect x="17" y=".4" width="16" height="18.6" fill="rgba(0,0,0,.10)" stroke="#fffaf0" strokeWidth=".28"/><circle cx="25" cy="19" r="6" fill="none" stroke="#fffaf0" strokeWidth=".28"/><line x1="22" y1="4" x2="28" y2="4" stroke="#fffaf0" strokeWidth=".3"/><circle cx="25" cy="5.25" r=".75" fill="none" stroke="#ff641f" strokeWidth=".34"/><path d="M3 0V14.15M47 0V14.15M3 14.15A23.75 23.75 0 0 0 47 14.15" fill="none" stroke="#fffaf0" strokeWidth=".3"/><line x1=".4" y1="46.6" x2="49.6" y2="46.6" stroke="#fffaf0" strokeWidth=".28"/></svg>{shots.slice(0,80).map(shot=><span key={shot.id} title={`${name(shot.player_id)} · ${eventLabel(shot.event_type)}`} className={`absolute h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full border ${shot.event_type==='shot_made'?'border-emerald-100 bg-emerald-400':'border-rose-100 bg-rose-400'}`} style={{left:`${shot.shot_x}%`,top:`${shot.shot_y}%`}}/> )}</div><div className="mt-3 flex gap-4 text-[10px] font-black uppercase tracking-wider text-white/35"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-emerald-400"/>Made</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-rose-400"/>Missed</span></div></div>
     <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-rcl-orange"><FaBolt className="mr-1 inline"/>Who’s hot</p>{hot?<><h3 className="mt-3 font-display text-2xl font-black uppercase">{name(hot.player_id)}</h3><div className="mt-4 grid grid-cols-3 gap-2">{[['PTS',hot.points],['REB',hot.rebounds],['AST',hot.assists]].map(([label,value])=><span key={label} className="rounded-xl bg-white/[.04] p-3 text-center"><small className="block text-[9px] font-black text-white/30">{label}</small><b className="mt-1 block font-display text-xl">{value}</b></span>)}</div><p className="mt-3 text-xs text-white/35">Plus/minus {hot.plus_minus??'—'}</p></>:<p className="mt-4 text-sm leading-6 text-white/35">Live player leaders appear as the scorebook records official stats.</p>}</div></div>
    <div className="mt-4 rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-wider text-white/35"><FaHeart className="mr-1 inline"/>Crowd reactions</p><span className="text-[10px] text-white/25">Tap to react</span></div><div className="mt-3 flex flex-wrap gap-2">{reactions.map(([key,emoji])=><button type="button" key={key} disabled={!user||busy===`reaction-${key}`} onClick={()=>void react(key)} className="inline-flex min-h-10 items-center gap-2 rounded-full border border-white/10 bg-white/[.03] px-3 text-sm transition hover:border-rcl-orange/35 disabled:opacity-40"><span>{emoji}</span><b className="text-xs">{reactionCounts[key]??0}</b></button>)}</div></div>
   </div>
   <aside className="border-t border-white/10 p-5 sm:p-7 xl:border-l xl:border-t-0"><div><p className="text-[10px] font-black uppercase tracking-wider text-rcl-blue"><FaBolt className="mr-1 inline"/>Play-by-play</p><div className="mt-4 max-h-72 space-y-2 overflow-y-auto pr-1">{events.length?events.slice(0,30).map(event=><div key={event.id} className="rounded-xl border border-white/8 bg-white/[.02] p-3"><div className="flex items-center justify-between gap-2"><span className="text-[9px] font-black uppercase tracking-wider text-rcl-orange">Q{event.period_number} · {clock(event.clock_seconds)}</span><span className="text-[9px] text-white/25">#{event.sequence_no}</span></div><p className="mt-1 text-xs font-black">{name(event.player_id)}</p><p className="mt-1 text-[11px] text-white/40">{eventLabel(event.event_type)}{event.points?` · +${event.points}`:''}{event.shot_zone?` · ${event.shot_zone.replace(/_/g,' ')}`:''}</p></div>):<p className="rounded-xl border border-dashed border-white/10 p-5 text-xs leading-5 text-white/35">Play-by-play activates as the official scorebook records events.</p>}</div></div>
    <div className="mt-6 border-t border-white/10 pt-5"><p className="text-[10px] font-black uppercase tracking-wider text-rcl-orange"><FaMedal className="mr-1 inline"/>Fan MVP vote</p><div className="mt-3 space-y-2">{[...stats].sort((a,b)=>b.points-a.points).slice(0,6).map(stat=>{const tally=votes.find(v=>v.player_id===stat.player_id)?.votes??0;return <button type="button" key={stat.player_id} disabled={!user||busy===`vote-${stat.player_id}`} onClick={()=>void vote(stat.player_id)} className={`flex w-full items-center justify-between rounded-xl border p-3 text-left transition ${myVote===stat.player_id?'border-rcl-orange/40 bg-rcl-orange/[.08]':'border-white/10 bg-white/[.02] hover:border-rcl-blue/30'} disabled:opacity-50`}><span><b className="block text-xs">{name(stat.player_id)}</b><small className="mt-1 block text-[10px] text-white/30">{stat.points} PTS · {stat.rebounds} REB · {stat.assists} AST</small></span><span className="text-xs font-black text-rcl-orange">{tally}</span></button>})}{!stats.length&&<p className="text-xs leading-5 text-white/35">MVP voting opens when player stats are available.</p>}</div></div>
    <div className="mt-6 border-t border-white/10 pt-5"><p className="text-[10px] font-black uppercase tracking-wider text-rcl-blue"><FaComments className="mr-1 inline"/>Game chat</p>{user?<><div className="mt-3 max-h-56 space-y-2 overflow-y-auto">{chat.length?chat.map(item=><div key={item.id} className="rounded-xl bg-white/[.03] p-3"><p className="text-[10px] font-black text-rcl-blue">{item.author?.display_name??(item.author?.username?`@${item.author.username}`:'RCL Member')}</p><p className="mt-1 text-xs leading-5 text-white/70">{item.body}</p></div>):<p className="text-xs text-white/30">Start the courtside conversation.</p>}</div><div className="mt-3 flex gap-2"><input value={message} maxLength={400} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void send();}}} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/30 px-3 text-sm outline-none focus:border-rcl-blue/40" placeholder="Talk game…"/><button type="button" disabled={!message.trim()||busy==='chat'} onClick={()=>void send()} className="grid h-11 w-11 place-items-center rounded-xl bg-rcl-blue text-black disabled:opacity-40"><FaPaperPlane/></button></div></>:<p className="mt-3 text-xs leading-5 text-white/35">Sign in to join Game Night chat, react and vote.</p>}</div>
   </aside>
  </div>
 </section>;
}
