'use client';
import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
import { FaArrowRight,FaBolt,FaBrain,FaChartLine,FaClipboard,FaDumbbell,FaFilm,FaFlask,FaMedal } from 'react-icons/fa6';
import { getSupabaseClient } from '@/lib/supabase';
import { useAuth } from '@/hooks/useAuth';
type A={category:string;score:number}; type S={id:string;title:string;skill:string;duration_minutes:number;status:string;completed_at:string|null;created_at:string}; type P={program_name:string;total_sessions:number;completed_sessions:number;focus:string|null}; type N={title:string;body:string;created_at:string};
const cats=['scoring','creation','playmaking','defense','athleticism','iq'] as const;
const details:Record<string,string[]>={scoring:['Finishing','Midrange','3PT','Free Throws'],creation:['Handle','Separation','P&R','Isolation'],playmaking:['Vision','Passing','Decision Making','Tempo'],defense:['On Ball','Help Defense','Screens','Rebounding'],athleticism:['Speed','Agility','Vertical','Strength'],iq:['Shot Selection','Spacing','Reads','Awareness']};
const blank=()=>Object.fromEntries(cats.map(x=>[x,null])) as Record<string,number|null>;
export function LabDashboard({onBuild}:{onBuild:()=>void}){
 const {user,profile,loading}=useAuth(),supabase=useMemo(()=>getSupabaseClient(),[]),db=supabase as any; const [sessions,setSessions]=useState<S[]>([]),[program,setProgram]=useState<P|null>(null),[scores,setScores]=useState<Record<string,number|null>>(blank),[note,setNote]=useState<N|null>(null);
 useEffect(()=>{if(loading||!user||!db)return;let live=true;(async()=>{const [a,b,c,d]=await Promise.all([db.from('lab_sessions').select('id,title,skill,duration_minutes,status,completed_at,created_at').eq('profile_id',user.id).order('created_at',{ascending:false}).limit(20),db.from('lab_program_enrollments').select('program_name,total_sessions,completed_sessions,focus').eq('profile_id',user.id).eq('status','active').limit(1).maybeSingle(),db.from('lab_assessments').select('category,score').eq('profile_id',user.id).order('assessed_at',{ascending:false}),db.from('lab_notebook_entries').select('title,body,created_at').eq('profile_id',user.id).order('created_at',{ascending:false}).limit(1).maybeSingle()]);if(!live)return;setSessions((a.data||[]) as S[]);setProgram((b.data||null) as P|null);setNote((d.data||null) as N|null);const n=blank();for(const x of (c.data||[]) as A[])if(n[x.category]===null)n[x.category]=x.score;setScores(n)})();return()=>{live=false}},[loading,user,db]);
 const completed=sessions.filter(x=>x.status==='completed'),vals=Object.values(scores).filter((x):x is number=>typeof x==='number'),labScore=vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):null,pct=program?Math.min(100,Math.round(program.completed_sessions/program.total_sessions*100)):0,today=sessions.find(x=>x.status!=='completed');
 return <div className="labdash">
  <section className="labdash-hero"><div><small>RICH CITY LEAGUE // PLAYER DEVELOPMENT</small><h1>THE<br/>LAB<span>.</span></h1><b>REAL WORK. REAL DEVELOPMENT. REAL RESULTS.</b></div><strong>BETTER<br/>PLAYERS.<br/>A BRIGHTER<br/>RICHMOND.</strong></section>
  <section className="labdash-identity"><article className="labdash-player"><div className="labdash-avatar">{profile?.avatar_url?<img src={profile.avatar_url} alt=""/>:<span>{(profile?.display_name||'R').slice(0,1)}</span>}</div><div><h2>{profile?.display_name||'Your Lab'}</h2><p>{user?'PLAYER DEVELOPMENT CENTER':'SIGN IN TO PERSONALIZE THE LAB'}</p></div></article><article className="labdash-score"><small>LAB SCORE</small><b>{labScore??'—'}</b><div><i style={{width:String(labScore??0)+'%'}}/></div><p>{labScore===null?'Complete assessments to establish your baseline.':'Latest development baseline.'}</p></article><article className="labdash-stats"><span><FaBolt/><b>{completed.length}</b><small>Sessions</small></span><span><FaChartLine/><b>{program?String(pct)+'%':'—'}</b><small>Program</small></span><span><FaMedal/><b>{vals.length}/6</b><small>Assessed</small></span></article></section>
  <section className="labdash-row"><article className="labdash-today"><header><h3>TODAY IN THE LAB</h3><button onClick={onBuild}>Build session</button></header><div><FaDumbbell/><span><b>{today?.title||'Build your next session'}</b><small>{today?today.skill+' · '+today.duration_minutes+' MIN':'Choose your focus, time and equipment.'}</small></span><button onClick={onBuild}>START <FaArrowRight/></button></div></article><article className="labdash-program"><small>CURRENT PROGRAM</small><h3>{program?.program_name||'No active program'}</h3><p>{program?.focus||'Structured programs keep development connected session to session.'}</p><div><i style={{width:String(pct)+'%'}}/></div><b>{program?program.completed_sessions+' / '+program.total_sessions+' sessions':'Choose a program to begin'}</b></article></section>
  <section className="labdash-development"><header><div><h3>DEVELOPMENT MAP</h3><p>Your measurable basketball-development baseline.</p></div><Link href="/lab/player-lab">Full breakdown <FaArrowRight/></Link></header><div className="labdash-map">{cats.map(cat=><article key={cat}><h4>{cat}</h4><div className="labdash-ring" style={{'--score':String(scores[cat]??0)+'%'} as React.CSSProperties}><b>{scores[cat]??'—'}</b></div><ul>{details[cat].map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></section>
  <section className="labdash-tools"><Tool icon={<FaFlask/>} title="LAB TESTING" body="Establish measurable baselines for shooting, handle, finishing, athleticism and IQ." href="/lab/player-lab" action="View assessments"/><Tool icon={<FaBrain/>} title="AI COACH" body="Turn goals and game context into focused basketball work." href="/game-iq" action="Open AI Coach"/><Tool icon={<FaFilm/>} title="FILM ROOM" body="Study possessions, decisions and spacing, then apply the lesson." href="/lab/film-room" action="Open Film Room"/><Tool icon={<FaBolt/>} title="CHALLENGES" body="Compete against measurable targets without fake ratings." href="/lab/challenges" action="View challenges"/><Tool icon={<FaMedal/>} title="ACHIEVEMENTS" body="Track verified milestones across your RCL journey." href="/lab/badges" action="View badges"/><article className="labdash-tool notebook"><FaClipboard/><h3>MY NOTEBOOK</h3>{note?<><b>{note.title}</b><p>{note.body}</p><small>{new Date(note.created_at).toLocaleDateString()}</small></>:<p>Private development notes, reflections and coach-connected work live here.</p>}<Link href="/lab/player-lab">Open notebook <FaArrowRight/></Link></article></section>
 </div>
}
function Tool({icon,title,body,href,action}:{icon:React.ReactNode;title:string;body:string;href:string;action:string}){return <article className="labdash-tool">{icon}<h3>{title}</h3><p>{body}</p><Link href={href}>{action} <FaArrowRight/></Link></article>}
