'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import type { Badge, Game, PlayerGameStats, PublicPlayer, PublicPlayerIQ, Roster, Season, Standing, Team, TeamSeason, UserLevel } from '@/types/database';
import { Container } from '@/components/Container';

type Category = 'players' | 'teams' | 'xp' | 'badges' | 'streaks';
type Props = {
  seasons: Season[]; players: PublicPlayer[]; games: Pick<Game, 'id' | 'season_id' | 'status' | 'home_score' | 'away_score'>[];
  stats: PlayerGameStats[]; teams: Team[]; rosters: Pick<Roster, 'id' | 'player_id' | 'team_season_id'>[];
  teamSeasons: TeamSeason[]; standings: Standing[]; iq: PublicPlayerIQ[]; badges: Badge[];
  playerBadges: Pick<DatabasePlayerBadge, 'id' | 'player_id' | 'badge_id' | 'earned_at'>[]; community: Pick<UserLevel, 'profile_id' | 'xp' | 'level' | 'current_streak'>[];
};
type DatabasePlayerBadge = { id: string; player_id: string; badge_id: string; earned_at: string };
type PlayerRow = PublicPlayer & { gp: number; ppg: number; rpg: number; apg: number; spg: number; bpg: number; fg: number; ovr: number | null; iq: number | null; team: Team | null; badgeCount: number };

const statOptions = [
  ['points', 'POINTS'], ['ppg', 'PPG'], ['rebounds', 'REBOUNDS'], ['rpg', 'RPG'], ['assists', 'ASSISTS'], ['apg', 'APG'],
  ['steals', 'STEALS'], ['blocks', 'BLOCKS'], ['fg', 'FG%'], ['ovr', 'OVR'], ['iq', 'PLAYER IQ'],
] as const;

export default function LeaderboardExperience(props: Props) {
  const [category, setCategory] = useState<Category>('players');
  const [seasonId, setSeasonId] = useState('all');
  const [sort, setSort] = useState<(typeof statOptions)[number][0]>('ppg');
  const seasonGames = useMemo(() => new Set(props.games.filter((game) => seasonId === 'all' || game.season_id === seasonId).map((game) => game.id)), [props.games, seasonId]);
  const players = useMemo<PlayerRow[]>(() => {
    const iqMap = new Map(props.iq.map((item) => [item.player_id, item]));
    const badgeCounts = new Map<string, number>();
    props.playerBadges.forEach((item) => badgeCounts.set(item.player_id, (badgeCounts.get(item.player_id) ?? 0) + 1));
    const teamSeasonMap = new Map(props.teamSeasons.map((item) => [item.id, item]));
    const teamMap = new Map(props.teams.map((item) => [item.id, item]));
    const rosterTeam = new Map(props.rosters.map((item) => [item.player_id, teamMap.get(teamSeasonMap.get(item.team_season_id)?.team_id ?? '') ?? null]));
    const statsByPlayer = new Map<string, PlayerGameStats[]>();
    props.stats.filter((stat) => seasonGames.has(stat.game_id)).forEach((stat) => statsByPlayer.set(stat.player_id, [...(statsByPlayer.get(stat.player_id) ?? []), stat]));
    return props.players.map((player) => {
      const playerStats = statsByPlayer.get(player.id) ?? [];
      const average = (key: keyof PlayerGameStats) => playerStats.length ? playerStats.reduce((total, stat) => total + Number(stat[key] ?? 0), 0) / playerStats.length : 0;
      const iqRecord = iqMap.get(player.id);
      const fgAttempts = playerStats.reduce((total, stat) => total + stat.field_goals_attempted, 0);
      const fgMade = playerStats.reduce((total, stat) => total + stat.field_goals_made, 0);
      return { ...player, gp: playerStats.length, ppg: average('points'), rpg: average('rebounds'), apg: average('assists'), spg: average('steals'), bpg: average('blocks'), fg: fgAttempts ? (fgMade / fgAttempts) * 100 : 0, ovr: iqRecord?.rcl_rating ?? null, iq: iqRecord?.rcl_rating ?? null, team: rosterTeam.get(player.id) ?? null, badgeCount: badgeCounts.get(player.id) ?? 0 };
    }).filter((player) => player.gp > 0 || player.ovr !== null || player.badgeCount > 0);
  }, [props, seasonGames]);
  const sortedPlayers = useMemo(() => [...players].sort((a, b) => Number(b[sort as keyof PlayerRow] ?? -1) - Number(a[sort as keyof PlayerRow] ?? -1) || a.last_name.localeCompare(b.last_name)), [players, sort]);
  const currentSeason = props.seasons.find((season) => season.status === 'active') ?? props.seasons[0];
  const categories: { id: Category; label: string; available: boolean }[] = [
    { id: 'players', label: 'PLAYERS', available: players.length > 0 },
    { id: 'teams', label: 'TEAMS', available: props.standings.length > 0 },
    { id: 'xp', label: 'XP', available: props.community.length > 0 },
    { id: 'badges', label: 'BADGES', available: props.playerBadges.length > 0 },
    { id: 'streaks', label: 'STREAKS', available: props.community.some((item) => item.current_streak > 0) },
  ];

  return <Container maxWidth="xl" className="pt-8">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
      <div><p className="text-xs font-black uppercase tracking-[0.25em] text-rcl-gold">Stats · Competition · Community</p><h2 className="mt-2 font-display text-3xl font-black uppercase">Find the impact</h2></div>
      <label className="flex items-center gap-3 text-xs font-black uppercase tracking-widest text-gray-400">Season
        <select value={seasonId} onChange={(event) => setSeasonId(event.target.value)} className="rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-white outline-none focus:border-rcl-gold"><option value="all">ALL TIME</option>{props.seasons.map((season) => <option key={season.id} value={season.id}>{season.name}{season.id === currentSeason?.id ? ' · CURRENT' : ''}</option>)}</select>
      </label>
    </div>
    <nav aria-label="Leaderboard categories" className="mt-8 flex gap-2 overflow-x-auto border-b border-white/10 pb-px">{categories.filter((item) => item.available).map((item) => <button key={item.id} type="button" onClick={() => setCategory(item.id)} aria-current={category === item.id ? 'page' : undefined} className={`shrink-0 border-b-2 px-4 py-3 text-xs font-black tracking-widest transition ${category === item.id ? 'border-rcl-gold text-rcl-gold' : 'border-transparent text-gray-500 hover:text-white'}`}>{item.label}</button>)}</nav>
    <div className="mt-8">{category === 'players' && <PlayerLeaderboard players={sortedPlayers} sort={sort} setSort={setSort} />} {category === 'teams' && <TeamLeaderboard standings={props.standings.filter((item) => seasonId === 'all' || item.season_id === seasonId)} teams={props.teams} />} {category === 'xp' && <CommunityLeaderboard rows={props.community} title="COMMUNITY XP" value={(row) => `${row.xp.toLocaleString()} XP`} />} {category === 'streaks' && <CommunityLeaderboard rows={props.community.filter((row) => row.current_streak > 0)} title="COMMUNITY STREAKS" value={(row) => `${row.current_streak} DAYS`} />} {category === 'badges' && <BadgeLeaderboard players={players} badges={props.badges} playerBadges={props.playerBadges} />}</div>
    <section className="mt-16 grid gap-6 md:grid-cols-2"><div className="rounded-2xl border border-rcl-gold/20 bg-rcl-gold/5 p-7"><p className="text-xs font-black tracking-[0.25em] text-rcl-gold">COMMUNITY SPOTLIGHT</p><h2 className="mt-3 font-display text-2xl font-black uppercase">More than stats. A stronger community.</h2><p className="mt-3 text-sm leading-6 text-gray-300">RCL recognizes performance, participation, leadership, community, and competition — on the court and across Richmond.</p><Link href="/social" className="mt-5 inline-block text-xs font-black tracking-widest text-rcl-gold hover:text-white">JOIN THE CONVERSATION →</Link></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-7"><p className="text-xs font-black tracking-[0.25em] text-rcl-gold">CLIMB THE RANKS</p><h2 className="mt-3 font-display text-2xl font-black uppercase">Earn XP. Get recognized.</h2><p className="mt-3 text-sm leading-6 text-gray-300">Legitimate league participation and community activity build your RCL journey. Keep showing up and make an impact.</p><Link href="/profile" className="mt-5 inline-block text-xs font-black tracking-widest text-rcl-gold hover:text-white">HOW XP WORKS →</Link></div></section>
  </Container>;
}

function PlayerLeaderboard({ players, sort, setSort }: { players: PlayerRow[]; sort: string; setSort: (value: (typeof statOptions)[number][0]) => void }) {
  return <section aria-labelledby="player-leaderboard"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black tracking-[0.25em] text-rcl-gold">Official game stats</p><h2 id="player-leaderboard" className="mt-2 font-display text-2xl font-black uppercase">Player leaderboard</h2><p className="mt-2 text-sm text-gray-500">Top performers. Real games. Real skill. Real recognition.</p></div><label className="text-xs font-black uppercase tracking-widest text-gray-500">Sorted by <select value={sort} onChange={(event) => setSort(event.target.value as (typeof statOptions)[number][0])} className="ml-2 rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-white"><option value="ppg">PPG</option>{statOptions.filter(([value]) => value !== 'ppg').map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>{players.length === 0 ? <EmptyState title="NO OFFICIAL STATS YET" body="RCL leaderboards will populate as official games are recorded." /> : <div className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.025]"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-white/10 text-[10px] font-black tracking-widest text-gray-500"><tr>{['RANK', 'PLAYER', 'TEAM', 'GP', 'PPG', 'RPG', 'APG', 'OVR'].map((heading) => <th key={heading} className="px-5 py-4">{heading}</th>)}</tr></thead><tbody>{players.map((player, index) => <PlayerRow key={player.id} player={player} rank={index + 1} />)}</tbody></table></div><div className="divide-y divide-white/10 md:hidden">{players.map((player, index) => <PlayerCard key={player.id} player={player} rank={index + 1} />)}</div></div>}</section>;
}

function PlayerRow({ player, rank }: { player: PlayerRow; rank: number }) { return <tr className="border-b border-white/5 transition last:border-0 hover:bg-white/[0.04]"><td className="px-5 py-5 font-display text-xl font-black text-rcl-gold">#{rank}</td><td className="px-5 py-5"><Link href={`/players/${player.id}`} className="font-black hover:text-rcl-gold">{player.first_name} {player.last_name}</Link><span className="ml-2 text-xs text-gray-500">{player.position ?? '—'}</span></td><td className="px-5 py-5 text-sm text-gray-400">{player.team ? <Link href={`/teams/${player.team.slug}`} className="hover:text-rcl-gold">{player.team.name}</Link> : '—'}</td><td className="px-5 py-5 text-sm">{player.gp}</td><td className="px-5 py-5 font-black text-rcl-gold">{player.ppg.toFixed(1)}</td><td className="px-5 py-5">{player.rpg.toFixed(1)}</td><td className="px-5 py-5">{player.apg.toFixed(1)}</td><td className="px-5 py-5 font-black">{player.ovr ?? '—'}</td></tr>; }
function PlayerCard({ player, rank }: { player: PlayerRow; rank: number }) { return <Link href={`/players/${player.id}`} className="block p-4 hover:bg-white/[0.04]"><div className="flex items-center gap-3"><span className="font-display text-xl font-black text-rcl-gold">#{rank}</span><div className="min-w-0 flex-1"><p className="truncate font-black">{player.first_name} {player.last_name}</p><p className="truncate text-xs text-gray-500">{player.team?.name ?? 'Team pending'} · {player.position ?? 'Position pending'}</p></div><div className="text-right"><p className="font-black text-rcl-gold">{player.ppg.toFixed(1)} <span className="text-[10px]">PPG</span></p><p className="text-xs text-gray-500">{player.gp} GP · OVR {player.ovr ?? '—'}</p></div></div></Link>; }

function TeamLeaderboard({ standings, teams }: { standings: Standing[]; teams: Team[] }) { const teamMap = new Map(teams.map((team) => [team.id, team])); return <section><p className="text-xs font-black tracking-[0.25em] text-rcl-gold">Official standings</p><h2 className="mt-2 font-display text-2xl font-black uppercase">Team leaderboard</h2>{standings.length === 0 ? <EmptyState title="NO TEAM RECORDS YET" body="Team rankings will appear after official game results are recorded." /> : <div className="mt-6 overflow-x-auto rounded-2xl border border-white/10 bg-white/[0.025]"><table className="w-full min-w-[620px] text-left"><thead className="border-b border-white/10 text-[10px] font-black tracking-widest text-gray-500"><tr>{['RANK', 'TEAM', 'W', 'L', 'WIN %', 'PF', 'PA', 'STREAK'].map((heading) => <th key={heading} className="px-5 py-4">{heading}</th>)}</tr></thead><tbody>{standings.map((standing, index) => { const team = teamMap.get(standing.team_id); const games = standing.wins + standing.losses + standing.ties; return <tr key={standing.id} className="border-b border-white/5 last:border-0"><td className="px-5 py-5 font-display text-xl font-black text-rcl-gold">#{standing.rank ?? index + 1}</td><td className="px-5 py-5 font-black">{team ? <Link href={`/teams/${team.slug}`} className="hover:text-rcl-gold">{team.name}</Link> : 'Team unavailable'}</td><td className="px-5 py-5 font-black text-rcl-gold">{standing.wins}</td><td className="px-5 py-5">{standing.losses}</td><td className="px-5 py-5">{games ? `${Math.round((standing.wins / games) * 100)}%` : '—'}</td><td className="px-5 py-5">{standing.points_for}</td><td className="px-5 py-5">{standing.points_against}</td><td className="px-5 py-5 text-gray-400">{standing.streak ?? '—'}</td></tr>; })}</tbody></table></div>}</section>; }
function CommunityLeaderboard({ rows, title, value }: { rows: Pick<UserLevel, 'profile_id' | 'xp' | 'level' | 'current_streak'>[]; title: string; value: (row: Pick<UserLevel, 'profile_id' | 'xp' | 'level' | 'current_streak'>) => string }) { const sorted = [...rows].sort((a, b) => b.xp - a.xp); return <section><p className="text-xs font-black tracking-[0.25em] text-rcl-gold">Verified community activity</p><h2 className="mt-2 font-display text-2xl font-black uppercase">{title}</h2>{sorted.length === 0 ? <EmptyState title="NO COMMUNITY XP DATA YET" body="Community rankings will appear as members participate in RCL." /> : <div className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.025]">{sorted.map((row, index) => <div key={row.profile_id} className="flex items-center gap-4 border-b border-white/10 p-5 last:border-0"><span className="font-display text-xl font-black text-rcl-gold">#{index + 1}</span><div className="flex-1"><p className="font-black">RCL community member</p><p className="text-xs uppercase tracking-widest text-gray-500">LEVEL {row.level}</p></div><span className="font-black">{value(row)}</span></div>)}</div>}</section>; }
function BadgeLeaderboard({ players, badges, playerBadges }: { players: PlayerRow[]; badges: Badge[]; playerBadges: DatabasePlayerBadge[] }) { const badgeMap = new Map(badges.map((badge) => [badge.id, badge])); const rows = players.filter((player) => player.badgeCount > 0).sort((a, b) => b.badgeCount - a.badgeCount); return <section><p className="text-xs font-black tracking-[0.25em] text-rcl-gold">Verified achievements</p><h2 className="mt-2 font-display text-2xl font-black uppercase">Badges leaderboard</h2>{rows.length === 0 ? <EmptyState title="NO BADGES YET" body="Badge rankings will appear as RCL achievements are earned." /> : <div className="mt-6 grid gap-3 md:grid-cols-2">{rows.map((player, index) => { const earned = playerBadges.filter((item) => item.player_id === player.id); const highest = earned.map((item) => badgeMap.get(item.badge_id)?.tier).filter(Boolean).pop(); return <Link href={`/players/${player.id}`} key={player.id} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[0.025] p-5 hover:border-rcl-gold/50"><span className="font-display text-xl font-black text-rcl-gold">#{index + 1}</span><div className="flex-1"><p className="font-black">{player.first_name} {player.last_name}</p><p className="text-xs uppercase tracking-widest text-gray-500">{highest ?? 'earned'} tier</p></div><span className="font-black">{player.badgeCount} <span className="text-xs text-gray-500">BADGES</span></span></Link>; })}</div>}</section>; }
function EmptyState({ title, body }: { title: string; body: string }) { return <div className="mt-6 rounded-2xl border border-dashed border-white/15 bg-white/[0.02] px-6 py-12 text-center"><p className="font-display text-lg font-black tracking-widest text-rcl-gold">{title}</p><p className="mx-auto mt-3 max-w-md text-sm text-gray-500">{body}</p></div>; }
