'use client';

import Image from 'next/image';
import Link from 'next/link';
import type { ReactNode } from 'react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { FaArrowRight, FaAward, FaChartLine, FaCircleCheck, FaDumbbell, FaFilm, FaMedal, FaPeopleGroup, FaTrophy } from 'react-icons/fa6';
import { Container } from '@/components/Container';
import { getSupabaseClient } from '@/lib/supabase';

type Passport={player_id:string;profile_id:string|null;first_name:string;last_name:string;jersey_number:number|null;position:string|null;height_inches:number|null;hometown:string|null;photo_url:string|null;is_active:boolean;rcl_rating:number;player_archetype:string|null;games_played:number;ppg:number|null;rpg:number|null;apg:number|null;spg:number|null;bpg:number|null;true_shooting_pct:number|null;assist_turnover_ratio:number|null;avg_plus_minus:number|null;badge_count:number;award_count:number;seasons_played:number;highlight_count:number;lab_sessions_completed:number};
type Rep={total_xp:number;level:number;status_label:string;hooper_xp:number;community_xp:number;creator_xp:number;coach_xp:number;reliability_xp:number};
type Reliability={runs_joined:number;verified_checkins:number;reliability_pct:number|null};
type Highlight={id:string;title:string;category:string;clip_url:string|null;featured:boolean;game_id:string|null};
type History={rcl_rating:number;calculated_at:string};
type Award={id:string;name:string;description:string|null;season_id:string|null;awarded_at:string|null};
type SpecialCard={id:string;edition:string;title:string|null;overall_rating:number;card_payload:Record<string,unknown>;issued_at:string};
type LiveCard={overall_rating:number;archetype:string};
const repRows=[['Hooper','hooper_xp'],['Community','community_xp'],['Creator','creator_xp'],['Coach','coach_xp'],['Reliability','reliability_xp']] as const;
const fmt=(v:number|null|undefined,d=1)=>v===null||v===undefined?'—':Number(v).toFixed(d);

export function PlayerPassportV2({playerId}:{playerId:string}){
 const supabase=useMemo(()=>getSupabaseClient(true),[]);const db=supabase as any;
 const [passport,setPassport]=useState<Passport|null>(null);const [rep,setRep]=useState<Rep|null>(null);const [reliability,setReliability]=useState<Reliability|null>(null);const [highlights,setHighlights]=useState<Highlight[]>([]);const [history,setHistory]=useState<History[]>([]);const [awards,setAwards]=useState<Award[]>([]);const [specialCards,setSpecialCards]=useState<SpecialCard[]>([]);const [liveCard,setLiveCard]=useState<LiveCard|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=useCallback(async()=>{if(!db){setLoading(false);return;}setLoading(true);setError('');const {data:passportData,error:passportError}=await db.from('player_passports').select('*').eq('player_id',playerId).maybeSingle();if(passportError){setError(passportError.message);setLoading(false);return;}const row=(passportData??null) as Passport|null;setPassport(row);if(!row){setLoading(false);return;}const [h,cards,hist,awardsResult,repResult,reliabilityResult,live]=await Promise.all([
   db.from('player_highlights').select('id,title,category,clip_url,featured,game_id').eq('player_id',playerId).eq('status','published').order('featured',{ascending:false}).order('created_at',{ascending:false}).limit(18),
   db.from('player_cards').select('id,edition,title,overall_rating,card_payload,issued_at').eq('player_id',playerId).order('issued_at',{ascending:false}).limit(12),
   db.from('player_iq_history').select('rcl_rating,calculated_at').eq('player_id',playerId).order('calculated_at',{ascending:true}).limit(24),
   db.from('awards').select('id,name,description,season_id,awarded_at').eq('player_id',playerId).order('awarded_at',{ascending:false}).limit(20),
   row.profile_id?db.from('rep_dimension_summary').select('*').eq('profile_id',row.profile_id).maybeSingle():Promise.resolve({data:null}),
   row.profile_id?db.from('run_reliability').select('runs_joined,verified_checkins,reliability_pct').eq('profile_id',row.profile_id).maybeSingle():Promise.resolve({data:null}),
   db.from('player_card_live').select('overall_rating,archetype').eq('player_id',playerId).maybeSingle(),
  ]);setHighlights((h.data??[]) as Highlight[]);setSpecialCards((cards.data??[]) as SpecialCard[]);setHistory((hist.data??[]) as History[]);setAwards((awardsResult.data??[]) as Award[]);setRep((repResult.data??null) as Rep|null);setReliability((reliabilityResult.data??null) as Reliability|null);setLiveCard((live.data??null) as LiveCard|null);setLoading(false);},[db,playerId]);
 useEffect(()=>{void load();},[load]);
 if(loading)return <main className="min-h-screen bg-[#03070d] p-8 text-white"><Container maxWidth="xl"><div className="h-[70vh] animate-pulse rounded-3xl border border-white/10 bg-white/[.02]"/></Container></main>;
 if(!passport)return <main className="min-h-screen bg-[#03070d] p-8 text-white"><Container maxWidth="lg"><div className="rounded-3xl border border-white/10 p-10 text-center"><h1 className="font-display text-3xl font-black uppercase">Passport unavailable</h1><p className="mt-3 text-sm text-white/40">{error||'This player does not have an RCL Basketball Passport yet.'}</p></div></Container></main>;
 const name=`${passport.first_name} ${passport.last_name}`;const latest=history.length?history[history.length-1].rcl_rating:passport.rcl_rating;const first=history[0]?.rcl_rating??latest;const delta=Number(latest)-Number(first);const maxRep=rep?Math.max(rep.hooper_xp,rep.community_xp,rep.creator_xp,rep.coach_xp,rep.reliability_xp,1):1;
 return <main className="min-h-screen bg-[#03070d] pb-28 text-white">
  <section className="border-b border-white/10 bg-[radial-gradient(circle_at_78%_10%,rgba(249,115,22,.18),transparent_34%),radial-gradient(circle_at_15%_35%,rgba(26,155,220,.15),transparent_36%),#050a10] py-12"><Container maxWidth="xl"><div className="grid gap-7 lg:grid-cols-[1fr_auto] lg:items-end"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="relative h-36 w-36 shrink-0 overflow-hidden rounded-3xl border-2 border-rcl-orange/50 bg-black/35">{passport.photo_url?<Image src={passport.photo_url} alt={name} fill sizes="144px" className="object-cover"/>:<div className="grid h-full place-items-center font-display text-5xl font-black text-rcl-orange">{passport.first_name[0]}{passport.last_name[0]}</div>}</div><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-rcl-blue">RCL Basketball Passport · Verified identity</p><h1 className="mt-2 font-display text-4xl font-black uppercase sm:text-6xl">{passport.first_name} <span className="text-rcl-orange">{passport.last_name}</span></h1><p className="mt-3 text-sm text-white/45">{passport.position??'RCL Player'} · {passport.height_inches?`${Math.floor(passport.height_inches/12)}'${passport.height_inches%12}\"`:'Height N/A'} · {passport.hometown??'Richmond, VA'}</p><div className="mt-5 flex gap-2"><Link href={`/players/${playerId}`} className="rounded-xl border border-white/15 px-4 py-2.5 text-[10px] font-black uppercase">Public profile</Link><Link href={`/players/compare?left=${playerId}`} className="rounded-xl bg-rcl-orange px-4 py-2.5 text-[10px] font-black uppercase text-black">Compare</Link></div></div></div><div className="rounded-3xl border border-rcl-orange/25 bg-black/35 p-6 text-center"><p className="text-[10px] font-black uppercase tracking-[.22em] text-rcl-orange">Live player card</p><p className="mt-2 font-display text-7xl font-black">{liveCard?.overall_rating??Math.round(passport.rcl_rating)}</p><p className="mt-1 text-xs font-black uppercase text-white/55">{liveCard?.archetype??passport.player_archetype??'RCL Hooper'}</p><p className={`mt-3 text-[10px] font-black uppercase ${delta>=0?'text-emerald-300':'text-rose-300'}`}>{delta>=0?'+':''}{delta.toFixed(1)} rating journey</p></div></div></Container></section>
  <Container maxWidth="xl" className="py-9"><section className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[['GP',passport.games_played],['PPG',fmt(passport.ppg)],['RPG',fmt(passport.rpg)],['APG',fmt(passport.apg)],['TS%',passport.true_shooting_pct===null?'—':`${fmt(passport.true_shooting_pct)}%`],['+/-',fmt(passport.avg_plus_minus)]].map(([label,value])=><Stat key={label} label={String(label)} value={String(value)}/>)}</section>
   <section className="mt-6 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><article className="rounded-3xl border border-rcl-blue/15 bg-[#071522]/45 p-6"><Heading icon={<FaMedal/>} eyebrow="REP 2.0" title="Basketball reputation"/>{rep?<><div className="mt-6 space-y-4">{repRows.map(([label,key])=><div key={key}><div className="flex justify-between text-xs font-black"><span>{label}</span><b>{rep[key]}</b></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-rcl-blue" style={{width:`${Math.max(3,Math.round(rep[key]/maxRep*100))}%`}}/></div></div>)}</div><div className="mt-5 flex items-center justify-between rounded-2xl bg-black/25 p-4"><div><p className="text-[9px] font-black uppercase text-white/30">Status</p><p className="mt-1 font-display text-xl font-black uppercase text-rcl-orange">{rep.status_label} · LVL {rep.level}</p></div><b className="font-display text-3xl">{rep.total_xp}</b></div></>:<p className="mt-5 text-sm text-white/40">No linked REP identity yet.</p>}</article><article className="rounded-3xl border border-white/10 bg-white/[.02] p-6"><Heading icon={<FaChartLine/>} eyebrow="Advanced analytics" title="Impact profile"/><div className="mt-6 grid gap-3 sm:grid-cols-3">{[['AST/TO',fmt(passport.assist_turnover_ratio,2)],['STL',fmt(passport.spg)],['BLK',fmt(passport.bpg)],['Badges',passport.badge_count],['Awards',passport.award_count],['Seasons',passport.seasons_played]].map(([label,value])=><Stat key={label} label={String(label)} value={String(value)}/>)}</div><div className="mt-5 rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex justify-between text-[10px] font-black uppercase"><span className="text-white/35">Game IQ history</span><span className="text-rcl-orange">{history.length} checkpoints</span></div><div className="mt-4 flex h-20 items-end gap-1">{history.map((point,index)=>{const values=history.map(h=>Number(h.rcl_rating));const min=Math.min(...values);const max=Math.max(...values);const height=24+((Number(point.rcl_rating)-min)/Math.max(1,max-min))*56;return <span key={`${point.calculated_at}-${index}`} className="min-w-1 flex-1 rounded-t bg-rcl-orange/65" style={{height}} title={`${new Date(point.calculated_at).toLocaleDateString()}: ${point.rcl_rating}`}/>})}</div></div></article></section>
   <section className="mt-6 grid gap-4 lg:grid-cols-3"><Info icon={<FaTrophy/>} label="Career" value={`${passport.seasons_played} seasons`} detail={`${passport.games_played} official games.`}/><Info icon={<FaDumbbell/>} label="Development" value={`${passport.lab_sessions_completed} Lab sessions`} detail="Verified completed training sessions."/><Info icon={<FaPeopleGroup/>} label="Reliability" value={reliability?.reliability_pct!==null&&reliability?.reliability_pct!==undefined?`${reliability.reliability_pct}%`:'Not rated'} detail={reliability?`${reliability.verified_checkins}/${reliability.runs_joined} joined runs verified.`:'Builds from verified run attendance.'}/></section>
   <section className="mt-6 rounded-3xl border border-rcl-orange/20 bg-rcl-orange/[.03] p-6"><Heading icon={<FaAward/>} eyebrow="Player cards" title="Special editions"/>{specialCards.length?<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{specialCards.map(card=><article key={card.id} className="relative overflow-hidden rounded-2xl border border-rcl-orange/25 bg-[radial-gradient(circle_at_top_right,rgba(249,115,22,.18),transparent_38%),#071018] p-5"><p className="text-[9px] font-black uppercase tracking-wider text-rcl-orange">{card.title??card.edition.replace(/-/g,' ')}</p><p className="mt-2 font-display text-5xl font-black">{card.overall_rating}</p><p className="mt-1 text-[10px] uppercase text-white/35">Special OVR · {new Date(card.issued_at).toLocaleDateString()}</p></article>)}</div>:<p className="mt-5 rounded-2xl border border-dashed border-white/10 p-6 text-sm text-white/35">Special editions unlock automatically from qualifying official performances.</p>}</section>
   <section className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-3xl border border-white/10 bg-[#071018] p-6"><Heading icon={<FaFilm/>} eyebrow="Highlight tape" title="Player media"/>{highlights.length?<div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{highlights.map(h=><a key={h.id} href={h.clip_url??(h.game_id?`/games/${h.game_id}`:'/media')} className="rounded-2xl border border-white/10 bg-black/25 p-4 hover:border-rcl-blue/35"><div className="grid aspect-video place-items-center rounded-xl bg-rcl-blue/[.06]"><FaFilm className="text-rcl-blue"/></div><p className="mt-3 text-[9px] font-black uppercase text-rcl-orange">{h.category.replace(/_/g,' ')}{h.featured?' · Featured':''}</p><h3 className="mt-1 text-sm font-black">{h.title}</h3></a>)}</div>:<p className="mt-5 text-sm text-white/35">Approved tagged clips will build this tape.</p>}</article><article className="rounded-3xl border border-white/10 bg-white/[.02] p-6"><Heading icon={<FaAward/>} eyebrow="Legacy" title="Awards"/>{awards.length?<div className="mt-5 space-y-3">{awards.map(a=><div key={a.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="font-black">{a.name}</p>{a.description&&<p className="mt-1 text-xs leading-5 text-white/35">{a.description}</p>}<p className="mt-2 text-[9px] uppercase text-rcl-orange">{a.awarded_at?new Date(a.awarded_at).toLocaleDateString():'RCL award'}</p></div>)}</div>:<p className="mt-5 text-sm text-white/35">Official awards stay attached across seasons.</p>}<Link href="/legacy" className="mt-5 inline-flex items-center gap-2 text-xs font-black uppercase text-rcl-orange">Legacy archive <FaArrowRight/></Link></article></section>
   <section className="mt-6 rounded-3xl border border-rcl-blue/15 bg-[#071522]/35 p-6"><div className="flex gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-rcl-blue/10 text-rcl-blue"><FaCircleCheck/></span><div><p className="text-[10px] font-black uppercase text-rcl-blue">Verified record</p><h2 className="mt-1 font-display text-xl font-black uppercase">One identity across RCL</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/40">Official scorebook stats, Game IQ, rosters, awards, tagged media, REP, The Lab and verified run attendance all feed this Passport.</p></div></div></section>
  </Container>
 </main>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-4 text-center"><p className="text-[9px] font-black uppercase tracking-wider text-white/30">{label}</p><p className="mt-2 font-display text-2xl font-black">{value}</p></div>}
function Heading({icon,eyebrow,title}:{icon:ReactNode;eyebrow:string;title:string}){return <div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-rcl-blue/10 text-rcl-blue">{icon}</span><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-blue">{eyebrow}</p><h2 className="font-display text-2xl font-black uppercase">{title}</h2></div></div>}
function Info({icon,label,value,detail}:{icon:ReactNode;label:string;value:string;detail:string}){return <article className="rounded-3xl border border-white/10 bg-white/[.02] p-5"><span className="text-rcl-orange">{icon}</span><p className="mt-3 text-[9px] font-black uppercase text-white/30">{label}</p><p className="mt-1 font-display text-2xl font-black uppercase">{value}</p><p className="mt-2 text-xs leading-5 text-white/35">{detail}</p></article>}
