'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { FaArrowRight, FaAward, FaBasketball, FaBolt, FaChartLine, FaCircleCheck, FaDumbbell, FaFilm, FaMedal, FaPeopleGroup, FaTrophy } from 'react-icons/fa6';
import { Container } from '@/components/Container';
import { getSupabaseClient } from '@/lib/supabase';

type Passport={player_id:string;profile_id:string|null;first_name:string;last_name:string;jersey_number:number|null;position:string|null;height_inches:number|null;hometown:string|null;photo_url:string|null;is_active:boolean;rcl_rating:number;player_archetype:string|null;rating_trend:string|null;games_played:number;ppg:number|null;rpg:number|null;apg:number|null;spg:number|null;bpg:number|null;true_shooting_pct:number|null;assist_turnover_ratio:number|null;avg_plus_minus:number|null;badge_count:number;award_count:number;seasons_played:number;highlight_count:number;lab_sessions_completed:number};
type Rep={total_xp:number;level:number;status_label:string;hooper_xp:number;community_xp:number;creator_xp:number;coach_xp:number;reliability_xp:number};
type Reliability={runs_joined:number;verified_checkins:number;reliability_pct:number|null};
type Highlight={id:string;title:string;category:string;clip_url:string|null;thumbnail_url:string|null;featured:boolean;created_at:string;game_id:string|null};
type Card={overall_rating:number;archetype:string;ppg:number|null;rpg:number|null;apg:number|null;spg:number|null;bpg:number|null;badge_count:number;award_count:number;seasons_played:number};
type History={rcl_rating:number;calculated_at:string;rating_change:number|null};
type Award={id:string;title:string;award_type:string;description:string|null;season_id:string|null;awarded_at:string|null};

const repRows=[['Hooper','hooper_xp'],['Community','community_xp'],['Creator','creator_xp'],['Coach','coach_xp'],['Reliability','reliability_xp']] as const;
function n(value:number|null|undefined,digits=1){return value===null||value===undefined?'—':Number(value).toFixed(digits);}

export function PlayerPassportExperience({playerId}:{playerId:string}){
 const supabase=useMemo(()=>getSupabaseClient(true),[]); const db=supabase as any;
 const [passport,setPassport]=useState<Passport|null>(null);const [rep,setRep]=useState<Rep|null>(null);const [reliability,setReliability]=useState<Reliability|null>(null);const [highlights,setHighlights]=useState<Highlight[]>([]);const [card,setCard]=useState<Card|null>(null);const [history,setHistory]=useState<History[]>([]);const [awards,setAwards]=useState<Award[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=useCallback(async()=>{if(!db){setLoading(false);return;}setLoading(true);setError('');const passportResult=await db.from('player_passports').select('*').eq('player_id',playerId).maybeSingle();if(passportResult.error){setError('Basketball Passport could not be loaded.');setLoading(false);return;}const row=(passportResult.data??null) as Passport|null;setPassport(row);if(!row){setLoading(false);return;}const [highlightResult,cardResult,historyResult,awardResult,repResult,reliabilityResult]=await Promise.all([
   db.from('player_highlights').select('id,title,category,clip_url,thumbnail_url,featured,created_at,game_id').eq('player_id',playerId).eq('status','published').order('featured',{ascending:false}).order('created_at',{ascending:false}).limit(18),
   db.from('player_card_live').select('*').eq('player_id',playerId).maybeSingle(),
   db.from('player_iq_history').select('rcl_rating,calculated_at,rating_change').eq('player_id',playerId).order('calculated_at',{ascending:true}).limit(24),
   db.from('awards').select('id,title,award_type,description,season_id,awarded_at').eq('player_id',playerId).order('awarded_at',{ascending:false}).limit(20),
   row.profile_id?db.from('rep_dimension_summary').select('*').eq('profile_id',row.profile_id).maybeSingle():Promise.resolve({data:null}),
   row.profile_id?db.from('run_reliability').select('runs_joined,verified_checkins,reliability_pct').eq('profile_id',row.profile_id).maybeSingle():Promise.resolve({data:null}),
  ]);setHighlights((highlightResult.data??[]) as Highlight[]);setCard((cardResult.data??null) as Card|null);setHistory((historyResult.data??[]) as History[]);setAwards((awardResult.data??[]) as Award[]);setRep((repResult.data??null) as Rep|null);setReliability((reliabilityResult.data??null) as Reliability|null);setLoading(false);},[db,playerId]);
 useEffect(()=>{void load();},[load]);
 if(loading)return <main className="min-h-screen bg-[#03070d] p-8 text-white"><Container maxWidth="xl"><div className="h-[70vh] animate-pulse rounded-3xl border border-white/10 bg-white/[.02]"/></Container></main>;
 if(!passport)return <main className="min-h-screen bg-[#03070d] p-8 text-white"><Container maxWidth="lg"><div className="rounded-3xl border border-white/10 p-10 text-center"><h1 className="font-display text-3xl font-black uppercase">Passport unavailable</h1><p className="mt-3 text-sm text-white/40">{error||'This player does not have an RCL Basketball Passport yet.'}</p><Link href={`/players/${playerId}`} className="mt-5 inline-flex items-center gap-2 text-xs font-black uppercase text-rcl-blue">Back to profile <FaArrowRight/></Link></div></Container></main>;
 const name=`${passport.first_name} ${passport.last_name}`;const maxRep=rep?Math.max(rep.hooper_xp,rep.community_xp,rep.creator_xp,rep.coach_xp,rep.reliability_xp,1):1;const latestRating=history.at(-1)?.rcl_rating??passport.rcl_rating;const firstRating=history[0]?.rcl_rating??latestRating;const ratingDelta=latestRating-firstRating;
 return <main className="min-h-screen bg-[#03070d] pb-28 text-white">
  <section className="relative overflow-hidden border-b border-white/10 bg-[radial-gradient(circle_at_78%_10%,rgba(249,115,22,.18),transparent_34%),radial-gradient(circle_at_15%_35%,rgba(26,155,220,.15),transparent_36%),#050a10] py-12 sm:py-16"><Container maxWidth="xl"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><div className="relative h-36 w-36 shrink-0 overflow-hidden rounded-3xl border-2 border-rcl-orange/50 bg-black/35 shadow-2xl">{passport.photo_url?<Image src={passport.photo_url} alt={name} fill sizes="144px" className="object-cover"/>:<div className="grid h-full place-items-center font-display text-5xl font-black text-rcl-orange">{passport.first_name[0]}{passport.last_name[0]}</div>}</div><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-rcl-blue">RCL Basketball Passport · Verified Identity</p><h1 className="mt-2 font-display text-4xl font-black uppercase sm:text-6xl">{passport.first_name} <span className="text-rcl-orange">{passport.last_name}</span></h1><p className="mt-3 text-sm text-white/45">{passport.position??'RCL Player'} · {passport.height_inches?`${Math.floor(passport.height_inches/12)}'${passport.height_inches%12}\"`:'Height N/A'} · {passport.hometown??'Richmond, VA'} · {passport.is_active?'Active':'Alumni'}</p><div className="mt-5 flex flex-wrap gap-2"><Link href={`/players/${playerId}`} className="rounded-xl border border-white/15 px-4 py-2.5 text-[10px] font-black uppercase tracking-wider">Public profile</Link><Link href={`/players/compare?left=${playerId}`} className="rounded-xl bg-rcl-orange px-4 py-2.5 text-[10px] font-black uppercase tracking-wider text-black">Compare player</Link></div></div></div><div className="rounded-3xl border border-rcl-orange/25 bg-black/35 p-6 text-center backdrop-blur"><p className="text-[10px] font-black uppercase tracking-[.22em] text-rcl-orange">Live player card</p><p className="mt-2 font-display text-7xl font-black">{card?.overall_rating??Math.round(passport.rcl_rating)}</p><p className="mt-1 text-xs font-black uppercase tracking-wider text-white/55">{card?.archetype??passport.player_archetype??'RCL Hooper'}</p><p className={`mt-3 text-[10px] font-black uppercase ${ratingDelta>=0?'text-emerald-300':'text-rose-300'}`}>{ratingDelta>=0?'+':''}{ratingDelta.toFixed(1)} rating journey</p></div></div></Container></section>
  <Container maxWidth="xl" className="py-8 sm:py-12">
   <section className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[['GP',passport.games_played],['PPG',n(passport.ppg)],['RPG',n(passport.rpg)],['APG',n(passport.apg)],['TS%',passport.true_shooting_pct===null?'—':`${n(passport.true_shooting_pct)}%`],['+/-',n(passport.avg_plus_minus)]].map(([label,value])=><div key={label} className="rounded-2xl border border-white/10 bg-white/[.025] p-4 text-center"><p className="text-[9px] font-black uppercase tracking-wider text-white/30">{label}</p><p className="mt-2 font-display text-3xl font-black">{value}</p></div>)}</section>
   <section className="mt-6 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><article className="rounded-3xl border border-rcl-blue/15 bg-[#071522]/45 p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-rcl-blue/10 text-rcl-blue"><FaMedal/></span><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-blue">REP 2.0</p><h2 className="font-display text-2xl font-black uppercase">Basketball reputation</h2></div></div>{rep?<><div className="mt-6 space-y-4">{repRows.map(([label,key])=><div key={key}><div className="flex items-center justify-between"><span className="text-xs font-black">{label}</span><b className="font-display">{rep[key]}</b></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-rcl-blue" style={{width:`${Math.max(3,Math.round(rep[key]/maxRep*100))}%`}}/></div></div>)}</div><div className="mt-5 flex items-center justify-between rounded-2xl bg-black/25 p-4"><div><p className="text-[9px] font-black uppercase tracking-wider text-white/30">Overall status</p><p className="mt-1 font-display text-xl font-black uppercase text-rcl-orange">{rep.status_label} · LVL {rep.level}</p></div><b className="font-display text-3xl">{rep.total_xp}</b></div></>:<p className="mt-6 text-sm leading-6 text-white/40">This player has not linked a public REP identity yet.</p>}</article>
    <article className="rounded-3xl border border-white/10 bg-white/[.02] p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-rcl-orange/10 text-rcl-orange"><FaChartLine/></span><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-orange">Advanced analytics</p><h2 className="font-display text-2xl font-black uppercase">How this player impacts games</h2></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[['AST/TO',n(passport.assist_turnover_ratio,2)],['STL',n(passport.spg)],['BLK',n(passport.bpg)],['Badges',passport.badge_count],['Awards',passport.award_count],['Seasons',passport.seasons_played]].map(([label,value])=><div key={label} className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-[9px] font-black uppercase tracking-wider text-white/30">{label}</p><p className="mt-2 font-display text-2xl font-black">{value}</p></div>)}</div><div className="mt-5 rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex justify-between text-[10px] font-black uppercase tracking-wider"><span className="text-white/35">Rating history</span><span className="text-rcl-orange">{history.length} checkpoints</span></div><div className="mt-4 flex h-20 items-end gap-1">{history.length?history.map((point,index)=>{const min=Math.min(...history.map(h=>h.rcl_rating));const max=Math.max(...history.map(h=>h.rcl_rating));const height=24+((point.rcl_rating-min)/Math.max(1,max-min))*56;return <span key={`${point.calculated_at}-${index}`} className="min-w-1 flex-1 rounded-t bg-rcl-orange/65" style={{height}} title={`${new Date(point.calculated_at).toLocaleDateString()}: ${point.rcl_rating}`}/>;}):<span className="m-auto text-xs text-white/30">Rating history begins after Game IQ evaluations.</span>}</div></div></article></section>
   <section className="mt-6 grid gap-6 lg:grid-cols-3"><Info icon={<FaTrophy/>} label="Career" value={`${passport.seasons_played} seasons`} detail={`${passport.games_played} official games in the Passport record.`}/><Info icon={<FaDumbbell/>} label="Development" value={`${passport.lab_sessions_completed} Lab sessions`} detail="Verified completed training sessions tied to this profile."/><Info icon={<FaPeopleGroup/>} label="Reliability" value={reliability?.reliability_pct!==null&&reliability?.reliability_pct!==undefined?`${reliability.reliability_pct}%`:'Not rated'} detail={reliability?`${reliability.verified_checkins}/${reliability.runs_joined} joined runs verified by check-in.`:'Run attendance becomes a reliability signal.'}/></section>
   <section className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-3xl border border-white/10 bg-[#071018] p-6"><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-blue"><FaFilm className="mr-1 inline"/>Highlight tape</p><h2 className="mt-1 font-display text-2xl font-black uppercase">Player media</h2></div><Link href="/media" className="text-xs font-black uppercase text-rcl-blue">RCL TV</Link></div>{highlights.length?<div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{highlights.map(h=><a key={h.id} href={h.clip_url??'/media'} className="rounded-2xl border border-white/10 bg-black/25 p-4 transition hover:border-rcl-blue/35"><div className="grid aspect-video place-items-center rounded-xl bg-rcl-blue/[.06]"><FaFilm className="text-rcl-blue"/></div><p className="mt-3 text-[9px] font-black uppercase tracking-wider text-rcl-orange">{h.category.replace(/_/g,' ')}{h.featured?' · Featured':''}</p><h3 className="mt-1 text-sm font-black">{h.title}</h3></a>)}</div>:<p className="mt-5 rounded-2xl border border-dashed border-white/10 p-7 text-sm text-white/35">Tagged game clips, Top Plays, interviews and mic’d-up moments will build this player’s permanent tape.</p>}</article><article className="rounded-3xl border border-rcl-orange/20 bg-rcl-orange/[.035] p-6"><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-orange"><FaAward className="mr-1 inline"/>Legacy</p><h2 className="mt-1 font-display text-2xl font-black uppercase">Awards & achievements</h2>{awards.length?<div className="mt-5 space-y-3">{awards.map(a=><div key={a.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-[9px] font-black uppercase tracking-wider text-rcl-orange">{a.award_type.replace(/_/g,' ')}</p><p className="mt-1 font-black">{a.title}</p>{a.description&&<p className="mt-1 text-xs leading-5 text-white/35">{a.description}</p>}</div>)}</div>:<p className="mt-5 text-sm leading-6 text-white/35">Official awards and historical achievements will remain attached to the Passport across seasons.</p>}<Link href="/legacy" className="mt-5 inline-flex items-center gap-2 text-xs font-black uppercase tracking-wider text-rcl-orange">RCL legacy archive <FaArrowRight/></Link></article></section>
   <section className="mt-6 rounded-3xl border border-rcl-blue/15 bg-[#071522]/35 p-6"><div className="flex gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-rcl-blue/10 text-rcl-blue"><FaCircleCheck/></span><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-blue">Verified record</p><h2 className="mt-1 font-display text-xl font-black uppercase">One identity across RCL</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/40">The Passport is built from official scorebook stats, RCL Game IQ, season rosters, league awards, tagged media, REP activity, The Lab and verified run attendance. It is designed to grow with the player instead of resetting every season.</p></div></div></section>
  </Container>
 </main>;
}

function Info({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <article className="rounded-3xl border border-white/10 bg-white/[.02] p-5"><span className="text-rcl-orange">{icon}</span><p className="mt-3 text-[9px] font-black uppercase tracking-wider text-white/30">{label}</p><p className="mt-1 font-display text-2xl font-black uppercase">{value}</p><p className="mt-2 text-xs leading-5 text-white/35">{detail}</p></article>;}
