'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';

type TeamItem = { id: string; name: string; slug: string; logo_url: string | null; primary_color: string | null; division: string | null; season: string | null; wins: number | null; losses: number | null };
type CoachItem = { id: string; profileId: string; name: string; title: string; team: string | null; teamSlug: string | null; wins: number | null; losses: number | null };
type NewsItem = { id: string; slug: string; title: string; excerpt: string | null; category: string; publishedAt: string | null; coverImageUrl: string | null };
type MediaItem = { id: string; title: string; description: string | null; type: string; url: string; createdAt: string };

function EmptyState({ title, body }: { title: string; body: string }) {
  return <div className="rounded-2xl border border-dashed border-white/15 bg-white/[0.03] p-10 text-center"><p className="font-display text-xl font-bold text-white">{title}</p><p className="mt-2 text-sm text-gray-500">{body}</p></div>;
}

export function TeamsDirectory({ items }: { items: TeamItem[] }) {
  const [query, setQuery] = useState('');
  const [division, setDivision] = useState('ALL');
  const divisions = [...new Set(items.map((item) => item.division).filter(Boolean))] as string[];
  const filtered = useMemo(() => items.filter((item) => `${item.name} ${item.division ?? ''}`.toLowerCase().includes(query.toLowerCase()) && (division === 'ALL' || item.division === division)), [items, query, division]);
  return <div>
    <div className="mb-8 flex flex-col gap-3 sm:flex-row"><label className="flex-1"><span className="sr-only">Search teams</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search teams..." className="w-full rounded-xl border border-white/10 bg-white/[0.05] px-4 py-3 text-sm text-white outline-none focus:border-rcl-gold" /></label><select value={division} onChange={(event) => setDivision(event.target.value)} className="rounded-xl border border-white/10 bg-rcl-navy px-4 py-3 text-sm text-white outline-none"><option value="ALL">All divisions</option>{divisions.map((item) => <option key={item} value={item}>{item}</option>)}</select></div>
    {!items.length ? <EmptyState title="THE CITY IS BUILDING." body="Official RCL teams will appear here as the league roster is finalized." /> : !filtered.length ? <EmptyState title="NO TEAMS FOUND." body="Try a different team name or division." /> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((team) => <Link key={team.id} href={`/teams/${team.slug}`} className="group rounded-2xl border border-white/10 bg-white/[0.04] p-5 transition hover:-translate-y-1 hover:border-rcl-gold/60"><div className="flex items-center gap-4">{team.logo_url ? <img src={team.logo_url} alt={`${team.name} logo`} className="h-14 w-14 rounded-xl object-cover" /> : <div className="h-14 w-14 rounded-xl" style={{ backgroundColor: team.primary_color ?? '#ff6b1a' }} />}<div><h2 className="font-display text-xl font-bold group-hover:text-rcl-gold">{team.name}</h2><p className="text-xs uppercase tracking-wider text-gray-500">{team.division ?? 'Division pending'}</p></div></div><div className="mt-6 flex items-end justify-between border-t border-white/10 pt-4"><span className="text-xs uppercase text-gray-500">{team.season ?? 'Season pending'}</span><span className="font-display text-xl font-bold">{team.wins === null ? '—' : `${team.wins}–${team.losses}`}</span></div></Link>)}</div>}
  </div>;
}

export function CoachesDirectory({ items }: { items: CoachItem[] }) {
  const [query, setQuery] = useState('');
  const [role, setRole] = useState('ALL');
  const roles = [...new Set(items.map((item) => item.title).filter(Boolean))];
  const filtered = items.filter((item) => `${item.name} ${item.team ?? ''} ${item.title}`.toLowerCase().includes(query.toLowerCase()) && (role === 'ALL' || item.title === role));
  return <div><div className="mb-8 flex flex-col gap-3 sm:flex-row"><label className="flex-1"><span className="sr-only">Search coaches</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search coaches..." className="w-full rounded-xl border border-white/10 bg-white/[0.05] px-4 py-3 text-sm text-white outline-none focus:border-rcl-gold" /></label><select value={role} onChange={(event) => setRole(event.target.value)} className="rounded-xl border border-white/10 bg-rcl-navy px-4 py-3 text-sm text-white outline-none"><option value="ALL">All roles</option>{roles.map((item) => <option key={item} value={item}>{item}</option>)}</select></div>{!items.length ? <EmptyState title="THE LEADERS ARE COMING." body="Official RCL coaching profiles will appear as staff assignments are finalized." /> : !filtered.length ? <EmptyState title="NO COACHES FOUND." body="Try a different name, team, or role." /> : <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((coach) => <Link key={coach.id} href={`/coaches/${coach.profileId}`} className="group rounded-2xl border border-white/10 bg-white/[0.04] p-6 transition hover:-translate-y-1 hover:border-rcl-gold/60"><p className="text-xs font-bold uppercase tracking-widest text-rcl-gold">{coach.title}</p><h2 className="mt-2 font-display text-2xl font-bold group-hover:text-rcl-gold">{coach.name}</h2><p className="mt-1 text-sm text-gray-400">{coach.team ?? 'Team assignment pending'}</p>{coach.wins === null ? <p className="mt-6 border-t border-white/10 pt-4 text-sm text-gray-500">No official record available</p> : <p className="mt-6 border-t border-white/10 pt-4 font-display text-xl font-bold">{coach.wins}–{coach.losses} <span className="text-xs font-normal uppercase text-gray-500">team record</span></p>}</Link>)}</div>}</div>;
}

export function NewsDirectory({ items }: { items: NewsItem[] }) {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('ALL');
  const categories = [...new Set(items.map((item) => item.category).filter(Boolean))];
  const filtered = items.filter((item) => `${item.title} ${item.excerpt ?? ''} ${item.category}`.toLowerCase().includes(query.toLowerCase()) && (category === 'ALL' || item.category === category));
  return <div><div className="mb-8 flex flex-col gap-3 sm:flex-row"><label className="flex-1"><span className="sr-only">Search RCL News</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search RCL News..." className="w-full rounded-xl border border-white/10 bg-white/[0.05] px-4 py-3 text-sm text-white outline-none focus:border-rcl-gold" /></label><select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-xl border border-white/10 bg-rcl-navy px-4 py-3 text-sm text-white outline-none"><option value="ALL">All categories</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select></div>{!items.length ? <EmptyState title="NO STORIES YET." body="Official RCL news will appear here once the league begins publishing." /> : <div className="grid gap-5 md:grid-cols-2">{filtered.map((item) => <Link key={item.id} href={`/news/${item.slug}`} className="group overflow-hidden rounded-2xl border border-white/10 bg-white/[0.04] transition hover:border-rcl-gold/60">{item.coverImageUrl && <img src={item.coverImageUrl} alt="" className="h-44 w-full object-cover transition group-hover:scale-105" />}<div className="p-6"><p className="text-xs font-bold uppercase tracking-widest text-rcl-gold">{item.category}</p><h2 className="mt-3 font-display text-2xl font-bold group-hover:text-rcl-gold">{item.title}</h2>{item.excerpt && <p className="mt-3 text-sm leading-6 text-gray-400">{item.excerpt}</p>}<p className="mt-5 text-xs text-gray-500">{item.publishedAt ? new Date(item.publishedAt).toLocaleDateString() : 'RCL News'}</p></div></Link>)}</div>}</div>;
}

export function MediaDirectory({ items }: { items: MediaItem[] }) {
  const [category, setCategory] = useState('ALL');
  const categories = [...new Set(items.map((item) => item.type))];
  const filtered = items.filter((item) => category === 'ALL' || item.type === category);
  return <div><div className="mb-8 flex gap-2 overflow-x-auto pb-2"><button onClick={() => setCategory('ALL')} className={`whitespace-nowrap rounded-full border px-4 py-2 text-xs font-bold uppercase ${category === 'ALL' ? 'border-rcl-gold bg-rcl-gold text-black' : 'border-white/10 text-gray-400'}`}>All</button>{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-xs font-bold uppercase ${category === item ? 'border-rcl-gold bg-rcl-gold text-black' : 'border-white/10 text-gray-400'}`}>{item}</button>)}</div>{!items.length ? <EmptyState title="THE CAMERA IS READY." body="Official RCL photos, highlights, interviews, and features will appear here as they're published." /> : <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.04]"><div className="aspect-video bg-black"><img src={item.url} alt={item.title} className="h-full w-full object-cover" /></div><div className="p-5"><p className="text-xs font-bold uppercase tracking-widest text-rcl-gold">{item.type}</p><h2 className="mt-2 font-display text-xl font-bold">{item.title}</h2>{item.description && <p className="mt-2 text-sm text-gray-400">{item.description}</p>}<p className="mt-4 text-xs text-gray-500">{new Date(item.createdAt).toLocaleDateString()}</p></div></article>)}</div>}</div>;
}
