import Link from 'next/link';
import { FaArrowRight, FaChartLine, FaCircleExclamation, FaCreditCard, FaCrown, FaDollarSign, FaPeopleGroup, FaStar } from 'react-icons/fa6';
import { Container } from '@/components/Container';
import { getServerSupabaseClient } from '@/lib/supabase-server';
import { stripeBillingConfigured } from '@/lib/stripe-billing';

export const dynamic = 'force-dynamic';

type Subscription={user_id:string;plan_code:string;status:string;billing_interval:string;price_cents:number|null;current_period_end:string|null;created_at:string};
type Spotlight={id:string;user_id:string;status:string;target_type:string;requested_month:string;created_at:string};

function money(cents:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100)}

export default async function RevenueCenterPage(){
 const supabase=await getServerSupabaseClient();const db=supabase as any;
 const [{data:subscriptionsRaw},{data:spotlightsRaw},{data:webhooksRaw},{count:memberCount}]=db?await Promise.all([
  db.from('member_subscriptions').select('user_id,plan_code,status,billing_interval,price_cents,current_period_end,created_at').order('created_at',{ascending:false}),
  db.from('member_spotlight_requests').select('id,user_id,status,target_type,requested_month,created_at').order('created_at',{ascending:false}).limit(20),
  db.from('membership_webhook_events').select('provider_event_id,event_type,processing_status,error_message,processed_at').order('processed_at',{ascending:false}).limit(20),
  db.from('profiles').select('id',{count:'exact',head:true}).eq('is_active',true),
 ]):[{data:[]},{data:[]},{data:[]},{count:0}];
 const subscriptions=(subscriptionsRaw??[]) as Subscription[];const spotlights=(spotlightsRaw??[]) as Spotlight[];const active=subscriptions.filter(s=>['active','trialing'].includes(s.status));const mrrCents=Math.round(active.reduce((sum,s)=>sum+(s.billing_interval==='annual'?(s.price_cents??0)/12:(s.price_cents??0)),0));const arrCents=mrrCents*12;const plus=active.filter(s=>s.plan_code==='rcl_plus').length;const allAccess=active.filter(s=>s.plan_code==='all_access').length;const pastDue=subscriptions.filter(s=>['past_due','unpaid'].includes(s.status)).length;const conversion=memberCount?active.length/memberCount*100:0;const pendingSpotlights=spotlights.filter(s=>s.status==='pending').length;const failedWebhooks=(webhooksRaw??[]).filter((row:any)=>row.processing_status==='failed').length;const billingReady=stripeBillingConfigured();
 return <main className="min-h-screen bg-[#03070d] pb-28 text-white"><section className="border-b border-white/10 bg-[radial-gradient(circle_at_80%_10%,rgba(59,130,246,.16),transparent_32%),#050a10] py-12"><Container maxWidth="xl"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.25em] text-rcl-orange">RCL Admin · Revenue</p><h1 className="mt-3 font-display text-4xl font-black uppercase sm:text-6xl">Revenue Center</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/45">Subscription run-rate, plan mix, billing health and premium-member operations in one place.</p></div><Link href="/membership" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/15 px-4 text-xs font-black uppercase">Public membership page <FaArrowRight/></Link></div></Container></section><Container maxWidth="xl" className="py-8">
 <div className={`mb-6 rounded-2xl border p-4 text-sm ${billingReady?'border-emerald-400/20 bg-emerald-400/[.05] text-emerald-100':'border-amber-300/20 bg-amber-300/[.05] text-amber-100'}`}>{billingReady?'Stripe secret configuration is present. Checkout still requires all configured Price IDs and webhook setup.':'Stripe is not connected yet. Membership product and entitlements are live, but paid checkout remains safely unavailable.'}</div>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Metric icon={<FaDollarSign/>} label="MRR run-rate" value={money(mrrCents)}/><Metric icon={<FaChartLine/>} label="ARR run-rate" value={money(arrCents)}/><Metric icon={<FaPeopleGroup/>} label="Paid members" value={String(active.length)}/><Metric icon={<FaCrown/>} label="All Access" value={String(allAccess)}/><Metric icon={<FaCreditCard/>} label="RCL+" value={String(plus)}/><Metric icon={<FaChartLine/>} label="Paid conversion" value={`${conversion.toFixed(1)}%`}/></section>
 <section className="mt-6 grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><article className="rounded-3xl border border-white/10 bg-white/[.02] p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-blue">Membership health</p><h2 className="mt-2 font-display text-2xl font-black uppercase">Subscriptions</h2></div><span className="text-xs font-black uppercase text-white/30">{subscriptions.length} records</span></div><div className="mt-5 space-y-3">{subscriptions.length?subscriptions.slice(0,15).map((s,i)=><div key={`${s.user_id}-${i}`} className="grid gap-2 rounded-2xl border border-white/10 bg-black/20 p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><b className="text-sm uppercase">{s.plan_code.replace('_',' ')}</b><p className="mt-1 text-xs text-white/35">User {s.user_id.slice(0,8)}… · {s.billing_interval}</p></div><span className={`text-xs font-black uppercase ${['active','trialing'].includes(s.status)?'text-emerald-300':s.status==='past_due'?'text-amber-300':'text-white/45'}`}>{s.status}</span><b>{money(s.price_cents??0)}</b></div>):<Empty text="No paid subscription records yet."/>}</div></article><article className="rounded-3xl border border-white/10 bg-[#071018] p-6"><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-orange">Attention</p><h2 className="mt-2 font-display text-2xl font-black uppercase">Revenue operations</h2><div className="mt-5 space-y-3"><Health label="Past due / unpaid" value={pastDue} warn={pastDue>0}/><Health label="Pending Spotlights" value={pendingSpotlights} warn={pendingSpotlights>0}/><Health label="Recent webhook failures" value={failedWebhooks} warn={failedWebhooks>0}/><Health label="Active RCL profiles" value={memberCount??0}/></div></article></section>
 <section className="mt-6 grid gap-6 lg:grid-cols-2"><article className="rounded-3xl border border-amber-300/20 bg-amber-300/[.025] p-6"><div className="flex items-center gap-3"><FaStar className="text-amber-300"/><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-amber-300">All Access</p><h2 className="font-display text-2xl font-black uppercase">Spotlight queue</h2></div></div><div className="mt-5 space-y-3">{spotlights.length?spotlights.map(s=><div key={s.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-center justify-between gap-3"><b className="text-sm uppercase">{s.target_type} Spotlight</b><span className="text-xs font-black uppercase text-amber-200">{s.status}</span></div><p className="mt-2 text-xs text-white/35">Member {s.user_id.slice(0,8)}… · {new Date(s.created_at).toLocaleDateString()}</p></div>):<Empty text="No Spotlight requests yet."/>}</div></article><article className="rounded-3xl border border-white/10 bg-white/[.02] p-6"><div className="flex items-center gap-3"><FaCircleExclamation className="text-rcl-blue"/><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-rcl-blue">Accounting boundary</p><h2 className="font-display text-2xl font-black uppercase">Run-rate ≠ cash collected</h2></div></div><p className="mt-5 text-sm leading-7 text-white/45">MRR and ARR here are subscription run-rate based on active membership records. This dashboard intentionally does not label those amounts as collected revenue. Stripe settlement, refunds, fees and payout reconciliation can be added after the live billing account is connected.</p></article></section>
 </Container></main>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <article className="rounded-2xl border border-white/10 bg-white/[.02] p-5"><span className="text-rcl-orange">{icon}</span><p className="mt-4 text-[9px] font-black uppercase tracking-wider text-white/30">{label}</p><p className="mt-1 font-display text-3xl font-black">{value}</p></article>}
function Health({label,value,warn=false}:{label:string;value:number;warn?:boolean}){return <div className="flex items-center justify-between rounded-xl border border-white/10 bg-black/20 p-4"><span className="text-xs font-bold text-white/55">{label}</span><b className={warn?'text-amber-300':'text-white'}>{value}</b></div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-white/35">{text}</div>}
