'use client';

import Link from 'next/link';
import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database';
import { Container } from '@/components/Container';
import { getSupabaseClient } from '@/lib/supabase';
import { useAuth } from '@/hooks/useAuth';
import { FaArrowLeft, FaBasketball, FaBullhorn, FaCamera, FaCompass, FaFire, FaHouse, FaMagnifyingGlass, FaShieldHalved, FaUserGroup } from 'react-icons/fa6';

const roleCards = [
  { id: 'player' as const, icon: FaBasketball, title: 'PLAYER', subtitle: 'Compete & build your stats', detail: 'Create your player identity, follow your career, rankings, badges and team activity.', accent: 'border-rcl-orange/40 bg-rcl-orange/10' },
  { id: 'official' as const, icon: FaBullhorn, title: 'OFFICIAL', subtitle: 'Coach, referee or league staff', detail: 'Request an official role. League administrators verify access before protected tools unlock.', accent: 'border-rcl-blue/40 bg-rcl-blue/10' },
  { id: 'fan' as const, icon: FaUserGroup, title: 'FAN', subtitle: 'Follow the city', detail: 'Build your fan identity, collect badges, join fantasy and connect with the RCL community.', accent: 'border-rcl-gold/40 bg-rcl-gold/10' },
];
type SelectedRole = 'fan' | 'player' | 'official';

export default function ProfilePage() {
  const { user, profile } = useAuth(); const supabase = useMemo(() => getSupabaseClient(), []);
  const avatarInputRef = useRef<HTMLInputElement>(null); const coverInputRef = useRef<HTMLInputElement>(null); const [uploading, setUploading] = useState<'avatar'|'cover'|null>(null); const [displayName, setDisplayName] = useState(''); const [bio, setBio] = useState(''); const [location, setLocation] = useState(''); const [avatarUrl, setAvatarUrl] = useState(''); const [coverUrl, setCoverUrl] = useState(''); const [visibility, setVisibility] = useState<'public' | 'friends' | 'private'>('public'); const [role, setRole] = useState<SelectedRole>('fan'); const [saved, setSaved] = useState(false); const [error, setError] = useState('');
  useEffect(() => { setDisplayName(profile?.display_name ?? ''); setBio(profile?.bio ?? ''); setLocation(profile?.location ?? ''); setAvatarUrl(profile?.avatar_url ?? ''); setCoverUrl(profile?.cover_url ?? ''); setVisibility(profile?.profile_visibility ?? 'public'); if (profile?.role === 'player' || profile?.role === 'coach' || profile?.role === 'fan') setRole(profile.role === 'coach' ? 'official' : profile.role); }, [profile]);
  const uploadProfileImage = async (kind: 'avatar'|'cover', file?: File) => {
    if (!file || !supabase || !user) return;
    setError('');
    if (!file.type.startsWith('image/')) { setError('Choose an image file.'); return; }
    if (file.size > 5 * 1024 * 1024) { setError('Profile images must be 5 MB or smaller.'); return; }
    setUploading(kind);
    const extension = file.name.split('.').pop()?.toLowerCase() || 'jpg';
    const path = `${user.id}/profile/${kind}-${Date.now()}.${extension}`;
    const { error: uploadError } = await supabase.storage.from('avatars').upload(path, file, { upsert: false, contentType: file.type });
    if (uploadError) { setError(uploadError.message || 'Unable to upload image.'); setUploading(null); return; }
    const { data } = supabase.storage.from('avatars').getPublicUrl(path);
    if (kind === 'avatar') setAvatarUrl(data.publicUrl); else setCoverUrl(data.publicUrl);
    setUploading(null);
  };
  const save = async (event: FormEvent) => {
    event.preventDefault(); setSaved(false); setError(''); if (!supabase || !user) return;
    const writeClient = supabase as unknown as SupabaseClient;
    const profileResult = await writeClient.from('profiles').update({ display_name: displayName.trim() || null, bio: bio.trim() || null, location: location.trim() || null, avatar_url: avatarUrl.trim() || null, cover_url: coverUrl.trim() || null, profile_visibility: visibility }).eq('id', user.id);
    if (profileResult.error) { setError('Unable to save your profile details.'); return; }
    const requestedRole = role === 'official' ? 'coach' : role;
    const existingRole = await writeClient.from('profile_roles').select('role,status').eq('profile_id', user.id).eq('role', requestedRole).maybeSingle();
    if (existingRole.error) { setError(existingRole.error.message || 'Unable to verify your role.'); return; }
    if (!existingRole.data) {
      const roleRequest: Partial<Database['public']['Tables']['profile_roles']['Insert']> = { profile_id: user.id, role: requestedRole, status: 'pending', verified_at: null, verified_by: null };
      const roleResult = await writeClient.from('profile_roles').insert(roleRequest);
      if (roleResult.error) { setError(roleResult.error.message || 'Unable to submit your role request.'); return; }
    }
    if (role === 'fan') { const existingFan = await writeClient.from('fan_profiles').select('profile_id').eq('profile_id', user.id).maybeSingle(); if (existingFan.error) { setError(existingFan.error.message || 'Unable to verify your fan profile.'); return; } if (!existingFan.data) { const fanResult = await writeClient.from('fan_profiles').insert({ profile_id: user.id, favorite_team_id: null, fan_level: 1, games_attended: 0 }); if (fanResult.error) { setError(fanResult.error.message || 'Unable to create your fan profile.'); return; } } }
    setSaved(true);
  };
  const isAdmin = profile?.role === 'admin';
  return <main className="min-h-screen bg-rcl-black pb-28 text-white"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#05080d]/95 backdrop-blur-xl"><Container maxWidth="xl" className="flex h-20 items-center gap-3"><Link href="/social" className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-white/10 bg-black/40 text-rcl-orange" aria-label="Back to Social"><FaArrowLeft /></Link><div className="flex h-11 min-w-0 flex-1 items-center gap-3 rounded-2xl border border-rcl-blue/40 bg-[#07111b] px-4 text-white/40"><FaMagnifyingGlass/><span className="truncate text-sm">Search players, teams, runs…</span></div></Container></header><Container maxWidth="xl" className="py-5 sm:py-8"><div className="mx-auto max-w-3xl"><div className="mb-5"><p className="text-[10px] font-black tracking-[.24em] text-rcl-orange">PROFILE</p><h1 className="mt-2 font-display text-3xl font-black uppercase sm:text-4xl">Edit your <span className="text-rcl-orange">profile</span></h1><p className="mt-2 text-sm leading-6 text-white/50">Customize how you show up on Rich City League.</p></div>
    {user ? <form onSubmit={save} className="grid gap-5"><section className="rounded-3xl border border-rcl-blue/30 bg-white/[.025] p-5 shadow-2xl sm:p-7"><div className="mb-5 overflow-hidden rounded-2xl border border-rcl-blue/30 bg-black/20"><div className="relative h-44 bg-gradient-to-br from-rcl-navy to-black">{coverUrl&&<img src={coverUrl} alt="Cover preview" className="h-full w-full object-cover"/>}<button type="button" onClick={()=>coverInputRef.current?.click()} className="absolute right-3 top-3 inline-flex items-center gap-2 rounded-xl bg-black/80 px-3 py-2 text-[10px] font-black uppercase tracking-wider"><FaCamera/>{uploading==='cover'?'Uploading…':'Change cover'}</button><input ref={coverInputRef} type="file" accept="image/*" className="hidden" onChange={e=>void uploadProfileImage('cover',e.target.files?.[0])}/><div className="absolute -bottom-10 left-5"><button type="button" onClick={()=>avatarInputRef.current?.click()} className="relative block h-24 w-24 overflow-hidden rounded-full border-4 border-[#0b1119] bg-rcl-orange">{avatarUrl?<img src={avatarUrl} alt="Profile preview" className="h-full w-full object-cover"/>:<span className="grid h-full w-full place-items-center text-2xl font-black text-black">{displayName?.[0]??'R'}</span>}<span className="absolute bottom-0 right-0 grid h-8 w-8 place-items-center rounded-full bg-white text-black"><FaCamera/></span></button><input ref={avatarInputRef} type="file" accept="image/*" className="hidden" onChange={e=>void uploadProfileImage('avatar',e.target.files?.[0])}/></div></div><div className="px-5 pb-4 pt-14"><p className="text-[10px] font-black uppercase tracking-[.18em] text-white/40">Basic information</p></div></div><div className="grid gap-3 md:grid-cols-3">{roleCards.map(({id,icon:Icon,title,subtitle,detail,accent})=><button type="button" key={id} onClick={()=>setRole(id)} className={`rounded-2xl border p-4 text-left transition ${role===id?accent:'border-white/10 bg-black/20 hover:border-white/25'}`}><div className="flex items-center justify-between"><Icon className={role===id?'text-rcl-orange':'text-white/40'}/><span className={`h-2 w-2 rounded-full ${role===id?'bg-rcl-orange':'bg-white/10'}`}/></div><p className="mt-5 font-display text-lg font-black">{title}</p><p className="mt-1 text-xs font-semibold text-white/70">{subtitle}</p><p className="mt-3 text-[11px] leading-5 text-white/45">{detail}</p></button>)}</div>
      {isAdmin&&<div className="mt-4 flex gap-3 rounded-2xl border border-rcl-gold/30 bg-rcl-gold/10 p-4 text-sm"><FaShieldHalved className="mt-1 text-rcl-gold"/><p><strong>ADMIN ACCESS</strong><br/><span className="text-white/60">Administrator permissions are controlled by league authorization and cannot be granted from this form.</span></p></div>}
      <div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="block text-xs font-black uppercase tracking-widest text-white/45">Display name<input value={displayName} onChange={e=>setDisplayName(e.target.value)} maxLength={80} className="mt-2 w-full rounded-xl border border-white/10 bg-black/40 px-4 py-3 text-sm text-white outline-none focus:border-rcl-orange"/></label><div><p className="text-xs font-black uppercase tracking-widest text-white/45">Account role</p><p className="mt-2 rounded-xl border border-white/10 bg-white/[.02] px-4 py-3 text-sm text-white/55">{profile?.username?`@${profile.username}`:role.toUpperCase()}</p></div></div>
      <label className="mt-5 block text-xs font-black uppercase tracking-widest text-white/45">Bio<textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength={500} placeholder="Tell the RCL community who you are…" className="mt-2 h-32 w-full resize-none rounded-xl border border-white/10 bg-black/40 px-4 py-3 text-sm text-white outline-none focus:border-rcl-orange"/><span className="mt-1 block text-right text-[9px] text-white/30">{bio.length}/500</span></label>
      <div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="block text-xs font-black uppercase tracking-widest text-white/45">Location<input value={location} onChange={e=>setLocation(e.target.value)} maxLength={100} placeholder="Richmond, VA" className="mt-2 w-full rounded-xl border border-white/10 bg-black/40 px-4 py-3 text-sm text-white outline-none focus:border-rcl-orange"/></label><label className="block text-xs font-black uppercase tracking-widest text-white/45">Profile visibility<select value={visibility} onChange={e=>setVisibility(e.target.value as 'public'|'friends'|'private')} className="mt-2 w-full rounded-xl border border-white/10 bg-black/40 px-4 py-3 text-sm text-white outline-none focus:border-rcl-orange"><option value="public">Public</option><option value="friends">Friends</option><option value="private">Private</option></select></label></div>
      <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><span className={`text-sm ${error?'text-red-300':'text-rcl-gold'}`}>{error||(saved?(role==='fan'?'Profile saved. Your fan identity is active.':'Profile saved. Your role request is pending league verification.'):'')}</span><button className="rounded-xl bg-rcl-orange px-7 py-3 font-black uppercase tracking-widest text-black transition hover:bg-white">SAVE RCL PROFILE</button></div></section>
    </form>:<div className="mt-10 rounded-3xl border border-white/10 bg-white/[.03] p-10 text-center"><p className="text-white/50">Sign in to create your RCL profile.</p><Link href="/auth/sign-in" className="mt-5 inline-flex rounded-xl bg-rcl-orange px-6 py-3 font-black uppercase text-black">Sign in</Link></div>}</div></Container><nav className="fixed inset-x-0 bottom-0 z-50 border-t border-white/10 bg-[#080b10]/95 px-4 py-2 backdrop-blur-xl"><div className="mx-auto grid max-w-3xl grid-cols-4 gap-2"><Link href="/social" className="flex items-center justify-center gap-2 rounded-2xl bg-rcl-orange px-3 py-3 text-[10px] font-black uppercase text-black"><FaFire/>Feed</Link><Link href="/social?view=discover" className="flex items-center justify-center gap-2 rounded-2xl border border-white/10 px-3 py-3 text-[10px] font-black uppercase text-white/50"><FaCompass/>Discover</Link><Link href="/runs" className="flex items-center justify-center gap-2 rounded-2xl border border-white/10 px-3 py-3 text-[10px] font-black uppercase text-white/50"><FaBasketball/>Runs</Link><Link href="/social?view=highlights" className="flex items-center justify-center gap-2 rounded-2xl border border-white/10 px-3 py-3 text-[10px] font-black uppercase text-white/50"><FaHouse/>Highlights</Link></div></nav></main>;
}
