-- Founding RCH Creators research seed
-- Private admin-only prospect pool for statewide Virginia basketball creator outreach.
-- Public listing/publication still requires admin review. Verify current affiliation,
-- availability and content rights before outreach or publication.

with seed(
  organization_name, organization_type, region, city, description,
  website_url, instagram_url, source_url, source_label, notes
) as (values
  ('Demetrius Dozier-Sherrod','creator','hampton-roads','Virginia Beach','Basketball videographer, editor and content producer; strong short-form and original-series fit.',null,'https://instagram.com/RealDealDeme','https://gondola.cc/RealDealDeme','Gondola portfolio','Priority prospect. Independent basketball work shown; verify current availability.'),
  ('Sydney Smith','creator','hampton-roads','Virginia Beach','Sports photographer/videographer with CNU men''s basketball and Hampton Roads sports experience.',null,'https://instagram.com/ssmithphoto_','https://gondola.cc/sydneysmith','Gondola portfolio','Strong 757 visual-storytelling prospect.'),
  ('Emily Lowery','creator','hampton-roads','Virginia Beach','Sports content creator, photographer, videographer and reporter based in Virginia Beach.',null,'https://instagram.com/emilylowery.photography','https://gondola.cc/EmilyLowery_Photography','Gondola portfolio','Short-form/reporting prospect; verify basketball portfolio depth.'),
  ('Jazmine McMillon','creator','hampton-roads','Hampton','Videographer, editor, photographer and content producer with Hampton men''s and women''s basketball work.',null,'https://instagram.com/Jazz_mcm','https://gondola.cc/Jazz_mcm','Gondola portfolio','Priority 757 prospect. Institutional footage requires rights clearance.'),
  ('Ryan Harvey','creator','hampton-roads','Norfolk','Norfolk sports creator with photography, videography, editing and social media experience.',null,'https://instagram.com/ryanharveyphotos','https://gondola.cc/ryanharveyphotos','Gondola portfolio','Strong regional shooter; verify basketball-specific availability.'),
  ('Brandon McLean','creator','hampton-roads','Norfolk','Creative director, videographer, editor, designer and photographer in Norfolk.',null,'https://instagram.com/BMackMadeIt','https://gondola.cc/BMackMadeIt','Gondola portfolio','Sports-first creator with original-series potential.'),
  ('Isaiah Jones','creator','hampton-roads','Norfolk','Creative services manager, photographer and videographer with Hampton Roads sports experience.',null,'https://instagram.com/isaiah_j_757','https://gondola.cc/isaiah_j_757','Gondola portfolio','Strong 757 production prospect; verify basketball fit.'),
  ('Opal Simmons','creator','hampton-roads','Norfolk','Videographer/photographer with ODU and prior Henrico basketball filming experience.','https://sites.wp.odu.edu/opalsimmonssportjournal/resume-2/',null,'https://sites.wp.odu.edu/opalsimmonssportjournal/resume-2/','ODU portfolio/resume','Basketball filming experience documented; verify current availability and contact route.'),
  ('Adrian "A.J." Justis II','creator','hampton-roads','Hampton','Hampton Roads media producer and Selah Productions leader with basketball-team ownership/media experience.','https://www.virginianeptunes.com/',null,'https://www.virginianeptunes.com/','Virginia Neptunes official site','Potential creator/production partner; discuss original Hampton Roads programming.'),
  ('Derek Floyd','creator','hampton-roads','Hampton','Media professional and Selah Productions co-owner with live-streaming, photography and videography experience.','https://www.virginianeptunes.com/',null,'https://www.virginianeptunes.com/','Virginia Neptunes official site','Potential creator/production partner; discuss 757 originals and live production.'),
  ('JET Sports Photography','media','hampton-roads','Hampton Roads','Virginia sports photography/media outlet covering 757 and 804 basketball.','https://linktr.ee/jetsports757','https://instagram.com/jetsports757','https://linktr.ee/jetsports757','Official Linktree','Media-brand prospect for galleries, shorts and regional coverage.'),
  ('The Sporting News 757','media','hampton-roads','Hampton Roads','757 sports media account with local high-school basketball audience.',null,null,'https://www.instalker.org/sp0rtingnews757','Public profile index','Verify current active channels/contact before outreach.'),

  ('Josh Faughnan','creator','central-virginia','Richmond','Richmond videographer/editor/photographer/content producer with VCU basketball work.',null,'https://instagram.com/jfproducti0ns','https://gondola.cc/jfproducti0ns','Gondola portfolio','Priority 804 prospect. Institutional footage requires rights clearance.'),
  ('Chase Wingfield','creator','central-virginia','Richmond','High-performing Richmond videographer/creator with Richmond Basketball, Virginia Tech MBB and circuit work.',null,'https://instagram.com/chasewingfield_','https://gondola.cc/chasewingfield_','Gondola portfolio','Priority short-form/story producer prospect.'),
  ('Dee Banks','creator','central-virginia','Richmond','Basketball videographer/editor with VCU men''s and women''s basketball collaborations.',null,'https://instagram.com/banksmade','https://gondola.cc/banksmade','Gondola portfolio','Priority 804 basketball creative prospect.'),
  ('Devin Summer','creator','central-virginia','Richmond','Creative media manager, videographer and editor with extensive VCU basketball work.',null,'https://instagram.com/Devin_Summer_','https://gondola.cc/Devin_Summer_','Gondola portfolio','High-skill prospect; recruit for independent original work only, not unlicensed institutional footage.'),
  ('Matthew Mitrani','creator','central-virginia','Richmond','Richmond sports photographer/videographer with VCU basketball experience.',null,'https://instagram.com/mm_snips','https://gondola.cc/mm_snips','Gondola portfolio','Photo/video prospect for 804 coverage.'),
  ('Elena Gutierrez','creator','central-virginia','Richmond','Richmond videographer/editor/photographer with Richmond basketball and VCU sports experience.',null,'https://instagram.com/elena_takes_photos','https://gondola.cc/elena_takes_photos','Gondola portfolio','Strong regional creator prospect.'),
  ('Miles / The Image LLC','creator','central-virginia','Richmond','Richmond video director/content creator and Team Loaded Basketball media leader.',null,'https://instagram.com/sdotmiles_','https://gondola.cc/sdotmiles_','Gondola portfolio','Priority grassroots/AAU pipeline prospect.'),
  ('Ada Long','creator','central-virginia','Richmond','Sports photographer/videographer working in Richmond and Charlotte.',null,'https://instagram.com/adalongphotography','https://gondola.cc/adalongphotography','Gondola portfolio','Rising creator prospect for high-school/grassroots coverage.'),
  ('Caden Woodward','creator','central-virginia','Richmond','Richmond sports videographer/editor with short-form production experience.',null,'https://instagram.com/cadenbwoodward','https://gondola.cc/cadenbwoodward','Gondola portfolio','Sports-adjacent prospect; test basketball short-form interest.'),
  ('Z Photography','creator','central-virginia','Richmond','Richmond basketball photography specialist covering youth and private-school basketball.','https://z-photography.com/sports/basketball.html',null,'https://z-photography.com/sports/basketball.html','Official portfolio','Strong photography/galleries prospect.'),
  ('Sara Warthen','creator','central-virginia','Richmond','Richmond-based filmmaker/editor who also captures content for a local basketball league.',null,null,'https://seedandspark.com/fund/otl','Seed&Spark profile','Filmmaker prospect for documentary/original storytelling; verify direct contact.'),
  ('BallinVA / Larry Merritte','media','statewide','Virginia','Virginia basketball podcast/media brand focused on athletes, coaches and statewide hoops stories.',null,null,'https://podcastrepublic.net/podcast/1624130823','Podcast listing','Priority voice/interview prospect. Public business contact previously listed as ballinvapodcast@gmail.com; verify before outreach.'),

  ('Jonaé Guest','creator','northern-virginia','Woodbridge','Basketball photographer with St. James, Capitol Hoops and Nike Pro City experience.',null,'https://instagram.com/jonae44','https://gondola.cc/jonae44','Gondola portfolio','Priority NOVA/DC basketball photography prospect.'),
  ('Brooks Ross','creator','northern-virginia','Reston','Reston sports photographer with South Lakes boys basketball experience.',null,'https://instagram.com/rossvisualzz','https://gondola.cc/rossvisualzz','Gondola portfolio','Local high-school/NOVA coverage prospect.'),
  ('Tyler Benson','creator','northern-virginia','Fairfax','Owner of Tyler Benson Productions; photographer/videographer with George Mason men''s basketball work.',null,'https://instagram.com/_BensonBoy23','https://gondola.cc/_BensonBoy23','Gondola portfolio','Priority NOVA college/creator prospect.'),
  ('Shariez Salman','creator','northern-virginia','Fairfax','Social media specialist/video creator with George Mason men''s basketball work.',null,'https://instagram.com/riezyvisuals','https://gondola.cc/riezyvisuals','Gondola portfolio','Priority short-form NOVA prospect.'),
  ('John Sondheim','creator','northern-virginia','Arlington','Arlington creator/videographer/editor/social manager with basketball production experience.',null,'https://instagram.com/shotbysonds','https://gondola.cc/shotbysonds','Gondola portfolio','Original-series/short-form prospect.'),
  ('Nick / Shifty Flicks','creator','northern-virginia','Woodbridge','DMV photographer/videographer and Team Durant media creator.',null,'https://instagram.com/shiftyflicks','https://gondola.cc/shiftyflicks','Gondola portfolio','Priority grassroots/AAU NOVA prospect.'),
  ('itsqucreated','creator','northern-virginia','Fairfax','Fairfax sports videographer/photographer/colorist with high-reach short-form work.',null,'https://instagram.com/itsqucreated','https://gondola.cc/itsqucreated','Gondola portfolio','High-upside short-form creator; verify basketball interest.'),
  ('Phoebe Winters','creator','northern-virginia','Fairfax','Fairfax creator, broadcaster, content producer and photographer.',null,'https://instagram.com/phoebe.winters','https://gondola.cc/phoebe.winters','Gondola portfolio','Sports-adjacent voice/production prospect.'),
  ('Owen Kashawlic','creator','northern-virginia','Fairfax','Creator with George Mason men''s basketball and Creators Cut work.',null,'https://instagram.com/Owenkashawlic','https://gondola.cc/Owenkashawlic','Gondola portfolio','NOVA basketball creative prospect; verify current location/availability.'),

  ('Steven Leonard','creator','other','Charlottesville','Charlottesville multi-discipline creator with Virginia men''s basketball work.',null,'https://instagram.com/_StevenLeonard_','https://gondola.cc/_StevenLeonard_','Gondola portfolio','High-skill UVA-market prospect; institutional rights clearance required.'),
  ('Karina Amos','creator','other','Charlottesville','Creative media manager with Virginia men''s basketball and major short-form basketball experience.',null,'https://instagram.com/karinaamos','https://gondola.cc/karinaamos','Gondola portfolio','Priority high-reach creator. Recruit for independent originals only.'),
  ('Jaden Hawkins','creator','other','Charlottesville','UVA-area graphic designer/photographer with Virginia men''s and women''s basketball work.',null,'https://instagram.com/jaden.hawkins14','https://gondola.cc/jaden.hawkins14','Gondola portfolio','Visual storytelling prospect.'),
  ('Nikolozi Khutsishvili','creator','other','Charlottesville','Charlottesville creator, videographer, photographer and editor.',null,'https://instagram.com/nikolozi.camera','https://gondola.cc/nikolozi.camera','Gondola portfolio','Rising general sports creator; test hoops concepts.'),
  ('Nate Goldstein','creator','other','Charlottesville','Charlottesville digital creator with JMU men''s basketball and Virginia/JMU sports work.',null,'https://instagram.com/Nategoldstein2','https://gondola.cc/Nategoldstein2','Gondola portfolio','Strong video/editor/photo prospect.'),
  ('Jackson Ploeger','creator','other','Charlottesville','Charlottesville sports creator/photographer with UVA creative-media network experience.',null,'https://instagram.com/PloegerPhotography','https://gondola.cc/PloegerPhotography','Gondola portfolio','Photography/short-form prospect.'),
  ('Gabby Valencia','creator','other','Charlottesville','UVA creative-media photographer/videographer with high-level sports production experience.',null,'https://instagram.com/ggevalencia.img','https://gondola.cc/ggevalencia.img','Gondola portfolio','Sports-adjacent prospect; recruit for independent basketball originals.'),
  ('Matt Neff','creator','other','Charlottesville','Charlottesville video-production director and editor with high-level sports storytelling experience.',null,'https://instagram.com/justneffit','https://gondola.cc/justneffit','Gondola portfolio','Experienced production prospect; verify basketball interest.'),
  ('Kyle Nguyen','creator','other','Charlottesville','Charlottesville creative-media intern, videographer, video director and photographer.',null,'https://instagram.com/urknvids','https://gondola.cc/urknvids','Gondola portfolio','Rising creator prospect.'),
  ('Taylor White / Tay','creator','other','Charlottesville','Director of multimedia/creative content for Virginia women''s basketball; videographer, editor and creative director.',null,'https://instagram.com/t.white_10','https://gondola.cc/t.white_10','Gondola portfolio','Priority storytelling prospect; institutional footage requires permission.'),
  ('Hoos Hoopin''','media','other','Charlottesville','UVA men''s basketball podcast hosted by Khari Williams and Sean Crow.','https://podcasts.apple.com/us/podcast/hoos-hoopin-a-virginia-basketball-podcast/id1653716779',null,'https://podcasts.apple.com/us/podcast/hoos-hoopin-a-virginia-basketball-podcast/id1653716779','Apple Podcasts','Voice/podcast prospect for UVA basketball programming.'),
  ('The Tonsler League Media','media','other','Charlottesville','Charlottesville summer basketball league with active livestream and social media presence.','https://linktr.ee/thetonslerleague','https://instagram.com/thetonslerleague','https://linktr.ee/thetonslerleague','Official Linktree','Potential creator/media partner and Charlottesville pipeline.'),

  ('Kaitlin Bucci','creator','shenandoah','Harrisonburg','Harrisonburg creator/videographer/editor/director with JMU men''s and women''s basketball work.',null,'https://instagram.com/kaitlinbucci','https://gondola.cc/kaitlinbucci','Gondola portfolio','Priority Valley prospect; institutional rights clearance required.'),
  ('Heather Hughes','creator','shenandoah','Harrisonburg','Harrisonburg videographer/editor with JMU men''s and women''s basketball experience.',null,'https://instagram.com/hhughes13','https://gondola.cc/hhughes13','Gondola portfolio','Priority Valley creator prospect.'),
  ('Mae O''Neill','creator','shenandoah','Harrisonburg','Videographer/editor/photographer with JMU men''s and women''s basketball collaborations.',null,'https://instagram.com/media.by.mae','https://gondola.cc/media.by.mae','Gondola portfolio','Strong rising creator prospect.'),
  ('Avery Collyer','creator','shenandoah','Harrisonburg','Videographer/editor with JMU men''s and women''s basketball work.',null,'https://instagram.com/averycmedia','https://gondola.cc/averycmedia','Gondola portfolio','Strong rising creator prospect.'),
  ('Dori Havens','creator','shenandoah','Harrisonburg','Harrisonburg photographer/editor with JMU women''s basketball work.',null,'https://instagram.com/dorihavenss','https://gondola.cc/dorihavenss','Gondola portfolio','Photography prospect.'),
  ('Leo Schlechter','creator','shenandoah','Harrisonburg','Harrisonburg photographer with JMU men''s and women''s basketball collaborations.',null,'https://instagram.com/leo.sc_j','https://gondola.cc/leo.sc_j','Gondola portfolio','Photography/visual-storytelling prospect.'),
  ('Luke Christensen','creator','shenandoah','Harrisonburg','Sports videographer, photographer and content creator with a dedicated basketball portfolio.','https://www.lukechristensen.com/','https://instagram.com/_Luke.Chris','https://www.lukechristensen.com/','Official portfolio','Priority independent creator; public portfolio lists direct contact.'),
  ('Telemedia Productions','media','shenandoah','Harrisonburg','Harrisonburg production company with collegiate basketball broadcast/live-event capability.','https://www.telemediaproductions.com/',null,'https://www.telemediaproductions.com/','Official site','Production partner prospect for western/Valley broadcasts and originals.'),
  ('Pete Jonas','creator','shenandoah','Winchester','Winchester videographer/editor with prior Vanderbilt men''s and women''s basketball work.',null,'https://instagram.com/Petejonas7','https://gondola.cc/Petejonas7','Gondola portfolio','Experienced Valley-area prospect; verify current availability.'),

  ('Jacob Sawyers','creator','southwest-virginia','Blacksburg','Blacksburg creative producer/videographer with Virginia Tech men''s and women''s basketball work.',null,'https://instagram.com/jdotsawyers','https://gondola.cc/jdotsawyers','Gondola portfolio','Priority Southwest prospect; institutional footage requires permission.'),
  ('Ryan Hedley','creator','southwest-virginia','Blacksburg','Blacksburg photographer/videographer with Virginia Tech men''s basketball work.',null,'https://instagram.com/ryanhedleymedia','https://gondola.cc/ryanhedleymedia','Gondola portfolio','Strong Southwest visual prospect.'),
  ('Henry Alves','creator','southwest-virginia','Blacksburg','Videographer/editor/director with Virginia Tech men''s and women''s basketball collaborations.',null,'https://instagram.com/h3nryalves','https://gondola.cc/h3nryalves','Gondola portfolio','Priority production prospect; verify current affiliation.'),
  ('Macey Early','creator','southwest-virginia','Blacksburg','Blacksburg content manager with Virginia Tech women''s basketball work.',null,'https://instagram.com/macey_early','https://gondola.cc/macey_early','Gondola portfolio','Short-form/social strategy prospect.'),
  ('Kendal Williams','creator','southwest-virginia','Blacksburg','Blacksburg social/content producer with Virginia Tech men''s and women''s basketball collaborations.',null,'https://instagram.com/kendal.williams','https://gondola.cc/kendal.williams','Gondola portfolio','Strong social/creator prospect; institutional/NIL rights require clearance.'),
  ('Jamaal Simmons','creator','southwest-virginia','Blacksburg','Experienced creative director, cinematographer, photographer and videographer with major sports background.',null,'https://instagram.com/Jamaal_Simmons','https://gondola.cc/Jamaal_Simmons','Gondola portfolio','High-skill production prospect; verify current Virginia availability.'),
  ('Chase Sanchez','creator','southwest-virginia','Blacksburg','Basketball creative with high-performing Virginia Tech women''s basketball content.',null,'https://instagram.com/ChaseVT','https://gondola.cc/ChaseVT','Gondola portfolio','Priority basketball short-form prospect; verify current role/availability.'),
  ('Jackson Sirbaugh','creator','southwest-virginia','Blacksburg','Blacksburg social media coordinator, photographer, videographer and editor.',null,'https://instagram.com/jsirbaughphotos','https://gondola.cc/jsirbaughphotos','Gondola portfolio','Sports-adjacent creator with strong production range.'),
  ('Will Trent','creator','southwest-virginia','Blacksburg','Blacksburg marketing/creative director, photographer and social strategist.',null,'https://instagram.com/WillyTMedia','https://gondola.cc/WillyTMedia','Gondola portfolio','Sports-adjacent original-content prospect.'),
  ('Brent Butler','creator','southwest-virginia','Roanoke','Roanoke sports photographer available for freelance work with professional sports portfolio.',null,'https://instagram.com/blizzflicks','https://gondola.cc/blizzflicks','Gondola portfolio','Priority western-Virginia photography prospect; verify basketball interest.'),
  ('Kaila McDonald','creator','southwest-virginia','Lynchburg','Lynchburg videographer/editor/social creator with Liberty men''s and women''s basketball work.',null,'https://instagram.com/Knoelmcd','https://gondola.cc/Knoelmcd','Gondola portfolio','Priority Lynchburg basketball creator prospect.'),
  ('Cullen Ecoffey','creator','southwest-virginia','Lynchburg','Lynchburg creative director/videographer/editor with Liberty men''s basketball work.',null,'https://instagram.com/CullenEcoffey','https://gondola.cc/CullenEcoffey','Gondola portfolio','Experienced original-content prospect; verify current availability.'),
  ('Emily Meyer','creator','southwest-virginia','Lynchburg','Lynchburg social/video creator with Liberty men''s and women''s basketball collaborations.',null,'https://instagram.com/emilyjowydo','https://gondola.cc/emilyjowydo','Gondola portfolio','Strong social/short-form prospect.'),
  ('Avery Mills','creator','southwest-virginia','Lynchburg','Lynchburg social media creator with Liberty women''s basketball work.',null,'https://instagram.com/averyymillss','https://gondola.cc/averyymillss','Gondola portfolio','Rising basketball creator prospect.')
)
insert into public.network_acquisition_prospects(
  organization_name,organization_type,region,city,description,
  website_url,instagram_url,source_url,source_label,notes,
  status,outreach_status
)
select
  s.organization_name,s.organization_type,s.region,s.city,s.description,
  s.website_url,s.instagram_url,s.source_url,s.source_label,s.notes,
  'staged','not-contacted'
from seed s
where not exists (
  select 1
  from public.network_acquisition_prospects p
  where lower(trim(p.organization_name))=lower(trim(s.organization_name))
    and p.status<>'archived'
)
and not exists (
  select 1
  from public.network_organizations o
  where lower(trim(o.name))=lower(trim(s.organization_name))
);
