'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { AdminWorkspace } from '@/components/AdminWorkspace';
import { Container } from '@/components/Container';
import { getSupabaseClient } from '@/lib/supabase';
import { useAuth } from '@/hooks/useAuth';
import { FaTrophy, FaMedal, FaStar } from 'react-icons/fa6';

export default function AdminRecognitionPage(){
  const {profile,loading}=useAuth();
  const db=useMemo(()=>getSupabaseClient(),[]);
  const [seasons,setSeasons]=useState<any[]>([]),[players,setPlayers]=useState<any[]>([]),[teams,setTeams]=useState<any[]>([]),[badges,setBadges]=useState<any[]>([]),[awards,setAwards]=useState<any[]>([]),[pows,setPows]=useState<any[]>([]);
  const [message,setMessage]=useState('');
  const [award,setAward]=useState({season_id:'',player_id:'',team_id:'',name:'',description:''});
  const [badge,setBadge]=useState({name:'',description:'',category:'milestone',icon:'🏆',tier:'bronze',requirement_type:'manual',requirement_value:1});
  const [grant,setGrant]=useState({player_id:'',badge_id:''});
  const [pow,setPow]=useState({player_id:'',season_id:'',week_number:1,description:''});
  const admin=profile?.role==='admin'||profile?.role==='staff';

  async function load(){if(!db||!admin)return;const [s,p,t,b,a,w]=await Promise.all([
    db.from('seasons').select('id,name').order('start_date',{ascending:false}),
    db.from('players').select('id,first_name,last_name').eq('is_active',true).order('last_name'),
    db.from('teams').select('id,name').order('name'),
    db.from('badges').select('*').order('created_at',{ascending:false}),
    db.from('awards').select('*').order('awarded_at',{ascending:false}),
    db.from('player_of_week').select('*').order('season_id').order('week_number'),
  ]);if(s.data)setSeasons(s.data);if(p.data)setPlayers(p.data);if(t.data)setTeams(t.data);if(b.data)setBadges(b.data);if(a.data)setAwards(a.data);if(w.data)setPows(w.data)}
  useEffect(()=>{void load()},[db,admin]);
  async function createAward(e:React.FormEvent){e.preventDefault();if(!db||!award.season_id||!award.name)return;const {error}=await db.from('awards').insert({...award,player_id:award.player_id||null,team_id:award.team_id||null} as never);setMessage(error?.message||'Award created.');if(!error){setAward({season_id:'',player_id:'',team_id:'',name:'',description:''});await load()}}
  async function createBadge(e:React.FormEvent){e.preventDefault();if(!db||!badge.name)return;const {error}=await db.from('badges').insert(badge as never);setMessage(error?.message||'Badge created.');if(!error){setBadge({...badge,name:'',description:''});await load()}}
  async function grantBadge(e:React.FormEvent){e.preventDefault();if(!db||!grant.player_id||!grant.badge_id)return;const {error}=await db.from('player_badges').insert({player_id:grant.player_id,badge_id:grant.badge_id} as never);setMessage(error?.message||'Badge awarded.');if(!error){setGrant({player_id:'',badge_id:''});await load()}}
  async function createPow(e:React.FormEvent){e.preventDefault();if(!db||!pow.player_id||!pow.season_id)return;const {error}=await db.from('player_of_week').insert({...pow,stats:{}} as never);setMessage(error?.message||'Player of the Week created.');if(!error)await load()}
  if(loading)return <main><AdminWorkspace/><Container maxWidth="xl" className="py-16">Checking access…</Container></main>;
  if(!admin)return <main><AdminWorkspace/><Container maxWidth="lg" className="py-16"><h1 className="rcl-display text-4xl uppercase">Admin access required</h1><Link href="/admin" className="rcl-link mt-5">Return to command center</Link></Container></main>;
  return <main className="min-h-screen pb-24 text-white"><AdminWorkspace/><Container maxWidth="xl" className="py-10"><Link href="/admin" className="rcl-link">← Command center</Link><div className="mt-8"><p className="rcl-kicker">RCL RECOGNITION</p><h1 className="rcl-display mt-2 text-5xl uppercase">Awards & badges.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/45">Control official awards, Player of the Week records, badge definitions and player recognition. Keep public recognition data tied to real league records.</p></div>{message&&<p className="mt-6 rounded-xl border border-rcl-orange/20 bg-rcl-orange/5 p-3 text-xs text-rcl-orange">{message}</p>}
  <div className="mt-8 grid gap-8 lg:grid-cols-2">
    <section className="rcl-platform-panel p-6"><p className="rcl-kicker">OFFICIAL AWARDS</p><h2 className="rcl-display mt-2 text-2xl uppercase">Create award</h2><form onSubmit={createAward} className="mt-5 grid gap-3"><select required value={award.season_id} onChange={e=>setAward({...award,season_id:e.target.value})} className="rcl-admin-field"><option value="">Season</option>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input required value={award.name} onChange={e=>setAward({...award,name:e.target.value})} className="rcl-admin-field" placeholder="Award name"/><select value={award.player_id} onChange={e=>setAward({...award,player_id:e.target.value})} className="rcl-admin-field"><option value="">Player (optional)</option>{players.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select><select value={award.team_id} onChange={e=>setAward({...award,team_id:e.target.value})} className="rcl-admin-field"><option value="">Team (optional)</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><textarea value={award.description} onChange={e=>setAward({...award,description:e.target.value})} className="rcl-admin-field" placeholder="Description"/><button className="rcl-button"><FaTrophy/> Create award</button></form></section>
    <section className="rcl-platform-panel p-6"><p className="rcl-kicker">PLAYER OF THE WEEK</p><h2 className="rcl-display mt-2 text-2xl uppercase">Publish weekly honor</h2><form onSubmit={createPow} className="mt-5 grid gap-3"><select required value={pow.season_id} onChange={e=>setPow({...pow,season_id:e.target.value})} className="rcl-admin-field"><option value="">Season</option>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select required value={pow.player_id} onChange={e=>setPow({...pow,player_id:e.target.value})} className="rcl-admin-field"><option value="">Player</option>{players.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select><input required type="number" min="1" value={pow.week_number} onChange={e=>setPow({...pow,week_number:Number(e.target.value)})} className="rcl-admin-field" placeholder="Week"/><textarea required value={pow.description} onChange={e=>setPow({...pow,description:e.target.value})} className="rcl-admin-field" placeholder="Why this player earned it"/><button className="rcl-button"><FaStar/> Publish Player of the Week</button></form></section>
    <section className="rcl-platform-panel p-6"><p className="rcl-kicker">BADGE DEFINITION</p><h2 className="rcl-display mt-2 text-2xl uppercase">Create badge</h2><form onSubmit={createBadge} className="mt-5 grid gap-3"><input required value={badge.name} onChange={e=>setBadge({...badge,name:e.target.value})} className="rcl-admin-field" placeholder="Badge name"/><input required value={badge.description} onChange={e=>setBadge({...badge,description:e.target.value})} className="rcl-admin-field" placeholder="Description"/><div className="grid grid-cols-2 gap-3"><input value={badge.icon} onChange={e=>setBadge({...badge,icon:e.target.value})} className="rcl-admin-field" placeholder="Icon"/><select value={badge.tier} onChange={e=>setBadge({...badge,tier:e.target.value})} className="rcl-admin-field">{['bronze','silver','gold','elite'].map(v=><option key={v}>{v}</option>)}</select></div><input value={badge.category} onChange={e=>setBadge({...badge,category:e.target.value})} className="rcl-admin-field" placeholder="Category"/><input value={badge.requirement_type} onChange={e=>setBadge({...badge,requirement_type:e.target.value})} className="rcl-admin-field" placeholder="Requirement type"/><input type="number" min="0" value={badge.requirement_value} onChange={e=>setBadge({...badge,requirement_value:Number(e.target.value)})} className="rcl-admin-field" placeholder="Requirement value"/><button className="rcl-button"><FaMedal/> Create badge</button></form></section>
    <section className="rcl-platform-panel p-6"><p className="rcl-kicker">RECOGNITION CONTROL</p><h2 className="rcl-display mt-2 text-2xl uppercase">Award a badge</h2><form onSubmit={grantBadge} className="mt-5 grid gap-3"><select required value={grant.player_id} onChange={e=>setGrant({...grant,player_id:e.target.value})} className="rcl-admin-field"><option value="">Player</option>{players.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select><select required value={grant.badge_id} onChange={e=>setGrant({...grant,badge_id:e.target.value})} className="rcl-admin-field"><option value="">Badge</option>{badges.filter(b=>b.is_active).map(b=><option key={b.id} value={b.id}>{b.icon} {b.name}</option>)}</select><button className="rcl-button"><FaMedal/> Award badge</button></form></section>
  </div>
  <div className="mt-8 grid gap-8 lg:grid-cols-2"><section className="rcl-platform-panel p-6"><div className="rcl-panel-heading"><span>Awards</span><b>{awards.length}</b></div><div className="max-h-80 space-y-2 overflow-auto p-4">{awards.map(a=><div key={a.id} className="rounded-xl border border-white/5 p-3 text-xs"><b>{a.name}</b><span className="ml-2 text-white/35">{new Date(a.awarded_at).toLocaleDateString()}</span><p className="mt-1 text-white/40">{a.description||'No description'}</p></div>)}</div></section><section className="rcl-platform-panel p-6"><div className="rcl-panel-heading"><span>Player of the Week</span><b>{pows.length}</b></div><div className="max-h-80 space-y-2 overflow-auto p-4">{pows.map(w=><div key={w.id} className="rounded-xl border border-white/5 p-3 text-xs"><b>{players.find(p=>p.id===w.player_id)?.first_name} {players.find(p=>p.id===w.player_id)?.last_name}</b><span className="ml-2 text-white/35">Week {w.week_number}</span><p className="mt-1 text-white/40">{w.description}</p></div>)}</div></section></div>
  </Container></main>
}
